### ISSUE TITLE
Build on windows

### ISSUE THREAD

**Issue by lucasjinreal** [pytorch/executorch#1000]
Is it support build on windows and link executorch for windows inference? (without libtorch

**Comment by kimishpatel** [comment]
Windows support is not there at the moment, but we will be looking into it soon.

**Comment by dbort** [comment]
@lucasjinreal what sort of build environment would you want? E.g., we technically build on windows under WSL, but that's probably not what you're looking for ;)

**Comment by TingfengTang** [comment]
After i get the model using torch.export.export():
model_ep=torch.export.export(model,input)
how to deploy the model model_ep on windows x86_64 like torchscript using C++?

**Comment by lucasjinreal** [comment]
From the dialog above, windows not support for now.

**Comment by Gasoonjia** [comment]
Seems the question has been solved. Close for now.

**Comment by lucasjinreal** [comment]
Any instructions build on windows?
