### ISSUE TITLE
can not run install_flatc.sh sucecessfully 

### ISSUE THREAD

**Issue by luxunxiansheng** [pytorch/executorch#1004]
When following the instructions given by the [tutorial](https://pytorch.org/executorch/stable/getting-started-setup.html),  Cmake error occured:

executorch/third-party/flatbuffers" does not appear to contain CMakeLists.txt.

I missed something?

**Comment by kimishpatel** [comment]
Did you do `git submodule sync/update`? If you inspect third-party/flatbuffers folders and it is empty then likely submodule has not been fetched.

**Comment by luxunxiansheng** [comment]
> Did you do `git submodule sync/update`? If you inspect third-party/flatbuffers folders and it is empty then likely submodule has not been fetched.

I did run that commads but as you said the folder is empty.  Is there any workarond before the bug fixed?

**Comment by kimishpatel** [comment]
When I have run into this in past, I have done manual fetch or update of the submodule

try `git submodule init` and then sync. more details https://git-scm.com/book/en/v2/Git-Tools-Submodules

Also add your repro steps here

**Comment by luxunxiansheng** [comment]
> git submodule sync

I follow the steps given in tutorai.  sync/ update --init . 
Now a fatal occured :

 fatal: unable to access 'https://git.mlplatform.org/ml/ethos-u/ethos-u-core-driver.git/': server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
fatal: clone of 'https://git.mlplatform.org/ml/ethos-u/ethos-u-core-driver.git' into submodule path 'backends/arm/third-party/ethos-u-core-driver' failed

Is it for this ?

**Comment by luxunxiansheng** [comment]
> Usually these following commands can get me the submodules
> 
> ```
> git submodule update --init
> git submodule update
> git submodule sync
> ```
> 
> Are all the folders in `executorch/third-party` empty?
 all the folders in 'executorch/third-party' are empty.

**Comment by cccclai** [comment]
Hmm that's for the arm backend. Seperately, are there contents inside `executorch/third-party/flatbuffers` now?

**Comment by luxunxiansheng** [comment]
> Hmm that's for the arm backend. Seperately, are there contents inside `executorch/third-party/flatbuffers` now?

No contents as before.

**Comment by kimishpatel** [comment]
> try git submodule init and then sync. more details https://git-scm.com/book/en/v2/Git-Tools-Submodules

@luxunxiansheng did you try following these steps?

**Comment by luxunxiansheng** [comment]
Yes, I tried different combinations of commands. No helps.

**Comment by kimishpatel** [comment]
Something seems off in your setup. Have you tried starting from scratch again?

I tried following tutorial in a fresh dir and it seems to clone flatbuffers correctly for me.

Can you paste log of what happened (just terminal capture) when you follow the steps of clone + submodule update?

**Comment by luxunxiansheng** [comment]
![image](https://github.com/pytorch/executorch/assets/26159816/d3cf6661-eccf-4c0e-a36a-3fe32cb82eba)

**Comment by luxunxiansheng** [comment]
> Something seems off in your setup. Have you tried starting from scratch again?
> 
> I tried following tutorial in a fresh dir and it seems to clone flatbuffers correctly for me.
> 
> Can you paste log of what happened (just terminal capture) when you follow the steps of clone + submodule update?

Is the screen shot helpful ?

**Comment by luxunxiansheng** [comment]
> > > Something seems off in your setup. Have you tried starting from scratch again?
> > > I tried following tutorial in a fresh dir and it seems to clone flatbuffers correctly for me.
> > > Can you paste log of what happened (just terminal capture) when you follow the steps of clone + submodule update?
> > 
> > 
> > Is the screen shot helpful ?
> 
> Did you try
> 
> ```
> git submodule sync
> git submodule update --init
> ```
> 
> What is the output you saw for that?

![image](https://github.com/pytorch/executorch/assets/26159816/2cf04b03-bd40-4947-b6a8-4b52c0518da1)

**Comment by robell** [comment]
It looks like the submodule call fails as it tries to clone ethos-u first and other modules don't clone after that. 

I can see no issues with the certificate and can fetch and browse to that repository. @luxunxiansheng can you browse (web browser) to https://git.mlplatform.org/ml/ethos-u/ethos-u-core-driver.git/ ? perhaps there is a certificate issue with the LetsEncrypt root cert?

What version of git are you using? (git --version)

**Comment by kimishpatel** [comment]
Thanks @robell . Sounds like thats the issue. @digantdesai @robell ideally we bring in these dep as part of "install requirements" of specific delegates.

**Comment by luxunxiansheng** [comment]
> It looks like the submodule call fails as it tries to clone ethos-u first and other modules don't clone after that.
> 
> I can see no issues with the certificate and can fetch and browse to that repository. @luxunxiansheng can you browse (web browser) to https://git.mlplatform.org/ml/ethos-u/ethos-u-core-driver.git/ ? perhaps there is a certificate issue with the LetsEncrypt root cert on your machine?
> 
> What version of git are you using? (git --version)
My server doesn't have desktop that I can't visit the link via browser. But I can visit it from other machine.   
My git version is 2.39.2

**Comment by robell** [comment]
@kimishpatel that would be a longer term fix, in the short term it appears to be a certificate issue on the end system @luxunxiansheng has. An easy workaround would be to remove the sub-module locally if as it seems no one else has this issue.

@luxunxiansheng:
1. can you access (with a web browser)  https://git.mlplatform.org/ml/ethos-u/ethos-u-core-driver.git/ ? 
2. The certificates look correct and other people are able to clone this repo, what happens if you: `git clone --progress --verbose  https://git.mlplatform.org/ml/ethos-u/ethos-u-core-driver.git/`
3. what about output for`wget -vd https://git.mlplatform.org/ml/ethos-u/ethos-u-core-driver.git/`

**Comment by luxunxiansheng** [comment]
2. ![image](https://github.com/pytorch/executorch/assets/26159816/0c7d9ced-f172-41a0-99ea-f8922fbe151e)
3. I can get the index.html

**Comment by luxunxiansheng** [comment]
> @kimishpatel that would be a longer term fix, in the short term it appears to be a certificate issue on the end system @luxunxiansheng has. An easy workaround would be to remove the sub-module locally if as it seems no one else has this issue.
> 
> @luxunxiansheng:
> 
> 1. can you access (with a web browser)  https://git.mlplatform.org/ml/ethos-u/ethos-u-core-driver.git/ ?
> 2. The certificates look correct and other people are able to clone this repo, what happens if you: `git clone --progress --verbose  https://git.mlplatform.org/ml/ethos-u/ethos-u-core-driver.git/`
> 3. what about output for`wget -vd https://git.mlplatform.org/ml/ethos-u/ethos-u-core-driver.git/`

My server doesn't have desktop that I can't visit the link via browser. But I can visit it from other machine. BTW.

**Comment by robell** [comment]
can you try the wget command? this might help show whether the certificates file has a problem on the server.

**Comment by luxunxiansheng** [comment]
> can you try the wget command? this might help show whether the certificates file has a problem on the server.

![image](https://github.com/pytorch/executorch/assets/26159816/b1687dc0-c531-498b-b244-9f9baf76a125)

**Comment by robell** [comment]
Ok, so we can see the ssl cert is valid and this machine can read via https in wget; it seems a problem then with git's use of ssl certificates in /etc/ssl/certs/.

I suspect the issue is your server has a configuration problem with /etc/ssl/certs/ca-certificates.crt, used by git, not containing the letsencrypt root certificate, and depending on your linux distro, fetching a newer version of this will be needed. e.g. on ubuntu, you would need https://manpages.ubuntu.com/manpages/xenial/man8/update-ca-certificates.8.html 

An alternative workaround would be to remove the ethos-u submodule as this isn't relevant for you: https://www.educative.io/answers/how-to-delete-a-git-submodule (though you of course cannot push this change back). if you just want to get it working, i'd suggest trying this second option.

**Comment by luxunxiansheng** [comment]
> Ok, so we can see the ssl cert is valid and this machine can read via https in wget; it seems a problem then with git's use of ssl certificates in /etc/ssl/certs/.
> 
> A workaround would be to try `git config --global http.sslVerify "false"` (but be aware this disables all verification of certificates!)
> 
> An alternative workaround would be to remove the ethos-u submodule as this isn't relevant for you: https://www.educative.io/answers/how-to-delete-a-git-submodule (though you of course cannot push this change back). if you just want to get it working, i'd suggest trying this second option.

Sorry to bother you agagin and  again .  But it did not work when I tried the  second option. I think I have remove the submodule. 
![image](https://github.com/pytorch/executorch/assets/26159816/e711af6b-1a31-4d36-9c4a-b6eb3f5fd82a)
When I run that install scripit,  still the same errors that flatbuffers is empyt.

**Comment by robell** [comment]
This is a clean checkout flow:
`git clone --branch v0.1.0 https://github.com/pytorch/executorch.git
cd executorch
git submodule deinit backends/arm/third-party/ethos-u-core-driver/
git submodule deinit backends/arm/third-party/serialization_lib
git rm backends/arm/third-party/ethos-u-core-driver/
git rm backends/arm/third-party/serialization_lib/
rm -rf .git/modules/backends/arm/third-party/ethos-u-core-driver/
rm -rf .git/modules/backends/arm/third-party/serialization_lib/
git submodule update --init
git submodule update
git submodule sync`

If this sequence does not populate third-party/flatbuffers/ then there is some other issue.

I suspect with a clean checkout even `git config --global http.sslVerify "false"` would work.

**Comment by luxunxiansheng** [comment]
Thanks guys for your patience. Now it works even got some errors during installing. 
![image](https://github.com/pytorch/executorch/assets/26159816/dc5ab204-05c5-4422-a0f3-0ae3728e0263)
Anyway, Thank you so much!
