### ISSUE TITLE
Add OpenAI Whisper model samples for mobile

### ISSUE THREAD

**Issue by madroidmaq** [pytorch/executorch#1005]
- [OpenAI Whisper](https://github.com/openai/whisper)
- [ONNX OpenAI Whisper Sample](https://github.com/microsoft/onnxruntime-inference-examples/tree/main/mobile/examples/whisper/local/android      )

**Comment by Gasoonjia** [comment]
Close the issue since we do not have a specific roadmap for supportive. Will reopen it once we have clear plan.

**Comment by ZodiacFRA** [comment]
hello @madroidmaq have you tried to export the model ?
