### ISSUE TITLE
Ninja: build stopped: subcommand failed.

### ISSUE THREAD

**Issue by yicheng-2019** [pytorch/executorch#1020]
Can not run the command  "python3 -m examples.apple.mps.scripts.mps_example --model_name="mv3" for "exporting and bundling the MobileNet v3 model."  in ExecuTorch iOS Demo App tutorial.

Env: MacOS termial

I have installed all the additional dependencies as per the previous steps, but I'm getting an error at this stage. Is there something I might have missed?

error:
**(executorch) qiuyicheng@qiuyc-MacBook-Pro executorch % python3 -m examples.apple.mps.scripts.mps_example --model_name="mv3" 
Traceback (most recent call last):
  File "/Users/qiuyicheng/miniconda3/envs/executorch/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 2100, in _run_ninja_build
    subprocess.run(
  File "/Users/qiuyicheng/miniconda3/envs/executorch/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/qiuyicheng/miniconda3/envs/executorch/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/qiuyicheng/miniconda3/envs/executorch/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/qiuyicheng/QIU/Code/pytorch/executorch/examples/apple/mps/scripts/mps_example.py", line 15, in <module>
    from executorch.backends.apple.mps.mps_preprocess import MPSBackend
  File "/Users/qiuyicheng/miniconda3/envs/executorch/lib/python3.10/site-packages/executorch/backends/apple/mps/mps_preprocess.py", line 10, in <module>
    from executorch.backends.apple.mps.utils.graph_bindings import graph_bindings
  File "/Users/qiuyicheng/miniconda3/envs/executorch/lib/python3.10/site-packages/executorch/backends/apple/mps/utils/graph_bindings.py", line 37, in <module>
    graph_bindings = torch.utils.cpp_extension.load(
  File "/Users/qiuyicheng/miniconda3/envs/executorch/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1308, in load
    return _jit_compile(
  File "/Users/qiuyicheng/miniconda3/envs/executorch/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1710, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/Users/qiuyicheng/miniconda3/envs/executorch/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1823, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "/Users/qiuyicheng/miniconda3/envs/executorch/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 2116, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'MPSGraphBindings': [1/2] c++ -MMD -MF MPSGraphInterface.o.d -DTORCH_EXTENSION_NAME=MPSGraphBindings -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_clang\" -DPYBIND11_STDLIB=\"_libcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1002\" -I/Users/qiuyicheng/QIU/Code/pytorch/executorch/backends/apple/mps -isystem /Users/qiuyicheng/miniconda3/envs/executorch/lib/python3.10/site-packages/torch/include -isystem /Users/qiuyicheng/miniconda3/envs/executorch/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /Users/qiuyicheng/miniconda3/envs/executorch/lib/python3.10/site-packages/torch/include/TH -isystem /Users/qiuyicheng/miniconda3/envs/executorch/lib/python3.10/site-packages/torch/include/THC -isystem /Users/qiuyicheng/miniconda3/envs/executorch/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++17 -c /Users/qiuyicheng/QIU/Code/pytorch/executorch/backends/apple/mps/utils/MPSGraphInterface.mm -o MPSGraphInterface.o 
FAILED: MPSGraphInterface.o 
c++ -MMD -MF MPSGraphInterface.o.d -DTORCH_EXTENSION_NAME=MPSGraphBindings -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_clang\" -DPYBIND11_STDLIB=\"_libcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1002\" -I/Users/qiuyicheng/QIU/Code/pytorch/executorch/backends/apple/mps -isystem /Users/qiuyicheng/miniconda3/envs/executorch/lib/python3.10/site-packages/torch/include -isystem /Users/qiuyicheng/miniconda3/envs/executorch/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /Users/qiuyicheng/miniconda3/envs/executorch/lib/python3.10/site-packages/torch/include/TH -isystem /Users/qiuyicheng/miniconda3/envs/executorch/lib/python3.10/site-packages/torch/include/THC -isystem /Users/qiuyicheng/miniconda3/envs/executorch/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++17 -c /Users/qiuyicheng/QIU/Code/pytorch/executorch/backends/apple/mps/utils/MPSGraphInterface.mm -o MPSGraphInterface.o 
/Users/qiuyicheng/QIU/Code/pytorch/executorch/backends/apple/mps/utils/MPSGraphInterface.mm:118:3: error: unknown type name 'MPSGraphExecutableSerializationDescriptor'; did you mean 'MPSGraphExecutableExecutionDescriptor'?
  MPSGraphExecutableSerializationDescriptor *serializationDescriptor = [MPSGraphExecutableSerializationDescriptor new];
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  MPSGraphExecutableExecutionDescriptor
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/MetalPerformanceShadersGraph.framework/Headers/MPSGraphExecutable.h:33:12: note: 'MPSGraphExecutableExecutionDescriptor' declared here
@interface MPSGraphExecutableExecutionDescriptor : NSObject<NSCopying>
           ^
/Users/qiuyicheng/QIU/Code/pytorch/executorch/backends/apple/mps/utils/MPSGraphInterface.mm:118:73: error: use of undeclared identifier 'MPSGraphExecutableSerializationDescriptor'
  MPSGraphExecutableSerializationDescriptor *serializationDescriptor = [MPSGraphExecutableSerializationDescriptor new];
                                                                        ^
/Users/qiuyicheng/QIU/Code/pytorch/executorch/backends/apple/mps/utils/MPSGraphInterface.mm:119:27: error: property 'deploymentPlatform' not found on object of type 'MPSGraphExecutableExecutionDescriptor *'
  serializationDescriptor.deploymentPlatform = MPSGraphDeploymentPlatformMacOS;
                          ^
/Users/qiuyicheng/QIU/Code/pytorch/executorch/backends/apple/mps/utils/MPSGraphInterface.mm:119:48: error: use of undeclared identifier 'MPSGraphDeploymentPlatformMacOS'
  serializationDescriptor.deploymentPlatform = MPSGraphDeploymentPlatformMacOS;
                                               ^
/Users/qiuyicheng/QIU/Code/pytorch/executorch/backends/apple/mps/utils/MPSGraphInterface.mm:120:27: error: property 'minimumDeploymentTarget' not found on object of type 'MPSGraphExecutableExecutionDescriptor *'
  serializationDescriptor.minimumDeploymentTarget = @"14.0.0";
                          ^
/Users/qiuyicheng/QIU/Code/pytorch/executorch/backends/apple/mps/utils/MPSGraphInterface.mm:121:9: warning: instance method '-serializeToMPSGraphPackageAtURL:descriptor:' not found (return type defaults to 'id') [-Wobjc-method-access]
  [exec serializeToMPSGraphPackageAtURL:bundleURL descriptor:serializationDescriptor];
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/MetalPerformanceShadersGraph.framework/Headers/MPSGraphExecutable.h:80:12: note: receiver is instance of class declared here
@interface MPSGraphExecutable : NSObject
           ^
1 warning and 5 errors generated.
ninja: build stopped: subcommand failed.**

**Comment by DenisVieriu97** [comment]
Hi @yicheng-2019 - thank you for the issue.

`: error: unknown type name 'MPSGraphExecutableSerializationDescriptor'; did you mean 'MPSGraphExecutableExecutionDescriptor'?`
Please note that you will need [macOS Sonoma ](https://www.apple.com/macos/sonoma/) and [Xcode 15](https://developer.apple.com/xcode/) in order to use the MPS delegate.

**Comment by yicheng-2019** [comment]
Thanks! After upgrading to Xcode 15, the issue has been resolved, but another error occurred when in Run Tests.

error：
(execuTorch) qiuyicheng@qiuyc-MacBook-Pro executorch % xcrun simctl create executorch "iPhone 15"
xcodebuild clean test \
     -project examples/demo-apps/apple_ios/ExecuTorchDemo/ExecuTorchDemo.xcodeproj \
     -scheme App \
     -destination name=executorch
xcrun simctl delete executorch
No runtime specified, using 'iOS 17.0 (17.0.1 - 21A342) - com.apple.CoreSimulator.SimRuntime.iOS-17-0'
6FAF2DDF-39EA-4D31-A1DF-FC284D3BEFE2
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild clean test -project examples/demo-apps/apple_ios/ExecuTorchDemo/ExecuTorchDemo.xcodeproj -scheme App -destination name=executorch

User defaults from command line:
    IDEPackageSupportUseBuiltinSCM = YES

--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Any iOS Device }
{ platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Any iOS Simulator Device }
{ platform:iOS Simulator, id:86AA1D58-FFF4-463C-A130-26C11510C72C, OS:17.0.1, name:executorch }
{ platform:iOS Simulator, id:A453BB87-8966-4B48-88C3-3DD6FB69A268, OS:17.0.1, name:executorch }
{ platform:iOS Simulator, id:1E5093EA-9B61-4492-BBF9-19BD25208A5E, OS:17.0.1, name:executorch }
{ platform:iOS Simulator, id:6658C35D-E57E-4D2F-BB5A-A5C1FDB6B661, OS:17.0.1, name:executorch }
{ platform:iOS Simulator, id:6823CDC5-7F07-462D-9461-4248C6BD7F22, OS:17.0.1, name:executorch }
{ platform:iOS Simulator, id:6FAF2DDF-39EA-4D31-A1DF-FC284D3BEFE2, OS:17.0.1, name:executorch }
{ platform:iOS Simulator, id:8456F1B2-C102-460F-A9D2-2D021A79FEE2, OS:17.0.1, name:executorch }
{ platform:iOS Simulator, id:99F4B036-EA70-4604-A282-32F26FE2AB3C, OS:17.0.1, name:executorch }
{ platform:iOS Simulator, id:E78861F9-52B6-441C-86E1-993A50B3F2B3, OS:17.0.1, name:executorch }
{ platform:iOS Simulator, id:B67B55B8-1D9C-4A78-A3B3-7BB82BD96335, OS:17.0.1, name:iPad (10th generation) }
{ platform:iOS Simulator, id:1879C5AF-9835-4005-B5AC-DBCF02420ABB, OS:17.0.1, name:iPad Air (5th generation) }
{ platform:iOS Simulator, id:850D0962-A91D-48C2-BB73-6F556A7F5893, OS:17.0.1, name:iPad Pro (11-inch) (4th generation) }
{ platform:iOS Simulator, id:EC9AC6DB-1618-477E-A788-0A39692A4B74, OS:17.0.1, name:iPad Pro (12.9-inch) (6th generation) }
{ platform:iOS Simulator, id:B6F6F6D5-1482-4EB7-8911-D1F58DA848F8, OS:17.0.1, name:iPad mini (6th generation) }
{ platform:iOS Simulator, id:D80C4A34-BAD2-451D-91EA-856AA76CB2C2, OS:17.0.1, name:iPhone 15 }
{ platform:iOS Simulator, id:89257188-8257-4FF4-8B29-95A72047EB7A, OS:17.0.1, name:iPhone 15 Plus }
{ platform:iOS Simulator, id:BBD8FCC7-233C-4B69-8307-B1739F9A3749, OS:17.0.1, name:iPhone 15 Pro }
{ platform:iOS Simulator, id:5582B38C-78E2-4DE8-B6CC-466A6DFB56F1, OS:17.0.1, name:iPhone 15 Pro Max }
{ platform:iOS Simulator, id:327C5CDA-205E-4194-98AF-91708B8F5A5E, OS:17.0.1, name:iPhone SE (3rd generation) }

** CLEAN SUCCEEDED **

--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Any iOS Device }
{ platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Any iOS Simulator Device }
{ platform:iOS Simulator, id:86AA1D58-FFF4-463C-A130-26C11510C72C, OS:17.0.1, name:executorch }
{ platform:iOS Simulator, id:A453BB87-8966-4B48-88C3-3DD6FB69A268, OS:17.0.1, name:executorch }
{ platform:iOS Simulator, id:1E5093EA-9B61-4492-BBF9-19BD25208A5E, OS:17.0.1, name:executorch }
{ platform:iOS Simulator, id:6658C35D-E57E-4D2F-BB5A-A5C1FDB6B661, OS:17.0.1, name:executorch }
{ platform:iOS Simulator, id:6823CDC5-7F07-462D-9461-4248C6BD7F22, OS:17.0.1, name:executorch }
{ platform:iOS Simulator, id:6FAF2DDF-39EA-4D31-A1DF-FC284D3BEFE2, OS:17.0.1, name:executorch }
{ platform:iOS Simulator, id:8456F1B2-C102-460F-A9D2-2D021A79FEE2, OS:17.0.1, name:executorch }
{ platform:iOS Simulator, id:99F4B036-EA70-4604-A282-32F26FE2AB3C, OS:17.0.1, name:executorch }
{ platform:iOS Simulator, id:E78861F9-52B6-441C-86E1-993A50B3F2B3, OS:17.0.1, name:executorch }
{ platform:iOS Simulator, id:B67B55B8-1D9C-4A78-A3B3-7BB82BD96335, OS:17.0.1, name:iPad (10th generation) }
{ platform:iOS Simulator, id:1879C5AF-9835-4005-B5AC-DBCF02420ABB, OS:17.0.1, name:iPad Air (5th generation) }
{ platform:iOS Simulator, id:850D0962-A91D-48C2-BB73-6F556A7F5893, OS:17.0.1, name:iPad Pro (11-inch) (4th generation) }
{ platform:iOS Simulator, id:EC9AC6DB-1618-477E-A788-0A39692A4B74, OS:17.0.1, name:iPad Pro (12.9-inch) (6th generation) }
{ platform:iOS Simulator, id:B6F6F6D5-1482-4EB7-8911-D1F58DA848F8, OS:17.0.1, name:iPad mini (6th generation) }
{ platform:iOS Simulator, id:D80C4A34-BAD2-451D-91EA-856AA76CB2C2, OS:17.0.1, name:iPhone 15 }
{ platform:iOS Simulator, id:89257188-8257-4FF4-8B29-95A72047EB7A, OS:17.0.1, name:iPhone 15 Plus }
{ platform:iOS Simulator, id:BBD8FCC7-233C-4B69-8307-B1739F9A3749, OS:17.0.1, name:iPhone 15 Pro }
{ platform:iOS Simulator, id:5582B38C-78E2-4DE8-B6CC-466A6DFB56F1, OS:17.0.1, name:iPhone 15 Pro Max }
{ platform:iOS Simulator, id:327C5CDA-205E-4194-98AF-91708B8F5A5E, OS:17.0.1, name:iPhone SE (3rd generation) }
2023-10-20 13:47:12.186 xcodebuild[23393:175291] Writing error result bundle to /var/folders/ny/03s2zhs16cz2b3h7tnf1nbv00000gn/T/ResultBundle_2023-20-10_13-47-0012.xcresult
Prepare packages

xcodebuild: error: Failed to build project ExecuTorchDemo with scheme App.: Cannot test target “MobileNetClassifierTest” on “Any iOS Device”: Tests must be run on a concrete device

**Comment by cccclai** [comment]
Looks like it's for the demo app. @shoumikhin any chance you know?

**Comment by shoumikhin** [comment]
Please check the [MPS tutorial](https://pytorch.org/executorch/stable/build-run-mps.html), the MPS backend requires Xcode 15+ and iOS 17+.

**Comment by yicheng-2019** [comment]
In Step 2. Run the model using the mps_executor_runner. 
The following error occurred.

error：
(execuTorch) qiuyicheng@qiuyc-MacBook-Pro executorch % ./cmake-out/examples/apple/mps/mps_executor_runner --model_path mv3.pte --bundled_program
I 00:00:00.013429 executorch:mps_executor_runner.mm:286] Model file mv3.pte is loaded.
I 00:00:00.013454 executorch:mps_executor_runner.mm:292] Program methods: 1
I 00:00:00.013457 executorch:mps_executor_runner.mm:294] Running method forward
I 00:00:00.013466 executorch:mps_executor_runner.mm:349] Setting up non-const buffer 1, size 606112.
I 00:00:00.013761 executorch:mps_executor_runner.mm:376] Setting up memory manager
I 00:00:00.013766 executorch:mps_executor_runner.mm:392] Loading method name from plan
I 00:00:00.101723 executorch:MPSCompiler.mm:101] Num inputs: 1
I 00:00:00.101744 executorch:MPSCompiler.mm:102] Num outputs: 1
I 00:00:00.101761 executorch:mps_executor_runner.mm:399] Method loaded.
I 00:00:00.101764 executorch:mps_executor_runner.mm:404] Loading bundled program...

I 00:00:00.101943 executorch:mps_executor_runner.mm:421] Inputs prepared.
F 00:00:00.114246 executorch:MPSDevice.mm:40] In function MPSDevice(), assert failed: _mtl_device != nil
zsh: abort      ./cmake-out/examples/apple/mps/mps_executor_runner --model_path mv3.pte

**Comment by kimishpatel** [comment]
@DenisVieriu97 can you take a look? It looks like device init failed. Is your macbook pro intel one or M1/M2? Not sure if thats relevant but asking for the context

**Comment by DenisVieriu97** [comment]
> 00:00:00.114246 executorch:MPSDevice.mm:40] In function MPSDevice(), assert failed: _mtl_device != nil

@yicheng-2019 could you please share your python environment information? You can get it using following command: 
```
python -m torch.utils.collect_env
```

**Comment by guangy10** [comment]
Correct the labels for this issue

**Comment by yicheng-2019** [comment]
Sorry for my late reply, here is my MAC environment.


**PyTorch version: 2.2.0.dev20231010
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 14.0 (x86_64)
GCC version: Could not collect
Clang version: 15.0.0 (clang-1500.0.40.1)
CMake version: version 3.27.7
Libc version: N/A

Python version: 3.10.0 (default, Mar  3 2022, 03:57:21) [Clang 12.0.0 ] (64-bit runtime)
Python platform: macOS-10.16-x86_64-i386-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz

Versions of relevant libraries:
[pip3] executorch==0.1.0
[pip3] executorchcoreml==0.0.1
[pip3] numpy==1.21.3
[pip3] torch==2.2.0.dev20231010
[pip3] torchaudio==2.2.0.dev20231010
[pip3] torchsr==1.0.4
[pip3] torchvision==0.17.0.dev20231010
[conda] executorch                0.1.0                    pypi_0    pypi
[conda] executorchcoreml          0.0.1                    pypi_0    pypi
[conda] numpy                     1.21.3                   pypi_0    pypi
[conda] torch                     2.2.0.dev20231010          pypi_0    pypi
[conda] torchaudio                2.2.0.dev20231010          pypi_0    pypi
[conda] torchsr                   1.0.4                    pypi_0    pypi
[conda] torchvision               0.17.0.dev20231010          pypi_0    pypi**

**Comment by DenisVieriu97** [comment]
Hi @yicheng-2019 - thank you for sharing the info. 

> OS: macOS 14.0 (x86_64)

Currently MPS backend for ExecuTorch doesn't support x86 macs - only Apple Silicon macs are supported (M1/M2)

**Comment by yicheng-2019** [comment]
I understand, thanks for your explanation.

**Comment by cpshelton** [comment]
Is it possible to run the ExecuTorch iOS demo without the MPS backend? My Mac is also x86 so it's not possible for me to complete the MPS step.

**Comment by DenisVieriu97** [comment]
@cpshelton latest ExecuTorch main branch supports running the ExecuTorch demo from a x86 Mac (you can also run it locally on x86 macs through the MPS delegate, see below comment). 

@yicheng-2019 

> OS: macOS 14.0 (x86_64)
> Currently MPS backend for ExecuTorch doesn't support x86 macs - only Apple Silicon macs are supported (M1/M2)

Latest main branch adds support for running the models on x86 macs with the MPS delegate (https://github.com/pytorch/executorch/pull/1655). If you have a Mac with AMD GPU it will work out of the box, if using a Intel GPU you can comment out this line before building it (https://github.com/pytorch/executorch/pull/1655).

Let me know if you see any issues. Thanks.

**Comment by mergennachin** [comment]
Closing this issue as it looks resolved.

**Comment by sandeep-chaturvedi** [comment]
Today I had an error like this, in Android Studio, and I found no solution over internet, While looking for solution I saw a inconsistency in the project

Go **android/app/.cxx** folder, 

```
Note - for checking .cxx as it's a hidden folder.
For window users -  In file explorer, make show hidden files and deleted that folder (**.cxx**), 
For mac users - (cmd + shift + .) Now you can see the hidden files/folders and deleted that folder (**.cxx**), 
```

Then clean the project and that was the solution LOL!
