### ISSUE TITLE
GPU backends

### ISSUE THREAD

**Issue by pfk-beta** [pytorch/executorch#1045]
Hello,

It would be great to have way to utilize GPUs with executorch. I can see unfinished vulkan backend. Are there plans to enable vulkan, opengl or opencl?

**Comment by kimishpatel** [comment]
Yes. There are plan for gpu delegate coming soon. ATM it is vulkan delegate

**Comment by pfk-beta** [comment]
Does vulkan delegate finished? Is it usable?

**Comment by kimishpatel** [comment]
Not at the moment. It will take a few months of work. We will update with timeline.

**Comment by SS-JIA** [comment]
Closing this issue for now. We are now starting work on a native GPU delegate for ExecuTorch built on top of the Vulkan API. This delegate is expected to be ready by ExecuTorch's alpha release.
