### ISSUE TITLE
Exporting mobilenetv2 to pte

### ISSUE THREAD

**Issue by lopusz** [pytorch/executorch#1062]
Hi All,

first of all the `executorch` looks really interesting. Thank you for releasing!

To give it a try, I wanted to export simple MobileNetV2 architecture to `pte` and run it using `executorch` engine.

Following the exporting tutorial, I used the script from here https://pytorch.org/executorch/stable/tutorials/export-to-executorch-tutorial.html#saving-to-a-file

However, I get an error:

`torch._export.verifier.SpecViolationError: Operator torch._ops.aten._native_batch_norm_legit_functional.default is not Aten Canonical.`

Does it mean that for `BatchNorm` I need some extra handling? 

Exporting simple example without `BatchNorm` works for me.

The minimal reproducible example:

```python
import torch
import torchvision

import executorch.exir as exir

from torch._export import capture_pre_autograd_graph
from torch.export import export, ExportedProgram

m = torchvision.models.MobileNetV2()

example_args = (torch.randn(1, 3, 224, 224),)
pre_autograd_aten_dialect = capture_pre_autograd_graph(m, example_args)

# Optionally do quantization:
# pre_autograd_aten_dialect = convert_pt2e(prepare_pt2e(pre_autograd_aten_dialect, CustomBackendQuantizer))

aten_dialect: ExportedProgram = export(pre_autograd_aten_dialect, example_args)
edge_program: exir.EdgeProgramManager = exir.to_edge(aten_dialect)

# Optionally do delegation:
# edge_program = edge_program.to_backend(CustomBackendPartitioner)

executorch_program: exir.ExecutorchProgramManager = edge_program.to_executorch(
    exir.ExecutorchBackendConfig(
        passes=[],  # User-defined passes
    )
)

with open("mobilenet_v2.pte", "wb") as file:
    file.write(executorch_program.buffer)
```

The environment:

I installed `executorch` using  `git clone --branch v0.1.0 https://github.com/pytorch/executorch.git` (as in the docs)
Versions:
```
torch==2.2.0.dev20231010+cpu
torchvision==0.17.0.dev20231010+cpu
```
Python 3.10.

If you need any more details, please let me know.

Thank you for suggestions.

Best regards,
Michał

**Comment by larryliu0820** [comment]
@lopusz We are having a discussion on whether this operator should be added into [Core ATen opset](https://pytorch.org/executorch/stable/ir-ops-set-definition.html#definition-of-the-core-aten-operator-set). For now you can bypass this by setting `_check_ir_validity=False` like what @cccclai suggested.

**Comment by larryliu0820** [comment]
@lopusz can you please try `m.eval()`? It should replace the `_native_batch_norm_legit_functional` operator with `_native_batch_norm_legit_no_training` which is a core ATen operator

**Comment by lopusz** [comment]
Hi @cccclai and @larryliu0820. 

Thank you for superfast answer.

Indeed `m.eval()` makes a lot of sense and does the trick.

Problem solved, I am closing the issue.

**Comment by deahhh** [comment]
@lopusz 
Hello, you the hot shot!
Could you give me some insight on using executorch?
I run the model mobilenetv2 built following this page, and run it with executor_runner of example in [Setting Up ExecuTorch](https://pytorch.org/executorch/stable/getting-started-setup.html), then got 17s running time. It seems like that the executor make use single cpu core of the 12 on my computer.
Thanks!
