### ISSUE TITLE
Autogenerator of valid shapes for a given op

### ISSUE THREAD

**Issue by lezcano** [pytorch/executorch#1063]
Discussed with @manuelcandales during the PyTorch conf. I was not able to ping Manuel as he's not in the PyTorch slack or the Symbolic Shapes workplace group, so sharing it here.

Here's Ed's prototype that shows how to generate valid shapes for a given operator automatically:
https://gist.github.com/ezyang/192c1b5eb57ff95a46d3b50aa46e3193

**Comment by manuelcandales** [comment]
Hi, what's up! Thank you for following up on this! I pinged Ed after the conference. He shared this gist with me, and I asked him some follow up questions. Notice though, how that gist is fixing everything, except the kernel sizes (s0 & s1). It is only solving for those. So, I asked Ed if this method could handle all the parameters for convolution. He tried that last week, and he said it chokes if you try to simultaneously solve for all of the parameters.
I think this approach is worth exploring. Right now, it isn't clear to me whether this can solve the general problem for all operators and replace the handcrafted algorithmic specifications I have worked on. However, even if it could handle only simpler ops, and complex ops only partially, that is still worth exploring.
