### ISSUE TITLE
Using Android's NnApi interface? 

### ISSUE THREAD

**Issue by FabianSchuetze** [pytorch/executorch#1097]
Thanks for this wonderful repo. 

Is there a way to leverage Android's NnApi interface with executorch?

**Comment by cccclai** [comment]
This is what we heard: https://www.xda-developers.com/google-drops-plans-nnapi-drivers-updatable/

**Comment by FabianSchuetze** [comment]
Thanks so much for the reply - that's very interesting indeed.

 Just to understand: How can I leverage accelerators from vendors other than the ones mentioned in https://github.com/pytorch/executorch/tree/main/backends ? For example, HiSilicon, Mediatek or Samsumg come to mind. They often have drivers integrating with NnApi. Do they need to release new drivers?

**Comment by larryliu0820** [comment]
I think we won't be able to get to NnApi backend in the near future. Feel free to send out a PR to support it and we can take a look

**Comment by cccclai** [comment]
> Thanks so much for the reply - that's very interesting indeed.
> 
> Just to understand: How can I leverage accelerators from vendors other than the ones mentioned in https://github.com/pytorch/executorch/tree/main/backends ? For example, HiSilicon, Mediatek or Samsumg come to mind. They often have drivers integrating with NnApi. Do they need to release new drivers?

It depends on how we want to leverage these backends. NNAPI is a wrapper and it's not necessary to use it if we want to use their accelerators. Likely it can be another delegates similar to other backends listed in `https://github.com/pytorch/executorch/tree/main/backends`
