### ISSUE TITLE
[TOSA] Enable running arm_tosa_e2e tests on public CI

### ISSUE THREAD

**Issue by Jerry-Ge** [pytorch/executorch#1100]
For better future maintenance and development. We need to add public CI jobs for the following test suites.  

`executorch/examples/arm/arm_tosa_e2e.py`

Dependencies: 
- [ ] TOSA Reference Model: https://review.mlplatform.org/plugins/gitiles/tosa/reference_model/

**Comment by Jerry-Ge** [comment]
Suggested label `partner:arm`

**Comment by digantdesai** [comment]
@Jerry-Ge - this is something we are looking at right now. @guangy10 and I discussed this and hope to get something which can run the tosa_fb output on the CI job.
