### ISSUE TITLE
How to virtualize the qte model?

### ISSUE THREAD

**Issue by liang1232018** [pytorch/executorch#1101]
Hi,

I am now working on executorch. I want to see the model architecture of qte, which is easy for us to debug.
However, I cannot find a virtualizing tool.  Netron does not support qte format now.
Could executorch support to virtualize the qte format model? 

Besides, I wonder  whether the export function  will translate the ops in the Pytorch model to specifics ops  in qte format? 

Thanks!!!
```[tasklist]
### Tasks
```

**Comment by JacobSzwejbka** [comment]
Do you mean pte? I think the visualizer will come through the ExecuTorch sdk, though I'm not sure we allow visualization of .pte vs the graph module before serialization. cc @tarun292

**Comment by liang1232018** [comment]
Thanks for your reply.

Yes, I  mean pte. I am sorry for wrong spelling.
I am looking forward to the the visualizer tool in the ExecuTorch sdk. It is much more convenient.
