### ISSUE TITLE
Build runtime - required headers

### ISSUE THREAD

**Issue by pfk-beta** [pytorch/executorch#1102]
What c++ headers should I have in my system before building runtime? I'm on ubuntu, so it would be great to have list of devel packages with that headers

--edit--
For ubuntu 22.04 which clang version you suggest?
--edit2--
Should I install coresponsing llvm?

--edit3--
I have installed these packages:
```shell
clang-15 
clang-tools-15 
libclang-15-dev
libclang-cpp15
libclang-cpp15-dev
libclang-common-15-dev 
libc++-15-dev
llvm-15 
llvm-15-dev 
lld-15 
liblldb-15-dev 
liblld-15
```

**Comment by larryliu0820** [comment]
What do you mean by headers? For toolchains we currently support gcc as well as clang on various linux distros. @lucylq if you can give more details on this

**Comment by pfk-beta** [comment]
sorry, my fault. I think I had broken clang/llvm environment. During building runtime, I get error about missing iostream, cstring and memory headers, which are part of stdlib, I gues. After installing previously mentioned packages I have solved problem.

**Comment by lucylq** [comment]
Glad you solved it! Though for reference:

> For ubuntu 22.04 which clang version you suggest?
The default clang should work well. We recommend > clang8

> Should I install coresponsing llvm?
Installing clang should be good, don't need to install llvm.
