### ISSUE TITLE
[TOSA] Enable Running arm_e2e_tests with Python Unit Test 

### ISSUE THREAD

**Issue by Jerry-Ge** [pytorch/executorch#1105]
In order to have a cleaner testing setup and generating XML test results, propose to refactor the current arm_e2e_tests to use the Python Unit Test Infrastructure. 

https://github.com/pytorch/executorch/blob/main/examples/arm/arm_tosa_e2e.py

Suggested label `partner:arm`

**Comment by digantdesai** [comment]
#1111 added a new CI flow to run setup.sh and run.sh from examples. Once that is stable and ready to use, we can just extend run.sh do do more things like running this script.

**Comment by Jerry-Ge** [comment]
cc @tatwaichong

**Comment by Jerry-Ge** [comment]
The refactoring work has got started since this patch: https://github.com/pytorch/executorch/commit/e4a78c233b64ae375f9ffaf1b6205b2f6653ea25

Close this issue ticket for now.
