### ISSUE TITLE
[CI]LintRunner Version Mismatch

### ISSUE THREAD

**Issue by Jerry-Ge** [pytorch/executorch#1109]
Inside public CI, the version of `lintrunner` is `0.11.0`, while the `lintrunner-adapters` is `0.9.0`. 

However, the latest version of `lintrunner-adapters`  is also `0.11.0`. Is there any specific reason of using a slightly older version of `lintrunner-adapters`? Or it's just not been updated yet in the docker image? 

The latest `lintrunner` version: https://pypi.org/project/lintrunner/#history
The latest `lintrunner-adapters` version: https://pypi.org/project/lintrunner-adapters/#history

```
Requirement already satisfied: lintrunner==0.11.0 in /opt/conda/envs/py_3.10/lib/python3.10/site-packages (from -r requirements-lintrunner.txt (line 2)) (0.11.0)
Requirement already satisfied: lintrunner-adapters==0.9.0 in /opt/conda/envs/py_3.10/lib/python3.10/site-packages (from -r requirements-lintrunner.txt (line 3)) (0.9.0)
```

**Comment by Jerry-Ge** [comment]
> Hi @Jerry-Ge
> 
> When I was enabling linter the latest stable version for lintrunners-adapters was 0.9.0. In fact, 0.10.0 was released right on PyTorch conference day looks like lol.
> 
> Anyway, thanks for bringing it up. I will test the latest version of these libraries and update our docker image and documentation accordingly.

got it! tks!

**Comment by mergennachin** [comment]
Will close the issue once I commit the fix
