### ISSUE TITLE
Issue with getting started example

### ISSUE THREAD

**Issue by arman-kazemi** [pytorch/executorch#1142]
Hi,

I followed the getting started document and tried to build the executor-runner binary but get the following error:
`Action failed: root//examples/portable/executor_runner:executor_runner (cxx_link_executable)
Local command returned non-zero exit code 1
Reproduce locally: clang++ @buck-out/v2/gen/root/524f8da68ea2a374/examples/portable/executor_runner/__executor_runner__/executor_runner.linker.argsfile
stdout:
stderr:
clang: error: invalid linker name in argument '-fuse-ld=lld'
Build ID: 3f6d5a07-3e35-4a51-9706-d5c1499375ba
Network: Up: 0 B  Down: 0 B
Jobs completed: 3. Time elapsed: 0.0s.
Cache hits: 0%. Commands: 1 (cached: 0, remote: 0, local: 1)
BUILD FAILED
Failed to build 'root//examples/portable/executor_runner:executor_runner (prelude//platforms:default#524f8da68ea2a374)'`

I'm using Ubuntu 22.04 and below is a list of my installed packages in the conda environment. Can you help me with this?

# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
attrs                     23.1.0                   pypi_0    pypi
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.21.0               hd590300_0    conda-forge
ca-certificates           2023.7.22            hbcca054_0    conda-forge
certifi                   2023.7.22                pypi_0    pypi
charset-normalizer        3.3.2                    pypi_0    pypi
cmake                     3.27.6               hcfe8598_0    conda-forge
exceptiongroup            1.1.3                    pypi_0    pypi
execnet                   2.0.2                    pypi_0    pypi
executorch                0.1.0                    pypi_0    pypi
expecttest                0.1.6                    pypi_0    pypi
filelock                  3.13.1                   pypi_0    pypi
flatbuffers               23.5.26                  pypi_0    pypi
fsspec                    2023.10.0                pypi_0    pypi
huggingface-hub           0.17.3                   pypi_0    pypi
hypothesis                6.88.1                   pypi_0    pypi
icu                       73.2                 h59595ed_0    conda-forge
idna                      3.4                      pypi_0    pypi
iniconfig                 2.0.0                    pypi_0    pypi
jinja2                    3.1.2                    pypi_0    pypi
keyutils                  1.6.1                h166bdaf_0    conda-forge
krb5                      1.21.2               h659d440_0    conda-forge
ld_impl_linux-64          2.40                 h41732ed_0    conda-forge
libcurl                   8.4.0                hca28451_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libexpat                  2.5.0                hcb278e6_1    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 13.2.0               h807b86a_2    conda-forge
libgomp                   13.2.0               h807b86a_2    conda-forge
libiconv                  1.17                 h166bdaf_0    conda-forge
libllvm17                 17.0.4               h5cf9203_0    conda-forge
libnghttp2                1.55.1               h47da74e_0    conda-forge
libnsl                    2.0.1                hd590300_0    conda-forge
libsqlite                 3.44.0               h2797004_0    conda-forge
libssh2                   1.11.0               h0841786_0    conda-forge
libstdcxx-ng              13.2.0               h7e041cc_2    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libuv                     1.46.0               hd590300_0    conda-forge
libxml2                   2.11.5               h232c23b_1    conda-forge
libzlib                   1.2.13               hd590300_5    conda-forge
lld                       17.0.4               hcfcaf08_0    conda-forge
markupsafe                2.1.2                    pypi_0    pypi
mpmath                    1.2.1                    pypi_0    pypi
ncurses                   6.4                  h59595ed_2    conda-forge
networkx                  3.0rc1                   pypi_0    pypi
numpy                     1.26.1                   pypi_0    pypi
openssl                   3.1.4                hd590300_0    conda-forge
packaging                 23.2                     pypi_0    pypi
pandas                    2.1.2                    pypi_0    pypi
parameterized             0.9.0                    pypi_0    pypi
pillow                    9.3.0                    pypi_0    pypi
pip                       23.3.1             pyhd8ed1ab_0    conda-forge
pluggy                    1.3.0                    pypi_0    pypi
pytest                    7.4.3                    pypi_0    pypi
pytest-xdist              3.3.1                    pypi_0    pypi
python                    3.10.0          h543edf9_3_cpython    conda-forge
python-dateutil           2.8.2                    pypi_0    pypi
pytz                      2023.3.post1             pypi_0    pypi
pyyaml                    6.0.1                    pypi_0    pypi
readline                  8.2                  h8228510_1    conda-forge
regex                     2023.10.3                pypi_0    pypi
requests                  2.31.0                   pypi_0    pypi
rhash                     1.4.4                hd590300_0    conda-forge
ruamel-yaml               0.18.5                   pypi_0    pypi
ruamel-yaml-clib          0.2.8                    pypi_0    pypi
safetensors               0.4.0                    pypi_0    pypi
setuptools                68.2.2             pyhd8ed1ab_0    conda-forge
six                       1.16.0                   pypi_0    pypi
sortedcontainers          2.4.0                    pypi_0    pypi
sqlite                    3.44.0               h2c6b66d_0    conda-forge
sympy                     1.11.1                   pypi_0    pypi
tabulate                  0.9.0                    pypi_0    pypi
timm                      0.6.13                   pypi_0    pypi
tk                        8.6.13               h2797004_0    conda-forge
tokenizers                0.14.1                   pypi_0    pypi
tomli                     2.0.1                    pypi_0    pypi
torch                     2.2.0.dev20231010+cpu          pypi_0    pypi
torchaudio                2.2.0.dev20231010+cpu          pypi_0    pypi
torchsr                   1.0.4                    pypi_0    pypi
torchvision               0.17.0.dev20231010+cpu          pypi_0    pypi
tqdm                      4.66.1                   pypi_0    pypi
transformers              4.34.0                   pypi_0    pypi
typing-extensions         4.8.0                    pypi_0    pypi
tzdata                    2023.3                   pypi_0    pypi
urllib3                   2.0.7                    pypi_0    pypi
wheel                     0.41.3             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
zstd                      1.5.5.1                  pypi_0    pypi`

**Comment by kimishpatel** [comment]
can you try with conda install -c conda-forge lld

**Comment by dbort** [comment]
The old docs had a note about this situation at https://github.com/pytorch/executorch/blob/3a74a1f06ce13a1953b530b9066ee1fc3e75b563/docs/website/docs/tutorials/00_setting_up_executorch.md?plain=1#L139-L142

We should copy those instructions into the corresponding new doc at https://github.com/pytorch/executorch/blob/6f6d129b1e31beb91b17d4227297546eee558b06/docs/source/getting-started-setup.md?plain=1#L274

**Comment by arman-kazemi** [comment]
I already installed lld through conda-forge before opening this issue:  
`ld.lld --version
LLD 17.0.4 (compatible with GNU linkers)`

**Comment by dbort** [comment]
> invalid linker name in argument '-fuse-ld=lld'



> I already installed lld through conda-forge before opening this issue:
> `ld.lld --version LLD 17.0.4 (compatible with GNU linkers)`

Ah sure enough it's in your list of packages. It it on your PATH in the terminal you're using to build?

```
$ ld.lld
ld.lld: error: no input files
```

**Comment by dbort** [comment]
btw I'm going to be offline for the next two weeks, though might be able to check in.

**Comment by kimishpatel** [comment]
Does it work if you follow cmake build?

**Comment by arman-kazemi** [comment]
I realized that this is due to using "sudo" when running the build since the PATH changes. I did this to avoid another error:
`Action failed: root//runtime/platform:platform (symlinked_dir buck-headers)
Internal error: Error cleaning up output path `buck-out/v2/gen/root/524f8da68ea2a374/runtime/platform/__platform__/buck-headers`: remove_path_recursive(/home/ubuntu/executorch/buck-out/v2/gen/root/524f8da68ea2a374/runtime/platform/__platform__/buck-headers) on directory: remove_dir_all(/home/ubuntu/executorch/buck-out/v2/gen/root/524f8da68ea2a374/runtime/platform/__platform__/buck-headers): Permission denied (os error 13)`

**Comment by dbort** [comment]
Thanks for checking; the different PATH explains it. Local file permissions are outside of our control, so I'm going to close this issue, but I hope you figure it out!
You might try running `buck2 clean` and/or `buck2 kill` to see if it's related to the buck2 daemon.

**Comment by arman-kazemi** [comment]
`buck2 clean` did it! thanks a lot!

**Comment by j30393** [comment]
@arman-kazemi 
I met the same problem here, and a little confused about the solution. 
Is it possible to tell how to resolved it? 

buck2 build //examples/portable/executor_runner:executor_runner --show-output                       
Action failed: root//third-party:flatc (cxx_link_executable)   Local command returned non-zero exit code 1
Reproduce locally: `clang++ @buck-out/v2/gen/root/524f8da68ea2a374/third-party/__flatc__/flatc.linker.argsfile`                                            stdout:
                                                                                                                                                    stderr:                                                                                                                                                    clang: error: invalid linker name in argument '-fuse-ld=lld'                                                                                               Build ID: c4300f73-1171-46c1-a174-914feeef91ac                                                                                                             Network: Up: 0 B  Down: 670 KiB                                                                                                                            Jobs completed: 965. Time elapsed: 24.6s.                                                                                                                  Cache hits: 0%. Commands: 332 (cached: 0, remote: 0, local: 332)                                                                                           BUILD FAILED                                                                                                                                               Failed to build 'root//third-party:flatc (prelude//platforms:default#524f8da68ea2a374)'

Environment : 
nvidia/cuda:12.4.0-base-ubuntu22.04 with prebuilt process in dockerfile.

Thank you!
