### ISSUE TITLE
git submodule update --init fails 

### ISSUE THREAD

**Issue by Infrared1029** [pytorch/executorch#1163]
```
git clone --branch v0.1.0 https://github.com/pytorch/executorch.git
cd executorch
git submodule sync
git submodule update --init
```
fails with 
```
fatal: unable to access 'https://git.mlplatform.org/ml/ethos-u/ethos-u-core-driver.git/': SSL: no alternative certificate subject name matches target host name 'git.mlplatform.org'
fatal: clone of 'https://git.mlplatform.org/ml/ethos-u/ethos-u-core-driver.git' into submodule path 'C:/Users/some_path/executorch/backends/arm/third-party/ethos-u-core-driver' failed
Failed to clone 'backends/arm/third-party/ethos-u-core-driver' a second time, aborting
```

**Comment by mergennachin** [comment]
Looks like one of the 3rd party git server's might be down

In the meantime you can comment out the failing dependencies here

`https://github.com/pytorch/executorch/blob/main/.gitmodules`

You wouldn't need ethos-u-core-driver if you're just trying it out -- that dependency is used for running Arm m55/u55 target

**Comment by Infrared1029** [comment]
> Hi @Infrared1029
> 
> Looks like one of the 3rd party git server's might be down
> 
> In the meantime you can comment out the failing dependencies here
> 
> `https://github.com/pytorch/executorch/blob/main/.gitmodules`
> 
> You wouldn't need ethos-u-core-driver if you're just trying it out -- that dependency is used for running Arm m55/u55 target

I think `serialization_lib` is failing too? i think this is causing `pip install .`  to fail as well

**Comment by mergennachin** [comment]
Yeah serialization_lib too, which is hosted on the same server.

We are now working with Arm to fix these issues.

**Comment by eric-k256** [comment]
git.mlplatform.org should be back now. The admins for the site are working on behind the scenes updates to enable it to stay up. (It was getting unexpectedly heavy load, although not for the repos for executorch).

**Comment by mergennachin** [comment]
Thanks @eric-k256 for the prompt fix.

@Infrared1029 -- let us know if you encounter any other errors with the set up.

**Comment by Infrared1029** [comment]
> Thanks @eric-k256 for the prompt fix.
> 
> @Infrared1029 -- let us know if you encounter any other errors with the set up.

everything seems to be working now:) thanks for the fast response everyone

**Comment by daichi1127** [comment]
Hi,
Yesterday, I could set up executorch and run it on Ubuntu 22.04 container.
But now, during the setup procedure especially on `git submodule update --init` I had an error.
Is this server down again?
And how I can make sure the servers of the submodules are ok?
```
Failed to clone 'backends/arm/third-party/ethos-u-core-driver'. Retry scheduled
Cloning into '/root/test/executorch/backends/arm/third-party/serialization_lib'...
fatal: unable to access 'https://git.mlplatform.org/tosa/serialization_lib.git/': The requested URL returned error: 500
fatal: clone of 'https://git.mlplatform.org/tosa/serialization_lib.git' into submodule path '/root/test/executorch/backends/arm/third-party/serialization_lib' failed
Failed to clone 'backends/arm/third-party/serialization_lib'. Retry scheduled
Cloning into '/root/test/executorch/backends/arm/third-party/ethos-u-core-driver'...
fatal: unable to access 'https://git.mlplatform.org/ml/ethos-u/ethos-u-core-driver.git/': The requested URL returned error: 500
fatal: clone of 'https://git.mlplatform.org/ml/ethos-u/ethos-u-core-driver.git' into submodule path '/root/test/executorch/backends/arm/third-party/ethos-u-core-driver' failed
Failed to clone 'backends/arm/third-party/ethos-u-core-driver' a second time, aborting
```

**Comment by EarthMu** [comment]
Hi,
Yesterday, I could set up executorch and run it on Ubuntu 22.04 container.
But now, during the setup procedure especially on `git submodule update --init` I had an error.
Is this server down again?
And how I can make sure the servers of the submodules are ok?
```sh
Failed to clone 'backends/arm/third-party/ethos-u-core-driver'. Retry scheduled
Cloning into '/root/test/executorch/backends/arm/third-party/serialization_lib'...
fatal: unable to access 'https://git.mlplatform.org/tosa/serialization_lib.git/': The requested URL returned error: 500
fatal: clone of 'https://git.mlplatform.org/tosa/serialization_lib.git' into submodule path '/root/test/executorch/backends/arm/third-party/serialization_lib' failed
Failed to clone 'backends/arm/third-party/serialization_lib'. Retry scheduled
Cloning into '/root/test/executorch/backends/arm/third-party/ethos-u-core-driver'...
fatal: unable to access 'https://git.mlplatform.org/ml/ethos-u/ethos-u-core-driver.git/': The requested URL returned error: 500
fatal: clone of 'https://git.mlplatform.org/ml/ethos-u/ethos-u-core-driver.git' into submodule path '/root/test/executorch/backends/arm/third-party/ethos-u-core-driver' failed
Failed to clone 'backends/arm/third-party/ethos-u-core-driver' a second time, aborting
```  
  
Thanks,

**Comment by escorciav** [comment]
I'm facing the same issue now :cry: . I guess it's not relevant if we're not deploying/testing with arm devices.

**Comment by robell** [comment]
hi @escorciav is it a 500 error or "SSL: no alternative certificate subject" you're seeing?

**Comment by mergennachin** [comment]
@escorciav, @EarthMu  Thanks for reporting the issue. 

It seems that external servers that our repo depends on, namely, `git.mlplatform.org`, is unstable and down sometimes. We let the admins know to improve the stability.

For long term solution, we will work on removing backend specific dependencies (e.g., ethos-u-core-driver, tosa/serialization_lib) from root level .gitmodules configuration instead and move them to individual setup script for each backends.

In the meantime, if you encounter similar issues, I'd recommend to comment those dependencies if you're not actually deploying to Arm devices.

**Comment by escorciav** [comment]
> hi @escorciav is it a 500 error or "SSL: no alternative certificate subject" you're seeing?

@robell My error **was** a 500 error, and related to `git.mlplatform.org`.

However, it seems that someone gave a bump to  the server, as it just worked (I believe) :)
```
$ git submodule update --init
Cloning into '/home/SERILOCAL/v.castillo/projects/on-device-llm/executorch/backends/arm/third-party/ethos-u-core-driver'...
Cloning into '/home/SERILOCAL/v.castillo/projects/on-device-llm/executorch/backends/arm/third-party/serialization_lib'...
Submodule path 'backends/arm/third-party/ethos-u-core-driver': checked out '90f9df900acdc0718ecd2dfdc53780664758dec5'
Submodule path 'backends/arm/third-party/serialization_lib': checked out '9601cbda5ff42dc4762e364d90093670931e1261'
Submodule path 'backends/xnnpack/third-party/FP16': checked out '4dfe081cf6bcd15db339cf2680b9281b8451eeb3'
Submodule path 'backends/xnnpack/third-party/FXdiv': checked out 'b408327ac2a15ec3e43352421954f5b1967701d1'
Submodule path 'backends/xnnpack/third-party/XNNPACK': checked out '51a987591a6fc9f0fc0707077f53d763ac132cbf'
Submodule path 'backends/xnnpack/third-party/cpuinfo': checked out '6481e8bef08f606ddd627e4d3be89f64d62e1b8a'
Submodule path 'backends/xnnpack/third-party/pthreadpool': checked out 'a134dd5d4cee80cce15db81a72e7f929d71dd413'
Submodule path 'examples/third-party/fbjni': checked out '52a14f0daa889a20d8984798b8d96eb03cebd334'
Submodule path 'examples/third-party/llama': checked out 'b00a461a6582196d8f488c73465f6c87f384a052'
Submodule path 'third-party/flatbuffers': checked out '0100f6a5779831fa7a651e4b67ef389a8752bd9b'
Submodule path 'third-party/flatcc': checked out 'eb5228f76d395bffe31a33398ff73e60dfba5914'
Submodule path 'third-party/googletest': checked out 'e2239ee6043f73722e7aa812a459f54a28552929'
Submodule path 'third-party/prelude': checked out '971986683b987d399473969831bca6338833736d'
Submodule path 'third-party/pybind11': checked out '8c7b8dd0ae74b36b7d42f77b0dd4096ebb7f4ab1'
Submodule path 'third-party/pytorch': checked out '468a73f0e3527c52495c864c7d48dc26684f6c0b'
```

**Comment by kimishpatel** [comment]
Closing this as it seems resolved

**Comment by escorciav** [comment]
_note to future self/anyone_

For anyone interested in running things on device, I would complete the [executor setup tutorial](https://pytorch.org/executorch/stable/getting-started-setup.html).

_Why?_
- I managed to successfully export a model [one day](https://github.com/pytorch/executorch/issues/1163#issuecomment-1802330075). The day after, I couldn't build & run it on host/device.
- I went down a rabbit hole related to "buck" (i.e., Meta's own version of Bazel) to later figure it out that
- The issue got solved by deleting `rm -rf executorch` & building it from scratch :sweat: 
 
:sweat_smile:

**Comment by kimishpatel** [comment]
> The issue got solved by deleting rm -rf executorch & building it from scratch

This shouldnt be necessary. THis is worse than "have you tried turning it off and on" :)

cc: @dbort for all build related stuff

**Comment by escorciav** [comment]
Agree that my approach is not a principled solution for executorch & QNN teams, 

but as an end-user I only care about getting my stuff done :)
