### ISSUE TITLE
CoreML backend delegate example does not work

### ISSUE THREAD

**Issue by the-neural-networker** [pytorch/executorch#1164]
I have been trying to run the example code snippet shown for the CoreML delegate [here](https://github.com/pytorch/executorch/tree/main/backends/apple/coreml). I have setup executorch and the coreml backend for it as described [here](https://pytorch.org/executorch/stable/getting-started-setup.html) followed by [here](https://github.com/pytorch/executorch/blob/c0b42d2bfae6b45fcce3555d057a2be79f80bb19/backends/apple/coreml/setup.md). But when running the following example:

```python
import executorch.exir as exir
import torch

from executorch.exir.backend.backend_api import to_backend

from executorch.backends.coreml.compiler import CoreMLBackend

class LowerableSubModel(torch.nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, x):
        return torch.sin(x)

# Convert the lowerable module to Edge IR Representation
to_be_lowered = LowerableSubModel()
example_input = (torch.ones(1), )
to_be_lowered_exir_submodule = exir.capture(to_be_lowered, example_input).to_edge()

# Lower to Core ML backend
lowered_module = to_backend('CoreMLBackend', to_be_lowered_exir_submodule, [])
```

I get a module not found error:

```
Traceback (most recent call last):
  File "/Users/abhiroop/Developer/torch_to_coreml/executorch_example.py", line 6, in <module>
    from executorch.backends.coreml.compiler import CoreMLBackend
ModuleNotFoundError: No module named 'executorch.backends.coreml'
```

Here is the full list of commands I ran to setup Executorch and its CoreML backend:

```bash
git clone --branch v0.1.0 https://github.com/pytorch/executorch.git

cd executorch
git submodule sync
git submodule update --init

conda create -yn executorch python=3.10.0
conda activate executorch

conda install cmake

./install_requirements.sh

./build/install_flatc.sh

./backends/apple/coreml/scripts/install_requirements.sh 
```

Have I missed a step in the installation procedure? Some help in figuring out what I am missing would be much appreciated!

**Comment by mergennachin** [comment]
Hi @the-neural-networker 

Instead of `from executorch.backends.coreml.compiler import CoreMLBackend` can you try `from executorch.backends.apple.coreml.compiler import CoreMLBackend` instead?

**Comment by the-neural-networker** [comment]
Hi @mergennachin, thanks, it fixed the import, but I get an `AssertionError`:

```
Torch version 2.2.0.dev20231010 has not been tested with coremltools. You may run into unexpected errors. Torch 2.0.0 is the most recent version that has been tested.
Traceback (most recent call last):
  File "/Users/abhiroop/Developer/torch_to_coreml/executorch_example.py", line 21, in <module>
    lowered_module = to_backend('CoreMLBackend', to_be_lowered_exir_submodule, [])
  File "/Users/abhiroop/anaconda3/envs/executorch/lib/python3.10/functools.py", line 878, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/Users/abhiroop/anaconda3/envs/executorch/lib/python3.10/site-packages/executorch/exir/backend/backend_api.py", line 104, in _
    assert isinstance(edge_program, ExportedProgram)
AssertionError
```

What could be the reason? How do I fix it?

**Comment by cccclai** [comment]
Maybe try the following?
```
lowered_module = to_backend('CoreMLBackend', to_be_lowered_exir_submodule.exported_program, [])
```

**Comment by mergennachin** [comment]
@the-neural-networker 

The README.md might be out of date. We will update it. cc @JacobSzwejbka 

However, the script should be working and validated via our CI.

https://github.com/pytorch/executorch/blob/main/examples/apple/coreml/README.md

I just ran `python3 -m examples.apple.coreml.scripts.export_and_delegate --model_name add` and seems to be working

Use https://github.com/pytorch/executorch/blob/v0.1.0/examples/apple/coreml/scripts/export_and_delegate.py (or from main branch) as reference for your custom script.

**Comment by mergennachin** [comment]
Just updated our README.md instructions. 

Thanks for reporting the issue, @the-neural-networker 

https://github.com/pytorch/executorch/pull/1166

**Comment by the-neural-networker** [comment]
> Maybe try the following?
> 
> ```
> lowered_module = to_backend('CoreMLBackend', to_be_lowered_exir_submodule.exported_program, [])
> ```

The above works. Thanks @cccclai! @mergennachin I will check out the reference you shared for writing my custom script. Thanks!

**Comment by the-neural-networker** [comment]
> Just updated our README.md instructions.
> 
> Thanks for reporting the issue, @the-neural-networker
> 
> #1166

No problem!

**Comment by denfromufa** [comment]
🚀
