### ISSUE TITLE
Delegating to a backend

### ISSUE THREAD

**Issue by adonnini** [pytorch/executorch#1169]
Hi,

I am taking the steps to run my model for inference in my Android app.

As I understand after building the exported model, the next step is to delegate to a backend. Is this right?

I have a couple of questions regarding the sample code for lowering a module in

a) Lowering the Whole Module (https://pytorch.org/executorch/stable/tutorials/export-to-executorch-tutorial.html#lowering-the-whole-module)
and 
b) Lowering a model to XNNPACK (https://pytorch.org/executorch/stable/tutorial-xnnpack-delegate-lowering.html#lowering-a-model-to-xnnpack)

Specifically:
1) In a) the file which is saved is the lowered module while in b) it is the ```to_executorch()``` file. Aren't they different? Which is right? What am I missing?

2) The call ```to_backend``` in a) has a number of arguments while in b) its only argument is the backend name. Can I use either one? Is one preferable over the other?

I intend on using XNNPACK. Should I just go with code like the one in b), or it doesn't really matter as except for the two points described above, I did not notice significant differences?

Thanks

From https://pytorch.org/executorch/stable/tutorials/export-to-executorch-tutorial.html#lowering-the-whole-module
```
class LowerableModule(torch.nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, x):
        return torch.sin(x)


# Export and lower the module to Edge Dialect
example_args = (torch.ones(1),)
pre_autograd_aten_dialect = capture_pre_autograd_graph(LowerableModule(), example_args)
aten_dialect: ExportedProgram = export(pre_autograd_aten_dialect, example_args)
edge_program: EdgeProgramManager = to_edge(aten_dialect)
to_be_lowered_module = edge_program.exported_program()

from executorch.exir.backend.backend_api import LoweredBackendModule, to_backend

# Import the backend
from executorch.exir.backend.test.backend_with_compiler_demo import (  # noqa
    BackendWithCompilerDemo,
)

# Lower the module
lowered_module: LoweredBackendModule = to_backend(
    "BackendWithCompilerDemo", to_be_lowered_module, []
)
print(lowered_module)
print(lowered_module.backend_id)
print(lowered_module.processed_bytes)
print(lowered_module.original_module)

# Serialize and save it to a file
save_path = "delegate.pte"
with open(save_path, "wb") as f:
    f.write(lowered_module.buffer())
```

From https://pytorch.org/executorch/stable/tutorial-xnnpack-delegate-lowering.html#lowering-a-model-to-xnnpack
```
import torch
import torchvision.models as models

from torch.export import export
from torchvision.models.mobilenetv2 import MobileNet_V2_Weights
from executorch.backends.xnnpack.partition.xnnpack_partitioner import XnnpackPartitioner
from executorch.exir import to_edge


mobilenet_v2 = models.mobilenetv2.mobilenet_v2(weights=MobileNet_V2_Weights.DEFAULT).eval()
sample_inputs = (torch.randn(1, 3, 224, 224), )

edge = to_edge(export(mobilenet_v2, sample_inputs))

edge = edge.to_backend(XnnpackPartitioner)

exec_prog = edge.to_executorch()

with open("xnnpack_mobilenetv2.pte", "wb") as file:
    file.write(exec_prog.buffer)
```

**Comment by kimishpatel** [comment]
I suggest following b here https://pytorch.org/executorch/stable/tutorial-xnnpack-delegate-lowering.html#lowering-a-model-to-xnnpack.

cc: @digantdesai @mcr229 

@angelayi for the export tutorial and whether it is still valid to not do .to_executorch?

**Comment by kimishpatel** [comment]
@adonnini please let us know if following b works and if it does @mcr229 please close the issue

**Comment by mcr229** [comment]
To answer your questions:

1) I do believe you should be calling `to_executorch` before saving the file as .pte.I would recommend following b if you are trying to lower to XNNPACK.

2) There are two main differences between the api used in example a and example b. 

- In a) we use the free function `to_backend`, and in b) to_backend is called from the exirexportedprogram which is just a calling the free function to_backend on the exportedprogram, which is why you can omit the `to_be_lowered_module` argument from the `to_backend` call in b.
- The second difference is using a partitioner vs using the backend str id. Calling to_backend with a partitioner, uses the partitioner to select the operator nodes lowerable to the specified backend. calling `to_backend` with the backend str id will lower the all the nodes(though it may not work as some nodes may not be supported by the backend). A difference in using the backend id vs partitioner is that you may pass in compile specs to help configure the backend lowering, which is why you may see that extra argument there. I believe it is generally safer to lower to a backend using the partitioner API.

**Comment by angelayi** [comment]
Yes, as Max mentioned these are two different APIs. 

* The first API (`to_backend(backend_name, to_be_fully_lowered_module, compile_spec)` is to delegate the entire module to the backend, when you know that the entire module is lowerable to the backend. 

* The second API (`to_backend(to_be_partially_lowered_module, backend_partitioner)` will use the backend partitioner to lower parts of the model which are supported by the backend. This flow is also mentioned in the export tutorial: https://pytorch.org/executorch/stable/tutorials/export-to-executorch-tutorial.html#partition-and-lower-parts-of-a-module. In your case, probably using the `XNNPackPartitioner` is best if you don't know for sure your own module is lowerable to XNNPack.

For saving to a file:

* You can get the buffer to save from the first API by just calling `lowered_module.buffer`, as the fully lowered module can be directly lowered.

* And you can get the buffer to save from the second API by calling `edge.to_executorch().buffer`. We need to go through the `to_executorch()` step to convert the rest of the not-lowereable parts of the model to a representation that can run on the executorch runtime.

**Comment by kimishpatel** [comment]
> * You can get the buffer to save from the first API by just calling `lowered_module.buffer`, as the fully lowered module can be directly run on the executorch runtime.
> *

@angelayi would it make sense to simplify the UI by just having to_executorch called regardless. I also do find it confusing that I can just serialize the `buffer` as pte and that just works without having to go through to_executorch which would actually do `emit` etc.

**Comment by angelayi** [comment]
The lowered module is a different type, so we would have to complicate `to_executorch`.
