### ISSUE TITLE
Support more Qualcomm SoCs

### ISSUE THREAD

**Issue by jingcheng88** [pytorch/executorch#1176]
Support more Qualcomm SoCs when use Qualcomm AI Engine Direc.

**Comment by haowhsu-quic** [comment]
Hi @jingcheng88 , thank you for using Qualcomm AI Engine Direct. May I know which SoC you are interested?

**Comment by jingcheng88** [comment]
@haowhsu-quic Qualcomm SA8295. I have tried add SA8295 myself but failed with following error:
```
QNN_EXECUTORCH_LOG(
        kLogLevelWarn,
        "[Qnn ExecuTorch] Failed to get soc info for "
        "soc model %d. Using default soc_model=%d",
        htp_options_.soc_model,
        default_soc_model);
````
One of the places that i modifeid:
```
typedef enum 
  UNKNOWN_SM = 0,
  SM8450 = 36, // v69
  SM8475 = 42, // v69
  SM8550 = 43, // v73
  SA8295 = 39, // v68
} QcomChipset;
```

**Comment by haowhsu-quic** [comment]
Could you try grepping all the file locations including "SM8550" and add SoC information accordingly. From your message, it looks like [PopulateSocInfoTable](https://github.com/pytorch/executorch/blob/3053662e4bb6d0b81a6dc4c96b6c634ad7a67e81/backends/qualcomm/runtime/Utils.cpp#L12) not getting updated.

**Comment by jingcheng88** [comment]
```
const std::map<QcomChipset, HtpInfo>& PopulateSocInfoTable() {
  static const std::map<QcomChipset, HtpInfo> soc_info_map{
      {QcomChipset::SM8550,
       {QcomChipset::SM8550,
        QnnHtpDevice_Arch_t::QNN_HTP_DEVICE_ARCH_V73,
        "SM8550",
        8}},
      {QcomChipset::SM8450,
       {QcomChipset::SM8450,
        QnnHtpDevice_Arch_t::QNN_HTP_DEVICE_ARCH_V69,
        "SM8450",
        8}},
      {QcomChipset::SM8475,
       {QcomChipset::SM8475,
        QnnHtpDevice_Arch_t::QNN_HTP_DEVICE_ARCH_V69,
        "SM8475",
        8}},
      {QcomChipset::SA8295,
       {QcomChipset::SA8295,
        QnnHtpDevice_Arch_t::QNN_HTP_DEVICE_ARCH_V68,
        "SA8295",
        8}},
  };
  return soc_info_map;
}
```

![image](https://github.com/pytorch/executorch/assets/8472283/fab3e1ca-ceca-441f-8a7f-a2959a96cde4)

![image](https://github.com/pytorch/executorch/assets/8472283/d1ab850c-3b5c-4102-aada-e15e517e7f88)

**Comment by jingcheng88** [comment]
After i recompile libexecutorchdemo.so, the error changed:
```
W  [Qnn ExecuTorch] Get soc info for soc model 39.  # Add 
W [Qnn ExecuTorch]:  <W> HTP arch will be deprecated, please set SoC id instead.
E [Qnn ExecuTorch]:  <E> Unsupported HTP arch 69 from device custom config
E [Qnn ExecuTorch]:  <E> Failed to parse custom config: 14001
E [Qnn ExecuTorch]:  <E> Failed to parse platform config: 14001
```
HTP arch should be V68 for SA8295.

**Comment by haowhsu-quic** [comment]
Yes, SA8295 should be v68. Have you copied the rebuilt pybind libraries (build_x86_64/backends/qualcomm/PyQnn*) to backends/qualcomm/python?
Also, should be aware of pushing the correct skel / stub version to the device.

**Comment by kimishpatel** [comment]
@jingcheng88 is the error happening at runtime or during delegation?

**Comment by jingcheng88** [comment]
@kimishpatel Runtime. 
@haowhsu-quic I did all those things.

**Comment by chiwwang** [comment]
Not sure why 69 is passed instead of 68 even with the correct setting in `PopulateSocInfoTable`. A quick guess might be aarch64 is not re-compiled correctly.

@jingcheng88  Could you please provide a PR or draft PR containing your changes? Best to have reproduce steps and then we can look into this issue.

And for unblocking the progress, you might want to hack a bit to force V68 at https://github.com/pytorch/executorch/blob/9682172576d5d9a10f3162ad91e0a32b384a3b7c/backends/qualcomm/runtime/backends/htpbackend/HtpDevice.cpp#L309 and https://github.com/pytorch/executorch/blob/9682172576d5d9a10f3162ad91e0a32b384a3b7c/backends/qualcomm/runtime/backends/htpbackend/x86_64/HtpDevicePlatformInfoConfig.cpp#L38.

**Comment by jingcheng88** [comment]
@chiwwang https://github.com/pytorch/executorch/pull/1196
https://pytorch.org/executorch/stable/build-run-qualcomm-ai-engine-direct-backend.html
https://pytorch.org/executorch/stable/demo-apps-android.html?highlight=demo

I run the demo app according to the guidelines.

**Comment by chiwwang** [comment]
Thank you for the information. The PR looks correct. We will give it a try.

BTW, I checked the tutorial https://pytorch.org/executorch/stable/demo-apps-android.html?highlight=demo
One question -- did you re-compile the .pte file and re-push to the device?
I.e., put it to the `asset` folder of app and trigger `gradle clean`, `gradle build`. `gradle clean` is possibly required since gradle might fail to detect modifications of assets.
ExecuTorch is currently AOT so the dsp_arch info is actually embedded in .pte file.

**Comment by jingcheng88** [comment]
@chiwwang I delete build_x86, build_android, cmake-out and re-build. 
I also re-compile the .pte file, remove old .pte  and put new one to the assets. 
```
python -m examples.qualcomm.scripts.deeplab_v3 -b build_android -m SA8295 -c
```
I will retry again to confirm.

**Comment by chiwwang** [comment]
Hi @jingcheng88 ,

I fetched your branch, built the code and ran it on a V68 device.
```bash
 python -m examples.qualcomm.scripts.deeplab_v3 -b build_android -m SA8295
```
And it works.

So maybe some problems while the `.pte` file was packaged into Android demo apk... maybe Android Studio didn't package latest .pte in `assets` folder?
Could you try to run the above `python -m ....` to see if the model can work with simple ADB setup? Just remove the `-c` from the command you used and the script should push related files to the device through `adb`.

**Comment by jingcheng88** [comment]
@chiwwang I can't connect to `SA8295` through `adb` directly.  So i connected to `8 Gen1 (V69)` through `adb`  and run `adb  shell "./qnn_executor_runner"` to do some test.
I found a strange issue. 
If i built with `- m SA8295`, it works.
```
python -m examples.qualcomm.scripts.deeplab_v3 -b build_android -m SA8295
```
if i built with `-m SM8550`, it resulted in the following error.
```
[ERROR] <E> Unsupported HTP arch 73 from device custom config
```
So i think `PopulateSocInfoTable` didn't run as expected."

**Comment by chiwwang** [comment]
Hi @jingcheng88 
Oops, I think it's on us. It seems we failed to have clear notation for dsp_arch.

If you build with `-m SM8550`, then `73` is correct. `SM8550` is `8 Gen 2 (V73)`.
If you have a `8 Gen1 (V69)`, I think it's `SM8450`. Or `SM8475` for `8 Gen1+`. So please use `-m SM8450` to compile the `.pte` file.

But at least you got a V68 compiled binary by `-m SA8295` worked on a V69 device. It's a good sign -- your code about adding SoC is correct.

**Comment by jingcheng88** [comment]
@chiwwang 
```
# adb shell " ls -l /data/local/tmp/executorch/dlv3_qnn|grep Htp"
-rwxrwxrwx 1 shell shell   1257600 2023-11-07 15:57 libQnnHtp.so
-rwxrwxrwx 1 shell shell   6057216 2023-11-07 15:57 libQnnHtpV68Skel.so
-rwxrwxrwx 1 shell shell    376616 2023-11-07 15:57 libQnnHtpV68Stub.so

# adb shell "./qnn_executor_runner --model_path ./dlv3_qnn.pte"
[WARNING] <W> Initializing HtpProvider
[ERROR] <E> Failed in loading stub: dlopen failed: library "libQnnHtpV69Stub.so" not found
[ERROR] <E> Unable to load Remote symbols 4000
[ERROR] <E> Unable to load Remote symbols 4000
```
I think the error should be as following if i build with `-m SA8295` and run it on `8 Gen1`.
```
[ERROR] <E> Unsupported HTP arch 68 from device custom config
```

**Comment by chiwwang** [comment]
> I think the error should be as following if i build with -m SA8295 and run it on 8 Gen1.
> [ERROR] <E> Unsupported HTP arch 68 from device custom config

Strictly speaking, yes. We cannot assume V68 binary work on V69 devices. But the error might a bit different from the above.


So did you try the below command on `8 Gen 1`?
```
python -m examples.qualcomm.scripts.deeplab_v3 -b build_android -m SM8450
```
I think it should work, and the script should push correct `libQnnHtpV69Stub.so`.

As an overall picture, the flow is
1. The script `deeplab_v3.py` compile the model against a specific SoC, passed by `-m` argument.
2. It also push required `.so` for the specific SoC. For example, `libQnnHtpV69Stub/Skel.so` for `8 Gen 1`
In `SA8295` case, as you added in `examples/qualcomm/..../utils.py`, it's `libQnnHtpV68Stub/Skel.so`
3. Then when we run `./qnn_executor_runner` on a device, it performs:
a. dlopen `libQnnHtp.so`
b. `libQnnHtp.so` check the device spec, and open corresponding `libQnnHtpVxxStub.so`
c. `libQnnHtpVxxStub.so` requests Hexagon to open `libQnnHtpVxxSkel.so`.

So you see the error message `[ERROR] <E> Failed in loading stub: dlopen failed: library "libQnnHtpV69Stub.so" not found`
because of the above step `b.`

**Comment by jingcheng88** [comment]
@chiwwang What can I do next?

**Comment by chiwwang** [comment]
If you're using `8 Gen1`, please use the below command
```
python -m examples.qualcomm.scripts.deeplab_v3 -b build_android -m SM8450
```

If you're using `SA8295`, please build codes with your PR and use the below command
```
python -m examples.qualcomm.scripts.deeplab_v3 -b build_android -m SA8295
```
If `adb` is not available, you can also try to run on `8 Gen 1`.
Though I said we cann't assume V68 binaries can work on a V69 device, it's still worth a try. It might work.


After you make sure executorch can work on the corresponding platform, I think you can start to integrate artifacts into apk if you wish.

**Comment by chiwwang** [comment]
mmmmmm...  based on the error message and test scenario, I might still consider Android Studio doesn't package correct `.pte` file for `SA8295`.

We can find it out.
I think you have two apk, one for `SM8450` and the other for `SA8295`, right?
Assuming names are `demo-app-sm8450.apk` and `demo-app-sa8295.apk`.
Let's unzip these two `.apk` by
```
mkdir unzipped_8450
unzip -d unzipped_8450 demo-app-sm8450.apk
mkdir unzipped_8295
unzip -d unzipped_8295 demo-app-sa8295.apk
```
Then, we can find `assets` directory inside the `unzipped_*` directory.
Please compare them with `diff` command to corresponding `.pte` files compiled previously on host.
I suspect the `.pte` inside `demo-app-sa8295.apk` was mis-packaged by `gradle` or Android Studio. It might be actually `.pte` for `8 Gen 1`.

Or you can add traces around https://github.com/pytorch/executorch/blob/1cb4b726fdf6ab05e1bc67843881dc134291a705/backends/qualcomm/runtime/QnnExecuTorchBackend.cpp#L97
to see what exactly the `compile_spec` is embedded in the `.pte` file.

**Comment by jingcheng88** [comment]
> After i recompile libexecutorchdemo.so, the error changed:
> 
> ```
> W  [Qnn ExecuTorch] Get soc info for soc model 39.  # Add 
> W [Qnn ExecuTorch]:  <W> HTP arch will be deprecated, please set SoC id instead.
> E [Qnn ExecuTorch]:  <E> Unsupported HTP arch 69 from device custom config
> E [Qnn ExecuTorch]:  <E> Failed to parse custom config: 14001
> E [Qnn ExecuTorch]:  <E> Failed to parse platform config: 14001
> ```
> 
> HTP arch should be V68 for SA8295.

I have add traces around 
https://github.com/pytorch/executorch/blob/1cb4b726fdf6ab05e1bc67843881dc134291a705/backends/qualcomm/runtime/backends/htpbackend/HtpDevice.cpp#L290

```
QNN_EXECUTORCH_LOG(
        kLogLevelWarn,
        "[Qnn ExecuTorch] Get soc info for "
        "soc model %d.",
        htp_options_.soc_model);
```
The soc model is 39. So i think .pte is built with `SA8295`. I will retry on `SA8295` today.

**Comment by chiwwang** [comment]
Yes `soc_model=39` should be detected as `SA8295`.... so things are really strange.

Could you also add trace directly printing what `arch` is filled us?
After this line https://github.com/pytorch/executorch/blob/1cb4b726fdf6ab05e1bc67843881dc134291a705/backends/qualcomm/runtime/backends/htpbackend/HtpDevice.cpp#L309C9-L309C64

print out `p_custom_config->arch.arch`.

**Comment by jingcheng88** [comment]
@chiwwang The log when i built .pte file.
```
[WARNING][Qnn ExecuTorch] Get soc info for soc model 39.
[WARNING][Qnn ExecuTorch] Get soc info for soc htp arch 68.
```
The log when i ran demo apk on `SA8295`. 
```
W [Qnn ExecuTorch]: [Qnn ExecuTorch] Get soc info for soc model 36.
W [Qnn ExecuTorch]: [Qnn ExecuTorch] Get soc info for soc htp arch 69.
W [Qnn ExecuTorch]:  <W> HTP arch will be deprecated, please set SoC id instead.
E [Qnn ExecuTorch]:  <E> Unsupported HTP arch 69 from device custom config
E [Qnn ExecuTorch]:  <E> Failed to parse custom config: 14001
E [Qnn ExecuTorch]:  <E> Failed to parse platform config: 14001
```
The `SA8295` is in a car. I will find a way to obtain more information about the chip.

**Comment by chiwwang** [comment]
Hey @jingcheng88 ,

So it's quite clear you package SM8450 `.pte` into the APK used by `SA8295` right?

W [Qnn ExecuTorch]:  <W> HTP arch will be deprecated, please set SoC id instead.
E [Qnn ExecuTorch]:  <E> Unsupported HTP arch 69 from device custom config

https://github.com/pytorch/executorch/blob/42268fe406ac544618c52248663c11f427104b91/backends/qualcomm/runtime/QnnExecuTorch.h#L73

36 is SM8450.

So you need to check when you build the APK, what .pte is really package into .apk by Android Sudio.
I never use Android Studio so not sure it's flow, but I might suggest you to start from a fresh environment to get rid of some cache behavior of gradle.

**Comment by jingcheng88** [comment]
@chiwwang I can make sure that i use the right .pte. Only new apk contains log with `htp arch`.
I ran the same apk on `8 GEN1`. It worked and the log is as follows.
```
[Qnn ExecuTorch] Get soc info for soc model 39.
[Qnn ExecuTorch] Get soc info for soc htp arch 68.
<W> HTP arch will be deprecated, please set SoC id instead.
<W> sg_stubPtr is not null, skip loadRemoteSymbols
```

**Comment by chiwwang** [comment]
Hi @jingcheng88 ,
As you can see from codes, the soc model is embedded in `.pte` file. 
If you use the same `.pte` on both 8 Gen 1 and SA8295, you should see the same soc model printed in logs.

But you saw soc=39 on 8 Gen 1 but soc=36 on SA8295. It means different .pte was used.

**Comment by jingcheng88** [comment]
@chiwwang I ran the apk on a new `SA8295` device. The error log changed.
```
E [Qnn ExecuTorch]:  <E> DspTransport.openSession qnn_open failed, 0x80000406
E [Qnn ExecuTorch]:  <E> IDspTransport: Unable to load lib 0x80000406
E [Qnn ExecuTorch]:  <E> DspTransport failed,cannot open session, error 0x00000009
E [Qnn ExecuTorch]:  <E> Unable to load Skel Library. transportStatus: 9
E [Qnn ExecuTorch]:  <E> Failed to retrieve skel build id: err: 10001
E [Qnn ExecuTorch]:  <E> Failed to create transport for device, error: 4000
E [Qnn ExecuTorch]:  <E> Failed to load skel, error: 4000
E [Qnn ExecuTorch]:  <E> Transport layer setup failed: 14001
E [Qnn ExecuTorch]:  <E> Failed to parse default platform info: 14001
E [Qnn ExecuTorch]:  <E> Failed to load default platform info: 14001
E [Qnn ExecuTorch]:  <E> Failed to parse platform config: 14001
E [Qnn ExecuTorch]: [Qnn ExecuTorch] Failed to create device_handle for Backend ID 6, error=14001
I ETLOG   : Fail to configure Qnn device
I ETLOG   : Fail to initialize Qnn Manager
I ETLOG   : Init failed for backend QnnBackend: 0x1
I ETLOG   : In function CheckOk(), assert failed: hasValue_
F libc    : Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 24839 (.executorchdemo), pid 24839 (.executorchdemo)
```

**Comment by Francis235** [comment]
Hi， everyone, I want to ask if anyone has added SA8155 chipset support or tested on SA8155 chipset?

**Comment by Francis235** [comment]
I build my code use this command "python -m examples.qualcomm.scripts.deeplab_v3 -b build_android -m SM8550 --compile_only --download", run on my SA8155 chipset, and get the following error:
hx11:/data/local/tmp/executorch_qualcomm_tutorial # ./qnn_executor_runner --model_path ./dlv3_qnn.pte
I 00:00:00.037259 executorch:qnn_executor_runner.cpp:81] Model file ./dlv3_qnn.pte is loaded.
I 00:00:00.037308 executorch:qnn_executor_runner.cpp:90] Using method forward
I 00:00:00.037320 executorch:qnn_executor_runner.cpp:138] Setting up planned buffer 0, size 9031680.
[INFO][Qnn ExecuTorch] create QNN Logger with log_level 2
[WARNING] <W> Initializing HtpProvider

[ERROR] <E> Unsupported SnapdragonModel by HTP backend

[ERROR] <E> Init support device platform info failed

[ERROR] <E> Failed to init router

[ERROR] <E> QnnLog_create - Provider initialization never called

[WARNING][Qnn ExecuTorch] Failed to create log_handle for backend  6, qnn_log_level 2, error=11002
[INFO][Qnn ExecuTorch] Initialize Qnn backend parameters for Qnn executorch backend type 2
[INFO][Qnn ExecuTorch] Caching: Caching is in RESTORE MODE.
[WARNING] <W> Initializing HtpProvider

[ERROR] <E> Unsupported SnapdragonModel by HTP backend

[ERROR] <E> Init support device platform info failed

[ERROR] <E> Failed to init router

[ERROR] <E> Failed to initialize provider

[ERROR][Qnn ExecuTorch] Failed to create backend_handle for Backend ID 6, error=4000
E 00:00:00.046192 executorch:QnnManager.cpp:84] Fail to configure Qnn backend
E 00:00:00.046199 executorch:QnnExecuTorchBackend.cpp:143] Fail to initialize Qnn Manager
E 00:00:00.046204 executorch:method.cpp:106] Init failed for backend QnnBackend: 0x1
F 00:00:00.046211 executorch:qnn_executor_runner.cpp:160] In function main(), assert failed (method.ok()): Loading of method forward failed with status 0x1.
I want to add SA8155 into executorch and I'm wondering if there's anything I need to pay attention to, what version of HTP architecture should I use? Has anyone done this before?

**Comment by chiwwang** [comment]
Hi @Francis235 
8155 seems a V66 chipset. QNN-HTP doesn't support V66.
We need QNN-DSP to support V66, which is in plan. Stay tuned!

**Comment by Francis235** [comment]
thank you for your reply. Is there any guidance tutorial which users can use QNN-DSP to support V66 on executorch by themselves? replace libQnnHtp.so with libQnnDSP.so will be ok?

**Comment by chiwwang** [comment]
Unfortunately, that would be super complex.
Unlike HTP, DSP cannot AOT compile the model on a x86 machine. Everything need to be done on the device.
And as you can see, our current translation code is in Python. It's impractical to assume Python runtime on an Android device.

The only way to somehow try executorch runtime on a V66 device is to leverage QNN converter and `qnn-context-binary-generator`. Push `qnn_model.so` and `aarch64-android/qnn-context-binary-generator` to an Android device and compile out a context-binary. You might want consult QNN support to see how to do this.

Then you can hack below line:
https://github.com/pytorch/executorch/blob/72c017fbc21f22f6c83f79970f6ccf3a7640272b/backends/qualcomm/qnn_preprocess.py#L87

Instead of return `bytes(qnn_context_binary)` from our Python translations, pull back the context-binary generated by the above steps, read it and wrap it into `PreprocessResult`. By this way, we can wrap it into a `.pte` file.

Then technically we can use this `.pte` on the device with executorch runtime. But it might not really make sense since executorch simply become a wrapper...

**Comment by shuyuan-wang** [comment]
> DspTransport.openSession qnn_open failed

Hi, Did you figure out how to solve this error? I was trying to run model on htp on 8295, this error also occurs.

**Comment by chiwwang** [comment]
> > DspTransport.openSession qnn_open failed
> 
> Hi, Did you figure out how to solve this error? I was trying to run model on htp on 8295, this error also occurs.

The trace obviously show that skel cannot be loaded.
```
E [Qnn ExecuTorch]:  <E> DspTransport.openSession qnn_open failed, 0x80000406
E [Qnn ExecuTorch]:  <E> IDspTransport: Unable to load lib 0x80000406
E [Qnn ExecuTorch]:  <E> DspTransport failed,cannot open session, error 0x00000009
E [Qnn ExecuTorch]:  <E> Unable to load Skel Library. transportStatus: 9
```

It's usually environment setup issue.

To narrow down the environment setup issue, I recommend to:
1. Try to run a model by QNN native tools, e.g., `qnn-net-run`. Follow QNN documents to setup the device environment, including where to put CPU side libraries and where to put Skel libraries. Pay attention to `LD_LIBRARY_PATH` and `ADSP_LIBRARAY_PATH` if they're used.

2. In any error, check `adb logcat` and contact your QNN support. They have a lot of knowledge how to setup a device. Additional traces can be turned on by Hexagon farf runtime configuration. You can check Hexagon SDK or contact QNN support about how to turn on additional Hexagon farf runtime log.

3. Once you confirm `qnn-net-run` works, you can start to try ExecuTorch. Note that executorch is similar to `qnn-net-run` -- they're all applications using QNN libraries. So the setup of QNN libraries remain the same. Again please pay attention to what QNN version you build executorch against with, which SoC you compiled the model for, where CPU libraries are put, and where Skel are put.

4.  If error again, please share outputs of `adb logcat`, which usually has clear messages about why Skel fails to be loaded.

**Comment by benjamintli** [comment]
To piggyback off this thread...if I wanted to get SM8350 running with llama delegating to HTP, do I need to make a code change similar to https://github.com/pytorch/executorch/pull/1196? or does it "work out of the box", it's just that there are better optimizations if the model compilation understands exactly what backend it's being delegated to?
