### ISSUE TITLE
android xnnpack example fails

### ISSUE THREAD

**Issue by Infrared1029** [pytorch/executorch#1181]
`python3 -m examples.xnnpack.aot_compiler --model_name="dl3" --delegate`
fails with
 ```
Command '['flatc', '--binary', '-o', '/tmp/tmp8mrxbnc_', '/tmp/tmp8mrxbnc_/program.fbs', '/tmp/tmp8mrxbnc_/data.json']' died with <Signals.SIGKILL: 9>.
```

**Comment by JacobSzwejbka** [comment]
cc @kirklandsign

**Comment by kimishpatel** [comment]
@digantdesai @mcr229 can you take a look

**Comment by digantdesai** [comment]
Could it be running into out-of-memory issue with flatc? 
I remember running into this for some other model.

FWIW - we run this model + backend configuration on Github Actions - see one of the latest runs [here](https://github.com/pytorch/executorch/actions/runs/6856299725/job/18643215191#step:11:4418)

**Comment by kirklandsign** [comment]
+1 to @digantdesai. We ran into this with W2L before. DL3 should work with a 16GB RAM instance. 

FYI: Our team is working on more efficient flatbuffer generation.

**Comment by digantdesai** [comment]
cc @guangy10

**Comment by guangy10** [comment]
@Infrared1029 I'm curious if your flatc is set up correctly. There are known issues with pre-built flatc installed via conda or other package tool. So if you run which `flatc`, you should see `<my_path>/executorch/third-party/flatbuffers/cmake-out/flatc` if you are using the correct one. 

To build and install the correct one (if you haven't done), simply run `sh install_requirements.sh` from executorch root. and add `export PATH="<my_path>/executorch/third-party/flatbuffers/cmake-out:${PATH}"` to your bash profile.

**Comment by Infrared1029** [comment]
> @Infrared1029 I'm curious if your flatc is set up correctly. There are known issues with pre-built flatc installed via conda or other package tool (cc: @cccclai for details). So if you run `which flatc`, you should see `<my_path>/executorch/third-party/flatbuffers/cmake-out/flatc` if you are using the correct one.
> 
> To build and install the correct one (if you haven't done), simply run `sh install_requirements.sh` from executorch root. and add `export PATH="<my_path>/executorch/third-party/flatbuffers/cmake-out:${PATH}"` to your bash profile.

yeah i had it installed properly back then when i tried (as specified in the docs), ill give this another shot later today and update you all.

**Comment by khimanir** [comment]
> +1 to @digantdesai. We ran into this with W2L before. DL3 should work with a 16GB RAM instance.
> 
> FYI: Our team is working on more efficient flatbuffer generation.

I'm using a Virtualbox Ubuntu 20.04 vm. Increasing from <16Gb to >20Gb did not fix this issue for me. Is there any alternative way to build this without increasing RAM anymore?

**Comment by cccclai** [comment]
@lucylq recently landed a stack of changes to emit flatbuffers more efficiently, see https://github.com/pytorch/executorch/issues/885 for details. Maybe it can help. 

Do we know the size of the model?

**Comment by mergennachin** [comment]
@Infrared1029 

We recently improved memory usage during ahead-of-time compilation process. 

I was able to run without any problem:

`python3 -m examples.xnnpack.aot_compiler --model_name="dl3" --delegate`

Closing this issue. Reopen if you encounter any more issues. 

cc @lucylq
