### ISSUE TITLE
What to do when coremltools has missing operations?

### ISSUE THREAD

**Issue by the-neural-networker** [pytorch/executorch#1189]
Hi, when using Executorch CoreML delegate, sometimes `coremltools` returns an error saying that the convert function is not implemented. For example:

```
RuntimeError: PyTorch convert function for op 'max.dim' not implemented.
```

What do I do in such a scenario? Is the alternative switching to a different backend like XNNPack or MPS? I wanted to know what is the best way to handle scenarios where operations are missing in `coremltools`.

**Comment by kimishpatel** [comment]
This needs support 'max.dim' added in coremltools for executorch. cc: @DawerG @cymbalrush

**Comment by mergennachin** [comment]
@cymbalrush , @DawerG 

Having Core ML Partitioner implementation would be good too in this case

**Comment by cymbalrush** [comment]
We are increasing op support but the best way to handle this is to have a Core ML Partitioner. @the-neural-networker could you please file a feature request?

**Comment by mergennachin** [comment]
@the-neural-networker 

Closing this issue as @cymbalrush added CoreMLPartitioner. 

https://github.com/pytorch/executorch/issues/1268
