### ISSUE TITLE
Enable mobilebert quant example

### ISSUE THREAD

**Issue by cbilgin** [pytorch/executorch#1197]
Tracking for the PR:
https://github.com/pytorch/executorch/pull/1043

**Comment by chiwwang** [comment]
cc. @shewu-quic

**Comment by shewu-quic** [comment]
[This pull request](https://github.com/pytorch/executorch/pull/1043) has been merged. Thanks.

**Comment by chiwwang** [comment]
Oops but I don't know how to resolve a github issue.

**Comment by guangy10** [comment]
> Oops but I don't know how to resolve a github issue.

You can use `@pytorchbot close` to close the GitHub Issue once the PR is merged.
