### ISSUE TITLE
Benchmark for inference speed

### ISSUE THREAD

**Issue by EarthMu** [pytorch/executorch#1231]
Hi, 

I run resnet18.pte by following way.  
`(executorch) root@ubuntu:~/test/executorch# ./cmake-out/executor_runner --model_path ./resnet18.pte --img_path test.jpg `

By checking application log, for resnet18, this seems so slow.  
This is running on ubuntu on VMware in `x86_64` arch.  
Is this normal? or is there other recommended way?  
And do you have any benchmark lists?  
  
### Application log
```
I 00:00:00.382397 executorch:executor_runner.cpp:133] Model file ./resnet18.pte is loaded.
I 00:00:00.382473 executorch:executor_runner.cpp:142] Using method forward
I 00:00:00.382480 executorch:executor_runner.cpp:190] Setting up planned buffer 0, size 64346944.
I 00:00:00.437272 executorch:executor_runner.cpp:213] Method loaded.
I 00:00:00.437405 executorch:executor_runner.cpp:219] Inputs prepared.
I 00:02:23.767346 executorch:executor_runner.cpp:228] Model executed successfully.
I 00:02:23.767409 executorch:executor_runner.cpp:232] 1 outputs: 
Output 0: tensor(sizes=[1, 1000], [
.
.
])
```

Thanks,

**Comment by kimishpatel** [comment]
Hello,
BY default exported model uses portable operators which are not meant for performant execution. Have you tried XNNPack delegate? cc: @digantdesai @mcr229

**Comment by mcr229** [comment]
Yup, you can follow this tutorial:
https://pytorch.org/executorch/stable/tutorial-xnnpack-delegate-lowering.html

To try lowering the model to XNNPACK for some faster inference

**Comment by EarthMu** [comment]
@kimishpatel @mcr229 
  
Thank you for your advice.
I will try running the model on XNNPACK.  
  
BR,

**Comment by EarthMu** [comment]
@kimishpatel @mcr229

I could run the resnet18 on XNNPACK backend
`/tmp/buck2 run examples/xnnpack:xnn_executor_runner -- --model_path ./xnnpack-exported-resnet18.pte`  
  
And I have a question.  
Can I build and run xnn_executor_runner by Cmake?
Because in portable executor_runner, I built it including OpenCV library by CMakeLists.txt.  
  
Thanks,

**Comment by mcr229** [comment]
https://pytorch.org/executorch/stable/runtime-build-and-cross-compilation.html

This tutorial may have some additional information on building executor_runner with cmake, can you try it out?

**Comment by EarthMu** [comment]
@mcr229 

Thank you for your help.    
I could build application for XNNPACK backend.
And also I confirmed that its performance increased.  
  
## Procedure
### 1. export model into pte format for xnnpack
```py
import torch
import torchvision.models as models
from torchvision.models.resnet import ResNet18_Weights
from torch.export import export, ExportedProgram
from executorch.backends.xnnpack.partition.xnnpack_partitioner import XnnpackPartitioner
from executorch.exir import to_edge

resnet18 = models.resnet18(weights=ResNet18_Weights.DEFAULT).eval()
resnet18.fc = torch.nn.Sequential(
        resnet18.fc,
        torch.nn.Softmax(dim=1)
        )
sample_inputs = (torch.randn(1, 3, 224, 224), )
edge = to_edge(export(resnet18, sample_inputs))
## Choosing XNNPACK partitioner as backend
edge = edge.to_backend(XnnpackPartitioner)
exec_prog = edge.to_executorch()

with open("xnnpack-exported-resnet18.pte", "wb") as file:
    file.write(exec_prog.buffer)
```
### 2. running xnn_executor_runner
```
/tmp/buck2 run examples/xnnpack:xnn_executor_runner -- --model_path ./xnnpack-exported-resnet18.pte
```
## Performance
### default settings
```
I 00:00:00.382397 executorch:executor_runner.cpp:133] Model file ./resnet18.pte is loaded.
I 00:00:00.382473 executorch:executor_runner.cpp:142] Using method forward
I 00:00:00.382480 executorch:executor_runner.cpp:190] Setting up planned buffer 0, size 64346944.
I 00:00:00.437272 executorch:executor_runner.cpp:213] Method loaded.
I 00:00:00.437405 executorch:executor_runner.cpp:219] Inputs prepared.
I 00:02:23.767346 executorch:executor_runner.cpp:228] Model executed successfully.
I 00:02:23.767409 executorch:executor_runner.cpp:232] 1 outputs: 
Output 0: tensor(sizes=[1, 1000], [
.
.
])
```
### for xnnpack backend
```
I 00:00:00.039777 executorch:executor_runner.cpp:341] Model file ./xnnpack-exported-resnet18.pte is loaded.
I 00:00:00.039815 executorch:executor_runner.cpp:350] Using method forward
I 00:00:00.039819 executorch:executor_runner.cpp:398] Setting up planned buffer 0, size 1404928.
I 00:00:00.041070 executorch:executor_runner.cpp:402] Allocating planned_memory
I 00:00:00.041102 executorch:executor_runner.cpp:416] Loading method in program
I 00:00:00.211679 executorch:executor_runner.cpp:423] Method loaded.
I 00:00:00.211786 executorch:executor_runner.cpp:429] Inputs prepared.
I 00:00:00.629226 executorch:executor_runner.cpp:438] Model executed successfully.
I 00:00:00.629337 executorch:executor_runner.cpp:442] 1 outputs: 
Output 0: tensor(sizes=[1, 1000], [
.
.
])
```

**Comment by ksasso1028** [comment]
can you elaborate on the speedup? how much faster? trying to decide whether or not to ditch torchscript

**Comment by mergennachin** [comment]
Closing this issue as XNNPACK is able to improve the performance.
