### ISSUE TITLE
[TOSA] Export Deprecated constrains

### ISSUE THREAD

**Issue by Jerry-Ge** [pytorch/executorch#1249]
While I'm running the TOSA unit tests: backends/arm/test/test_tosa.py (https://github.com/pytorch/executorch/blob/main/backends/arm/test/test_tosa.py)

I'm always receiving the following warnings. Is there a way to fix or turn it off? 

python3.10/site-packages/torch/_export/__init__.py:610:  DeprecationWarning: Using `constraints` to specify dynamic shapes for export is DEPRECATED and will not be supported in the future. Please use `dynamic_shapes` instead (see docs on `torch.export.export`).

**Comment by digantdesai** [comment]
hmm, this is the warning right? https://github.com/pytorch/pytorch/blob/main/torch/_export/__init__.py#L546-L553

Where is it coming from, I see test_tosa.py doesn't use dynamic dims then why is this condition passing?

**Comment by Jerry-Ge** [comment]
> hmm, this is the warning right? https://github.com/pytorch/pytorch/blob/main/torch/_export/__init__.py#L546-L553
> 
> Where is it coming from, I see test_tosa.py doesn't use dynamic dims then why is this condition passing?

Yes, that's the right place. `I see test_tosa.py doesn't use dynamic dims then why is this condition passing?` this is the weird part...

**Comment by Jerry-Ge** [comment]
hi @Olivia-liu @digantdesai  do you guys have any findings on this issue?

**Comment by Jerry-Ge** [comment]
> It seems like has something to do with the Python unittest. When I isolate the test code snippet out of the `unittest.TestCase` the warning magically disappeared.
> 
> And it can be reproduced by running the following dummy script run script: `python3 -m unittest export_test.py`
> 
> ```python
> import torch
> from torch._export import capture_pre_autograd_graph
> from torch.export import export, ExportedProgram
> import unittest
> 
> class SimpleModel(torch.nn.Module):
>     def __init__(self) -> None:
>         super().__init__()
>         self.relu = torch.nn.ReLU()
> 
>     def forward(self, x: torch.Tensor) -> torch.Tensor:
>         return self.relu(x)
> 
> example_args = (torch.randn(1, 3, 256, 256),)
> 
> class TestDemo(unittest.TestCase):
>     def test_demo(self):
>         pre_autograd_aten_dialect = capture_pre_autograd_graph(SimpleModel(), example_args)
>         aten_dialect: ExportedProgram = export(pre_autograd_aten_dialect, example_args)
> ```

Hi Meta team, could anyone try to reproduce this and hope that can be fixed thanks. @Olivia-liu @digantdesai

**Comment by Jerry-Ge** [comment]
The issue has disappeared with updated PyTorch version.
