### ISSUE TITLE
What is the codegen really done at the Executorch flow?

### ISSUE THREAD

**Issue by kris-himax** [pytorch/executorch#1252]
Hi,

Although I study the https://pytorch.org/executorch/stable/concepts.html#codegen about codegen part, I do not understand very well about this part.
![Screenshot from 2023-11-21 16-38-38](https://github.com/pytorch/executorch/assets/87454575/669a120d-714a-4861-9b5c-1d822bfd29dd)

Above the concepts map, after I export the model.pte file which is the binary file.
Can I directly select the kernel op to run the model with Executorch Runtime library ?

And there is another branch of model.pte file which do the codegen to gen the Kernel Registration Library. I do not understand very well about this part.

My question is that if I can run with model.pte file with kernel op run time library, why need to codegen again?
Or what is the codegen output at real flow? Is it a c code about the graph of the model with ops and the weight?

**Comment by kimishpatel** [comment]
@larryliu0820

**Comment by larryliu0820** [comment]
On a high level codegen does 2 things and we decide to :

1. Use the operator information from models to do selective build.
2. Generate adapter logic to translate void(EValue**) call to void(Tensor, Tensor, ...) call. We call this "unboxing" and we generate glue logic to connect these two type of calls.

For 1 @lucylq  can explain more on how selective build works.

For 2, the alternative is to do a C++ template-based unboxing like what TVM and PyTorch JIT is doing. It could be beneficial in terms of keeping everything in C++, making it easier for user to use. However it is also harder to connect with selective build. In the future we may be able to support both solutions.

**Comment by lucylq** [comment]
> Can I directly select the kernel op to run the model with Executorch Runtime library ?
> My question is that if I can run with model.pte file with kernel op run time library, why need to codegen again?

Codegen is used to generate the [kernel registration](https://pytorch.org/executorch/stable/kernel-library-custom-aten-kernel.html) library which connects the op names referenced in the model with the kernel implementation.

Re the diagram, the arrow between model.pte and codegen indicates selective build. Codegen can consume a model.pte file and select only the ops used by the model. So yes, you can directly select specific ops to include and link with the ExecuTorch runtime (which helps to reduce binary size). 

Keep in mind that selective build is optional (we can build with all the portable kernels, etc. as well). Without it, codegen still occurs to glue together the ExecuTorch runtime and kernel library. 

> Or what is the codegen output at real flow? Is it a c code about the graph of the model with ops and the weight?

The codegen output is a set of C++ bindings (various .h, .cpp files) that connect the kernels to the ExecuTorch runtime.

**Comment by kris-himax** [comment]
Hi,
Thanks for reply.
In my option, can I think the codegen at the Executorch is different from TVM codegen?
According to your reply, the codegen at the Executorch seems like that it generate binding or linking to the ExecuTorch runtime and kernel library. It seems that it is not to input model.pte file and output the c code with weight scalar and the op about the model like TVM. Am I correct?
Another question, where can I see I should select which op to build?
Is it the op list under the link?
If it is the link, there are three type for each ops what do they mean or which one should I choose?
for example,
```
aten::abs
aten::abs.out
aten::abs_
```
https://github.com/pytorch/pytorch/blob/265d6aac0b71b917d6e36c5dd65c22f61644b715/test/expect/HasDecompTest.test_aten_core_operators.expect

**Comment by lucylq** [comment]
> In my option, can I think the codegen at the Executorch is different from TVM codegen?

Yeah, ExecuTorch codegen generates code that connects the runtime and kernel library. I'm not too familiar with TVM codegen, @larryliu0820 can probably speak more on this.

> If I want to do the inference by the Executorch, I still should input the model.pte file. Am I correct?

You should input the model.pte file to codegen if you want selective build. The sample runtime, `executor_runner`, includes all the portable kernels; you can try run your model with `executor_runner` as a first step. By the way, there are some [selective build examples here](https://github.com/pytorch/executorch/tree/main/examples/selective_build). These show how to include specific ops into the `executorch_generated_lib`.

> Another question, where can I see I should select which op to build?

You can check the functions.yaml files for operators, eg. [portable ops](https://github.com/pytorch/executorch/blob/main/kernels/portable/functions.yaml), [optimized ops](https://github.com/pytorch/executorch/blob/main/kernels/portable/functions.yaml).

> Another question is at runner.cpp. How could I decide the size of method_allocator_pool?

The amount of memory depends on the loaded method and the runtime code - see [method allocator](https://github.com/pytorch/executorch/blob/main/examples/portable/executor_runner/executor_runner.cpp#L90-L110). 

> At runner.cpp what is the meaning about program->num_methods() ?

ExecuTorch [methods](https://pytorch.org/executorch/stable/concepts.html#executorch-method) are the executable equivalent of an `nn.Module` Python method. If an eager mode `nn.Module` contains one `forward()` method, that would compile into an ExecuTorch method and `num_methods()` would equal 1.

**Comment by larryliu0820** [comment]
We don't support codegen kernels yet. There's `inductor` on PT2 that is able to generate C++/triton kernels for ops, but that's more suitable to run in server environment with GPU support. We may be able to leverage that in the future, but currently we will ask the users to provide kernels.

> there are many types for each ops what do they mean or which one should I choose?

We've defined a [core ATen Op set](https://pytorch.org/executorch/stable/ir-ops-set-definition.html) that contains all the ops may possibly appear in the exported graph. Once we lower exported graph to ExecuTorch, we will convert these operators to their out-variant, e.g., `add.Tensor` -> `add.out`. Therefore, at runtime we only see these "out" operators.
