### ISSUE TITLE
can i run ExecuTorch on ARM Cortex-M3?

### ISSUE THREAD

**Issue by mashuai191** [pytorch/executorch#1283]
as title

**Comment by mergennachin** [comment]
Hi @mashuai191 

Yes, we tested on Cortex-M33 and Cortex-M55 architecture. We haven't specifically tested on Cortex-M3 but we built ExecuTorch with [portability in mind](https://pytorch.org/executorch/stable/runtime-overview.html#portable-code-and-architecture). I'd suggest to try it out following our documentation. If you find any issues, let us know.

**Comment by mashuai191** [comment]
thanks for reply!

**Comment by mergennachin** [comment]
Let us know if you find any issues during deployment. In the meantime, I'll close this issue for now
