### ISSUE TITLE
cmake error

### ISSUE THREAD

**Issue by lizhiwen19900709** [pytorch/executorch#1286]
![image](https://github.com/pytorch/executorch/assets/15767823/0dcccb19-293b-47f3-8d67-88ae75bb4b39)

CMake Error at CMakeLists.txt:232 (message):
  FLATC_EXECUTABLE must be set when EXECUTORCH_BUILD_FLATC is disabled.  Note
  that EXECUTORCH_BUILD_FLATC may be disabled implicitly when cross-compiling
  or when EXECUTORCH_BUILD_HOST_TARGETS is disabled.

**Comment by adonnini** [comment]
Hi,
I had the same problem (If I understand your problem correctly).
In my case I had to change
-DEXECUTORCH_BUILD_FLATC=OFF \
to
-DEXECUTORCH_BUILD_FLATC=ON \

I hope I didn't waster your time and that this helps

**Comment by larryliu0820** [comment]
So we have 2 options when using CMake: 1. tell CMake what our flatc executable is, or 2. tell CMake to build flatc on our host environment. You will have to choose one of the option to make it work.

**Comment by lizhiwen19900709** [comment]
-DEXECUTORCH_BUILD_FLATC=ON Still fails to compile @adonnini

**Comment by lizhiwen19900709** [comment]
How does that work? @larryliu0820

**Comment by lizhiwen19900709** [comment]
How can I make it come true? @larryliu0820

**Comment by larryliu0820** [comment]
> -DEXECUTORCH_BUILD_FLATC=ON Still fails to compile @adonnini

What is your error message?

**Comment by lizhiwen19900709** [comment]
-DEXECUTORCH_BUILD_FLATC=ON

**Comment by lizhiwen19900709** [comment]
-DEXECUTORCH_BUILD_FLATC=ON    cmake --build . -j16  error 
![1701162623844](https://github.com/pytorch/executorch/assets/15767823/2a532a2a-e8db-4abf-a3e7-a18a9f353f94)
@larryliu0820

**Comment by lizhiwen19900709** [comment]
I upgraded the system to Ubuntu22.04 after the compilation, may be 20.04 system forced upgrade glibc 2.35 caused by the problem

**Comment by adonnini** [comment]
I made the change I mentioned above when running this
```
export ANDROID_NDK=<path-to-android-ndk>

rm -rf cmake-out && mkdir cmake-out && cd cmake-out
cmake .. \
    -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake \
    -DANDROID_ABI=arm64-v8a \
    -DBUCK2=/tmp/buck2 \
    -DEXECUTORCH_BUILD_ANDROID_DEMO_APP_JNI=ON \
    -DEXECUTORCH_BUILD_XNNPACK=ON \
    -DEXECUTORCH_BUILD_FLATC=ON \
    -DEXECUTORCH_BUILD_EXTENSION_DATA_LOADER=ON
```

**Comment by larryliu0820** [comment]
@lizhiwen19900709 the flag should be added when you configure cmake not when you build it. Can you please follow what @adonnini suggested

**Comment by khimanir** [comment]
> @lizhiwen19900709 the flag should be added when you configure cmake not when you build it. Can you please follow what @adonnini suggested
![image](https://github.com/pytorch/executorch/assets/153782277/a01b3c7d-69de-497a-a977-51e8b49fe46a)

I'm having the same issue as this

**Comment by SS-JIA** [comment]
cc: @mcr229 seems the build error is related to XNNPACK; would you know more about what's happening here?

**Comment by mcr229** [comment]
@SS-JIA Not sure this is an xnnpack related issue because all the microkernels are being built. Can you share the errors being thrown in cmake? I repro-ed an error with building this way getting an error that looks like:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/maxren/Desktop/oss/executorch/codegen/tools/gen_oplist.py", line 14, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
make[2]: *** [kernels/portable/selected_operators.yaml] Error 1
make[1]: *** [kernels/portable/CMakeFiles/portable_ops_lib.dir/all] Error 2
make[1]: *** Waiting for unfini
```

Let me know if you're seeing the same error after:
```
cmake --build cmake-out -j4 2> error.log && cat error.log
```

**Comment by mcr229** [comment]
If you're getting the same issue described above, I found that it was because my python executable was my python3 command in which:
```
> which python
> /Users/maxren/miniconda3/envs/executorch/bin/python
> which python3
> /Library/Frameworks/Python.framework/Versions/3.11/bin/python3
```
It seems like pyyaml was not installed in the python executable that was being defaulted to. As a result, I found that when I changed the command to:

```
 rm -rf cmake-out && mkdir cmake-out && cd cmake-out
cmake .. \
    -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake \
    -DANDROID_ABI=arm64-v8a \
    -DBUCK2=tmp/buck2 \
    -DEXECUTORCH_BUILD_ANDROID_DEMO_APP_JNI=ON \
    -DEXECUTORCH_BUILD_XNNPACK=ON \
    -DEXECUTORCH_BUILD_FLATC=ON \
    -DEXECUTORCH_BUILD_EXTENSION_DATA_LOADER=ON \
    -DPYTHON_EXECUTABLE=python
```

I managed to build successfully. 

cc. @larryliu0820 @dbort @guangy10  This kind of issue where the wrong python executable is being used should be reflected either in the docs, or fixed with our ExecuTorch Build set up
