### ISSUE TITLE
CMake failure while Building the DSP firmware image

### ISSUE THREAD

**Issue by nxprxf** [pytorch/executorch#1296]
I'm referring blog https://pytorch.org/executorch/stable/build-run-xtensa.html to BUILDING AND RUNNING EXECUTORCH ON XTENSA HIFI4 DSP. 
My environment:

- Executorch version: v0.1.0 (git clone --branch v0.1.0 https://github.com/pytorch/executorch.git)
- Ubuntu 20.04
- g++: Ubuntu 9.4.0-1ubuntu1~20.04.1
- Python3.10
- Use Python virtual environment

Steps:
I already completed those steps before Building the DSP firmware image, when I tried to run cmake command to configure project, it will reported below errors:

> (.executorch) $ cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_TOOLCHAIN_FILE=/home/pubuser/work/examples/xtensa/xtensa.cmake -DMODEL_PATH=/home/pubuser/work/XtensaDemoModel.pte -DNXP_SDK_ROOT_DIR=/home/pubuser/work/RT68514 -DEXECUTORCH_BUILD_FLATC=0 -DFLATC_EXECUTABLE="$(which flatc)" -DEXECUTORCH_BUILD_XTENSA_EXAMPLE=1 -DNN_LIB_BASE_DIR=/home/pubuser/work/nnlib-hifi4 ..
> -- Found toolchain: xt-clang (/home/pubuser/work/xtensa/XtDevTools/install/tools/)
> -- executorch: Generating source lists
> Error while generating /home/pubuser/work/executorch/cmake-xt/executorch_srcs.cmake. Exit code: 1
> Output:
> 
> Error:
> Traceback (most recent call last):
>   File "/home/pubuser/work/executorch/build/extract_sources.py", line 79, in run
>     cp: subprocess.CompletedProcess = subprocess.run(
>   File "/usr/lib/python3.10/subprocess.py", line 526, in run
>     raise CalledProcessError(retcode, process.args,
> subprocess.CalledProcessError: Command '['buck2', 'cquery', "inputs(deps('//examples/portable/executor_runner:executor_runner'))"]' returned non-zero exit status 2.
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/home/pubuser/work/executorch/build/extract_sources.py", line 235, in <module>
>     main()
>   File "/home/pubuser/work/executorch/build/extract_sources.py", line 220, in main
>     target_to_srcs[name] = sorted(target.get_sources(graph, runner))
>   File "/home/pubuser/work/executorch/build/extract_sources.py", line 133, in get_sources
>     sources: set[str] = set(runner.run(["cquery", query]))
>   File "/home/pubuser/work/executorch/build/extract_sources.py", line 84, in run
>     raise RuntimeError(ex.stderr.decode("utf-8")) from ex
> RuntimeError: [2023-11-28T15:54:42.538+09:00] Build ID: 46fd9dcd-5bdc-4e82-8a03-3a33cdf9b221
> Command failed: 
> From load at implicit location
> 
> Caused by:
>     0: From load at third-party/prelude/prelude.bzl:8
>     1: Error parsing: `prelude//native.bzl`
>     2: error: list of 1 element expression is not allowed in type expression
>           --> third-party/prelude/native.bzl:166:42
>            |
>        166 | def _get_valid_cpu_filters(cpu_filters: [[str], None]) -> [str]:
>            |                                          ^^^^^
>            |
>        
> 
> 
> CMake Error at build/Utils.cmake:103 (message):
>   executorch: source list generation failed
> Call Stack (most recent call first):
>   CMakeLists.txt:170 (extract_sources)
> 
> 
> -- Configuring incomplete, errors occurred!
>

**Comment by larryliu0820** [comment]
It seems your submodule is not configured correctly. Can you do:

```bash
git submodule init
git submodule update
```

**Comment by mohdyusuf** [comment]
Odd, I seem to hit this issue too from basic setup instruction here:
https://pytorch.org/executorch/stable/getting-started-setup.html

Command:
`buck2 build //examples/portable/executor_runner:executor_runner --show-output`

Error:
`
Caused by:
    0: From load at third-party/prelude/prelude.bzl:8
    1: Error parsing: `prelude//native.bzl`
    2: error: list of 1 element expression is not allowed in type expression
          --> third-party/prelude/native.bzl:166:42
           |
       166 | def _get_valid_cpu_filters(cpu_filters: [[str], None]) -> [str]:
           |                                          ^^^^^
`

**Comment by mohdyusuf** [comment]
> Odd, I seem to hit this issue too from basic setup instruction here: https://pytorch.org/executorch/stable/getting-started-setup.html
> 
> Command: `buck2 build //examples/portable/executor_runner:executor_runner --show-output`
> 
> Error:
> 
> ```
> Caused by:
>     0: From load at third-party/prelude/prelude.bzl:8
>     1: Error parsing: `prelude//native.bzl`
>     2: error: list of 1 element expression is not allowed in type expression
>           --> third-party/prelude/native.bzl:166:42
>            |
>        166 | def _get_valid_cpu_filters(cpu_filters: [[str], None]) -> [str]:
>            |                                          ^^^^^
> ```
> 
> `commit 51029c664944ed7461fc1b3d626ec2ea9802bdfe (HEAD, tag: v0.1.0-rc2, tag: v0.1.0)`

Ah, ok - I think I may have overcome this problem - try the *musl* variant of the `buck2` prebuilt binary. Weirdly when I used the *-gnu* variant, I ran into the error above - but the *-musl* variant actually went thru `buck2` compilation flow and for me crapped out at clang++ - which is a different issue.

https://github.com/facebook/buck2/releases/download/2023-07-18/buck2-x86_64-unknown-linux-musl.zst
