### ISSUE TITLE
How to run the pte model on GPU

### ISSUE THREAD

**Issue by EarthMu** [pytorch/executorch#1313]
Hello,

I would like to konw if ExecuTorch supports GPU.
Now I could export model into pte format and execute runtime for xnnpack backend in Intel device.
The device has GPU.

But when I check GPU usage while running the application, GPU wasn't utilized.
If ExecuTorch supports GPU, can you please share me how to use GPU?

### Environment
```
$ lscpu
Architecture:            x86_64
  CPU op-mode(s):        32-bit, 64-bit
  Address sizes:         39 bits physical, 48 bits virtual
  Byte Order:            Little Endian
CPU(s):                  4
  On-line CPU(s) list:   0-3
Vendor ID:               GenuineIntel
  Model name:            Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    CPU family:          6
    Model:               142
    Thread(s) per core:  2
    Core(s) per socket:  2
    Socket(s):           1
    Stepping:            9
    CPU max MHz:         3600.0000
    CPU min MHz:         400.0000
    BogoMIPS:            4599.93
    Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon
                          pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe p
                         opcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad 
                         fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window 
                         hwp_epp md_clear flush_l1d arch_capabilities
```
  
Thanks,

**Comment by EarthMu** [comment]
@kirklandsign 

Thank you.
How about Qualcomm backend?
Is it also WIP?

**Comment by chiwwang** [comment]
Hi @EarthMu ,
Yep, if you have a Qualcomm device, GPU for Qualcomm Ai Engine Direct Backend is WIP. Stay tuned!

**Comment by SS-JIA** [comment]
I will close this issue for now. To summarize we are currently working on a couple of options to run models on the GPU via ExecuTorch:

1. A native GPU delegate for ExecuTorch built on top of the Vulkan API
2. GPU delegation via the Qualcomm delegate, as mentioned previously

Note that the Qualcomm delegate will require a Snapdragon 8 chipset, whereas the native GPU delegate will work as long as Vulkan drivers exist. However, as a disclaimer we will be targeting optimization efforts to mobile GPUs such as Adreno and Mali so YMMV if you are trying to run your model on a laptop or desktop computer.
