### ISSUE TITLE
Object Detection model for Qualcomm backend

### ISSUE THREAD

**Issue by EarthMu** [pytorch/executorch#1445]
Hello, 
I would like to know if there are supported object detection models like `MobileNetV1-SSD`, `EfficientDet` or `Yolov5` which is runnable for Qualcomm backend.  
So far, I couldn't find object detection models for Qualcomm backend in the Docs.
  
Thanks,

**Comment by digantdesai** [comment]
Hello, apologies for a delayed response. It should be possible to run these model using ExecuTorch with or without Qualcomm backend. As of today we don't have these models you listed on Qualcomm backend but [here](https://github.com/pytorch/executorch/tree/main/examples/qualcomm) are some examples to get started with.
