### ISSUE TITLE
question about Setting up QNN Backend

### ISSUE THREAD

**Issue by tensorflowt** [pytorch/executorch#1490]
I followed the examples on the official website and encountered the following problem.
My operation process is as follows：

- Environment Setup【passed】
✅ Download Qualcomm AI Engine Direct SDK【passed】
✅ Download Android NDK【passed】
✅ Setup environment variables【passed】

- End to End Inference
✅ Step 1: Build Python APIs for AOT compilation on x64【passed】
❌ Step 2: Build qnn_executor_runner for Android【failed】

In this part, I first completed the compilation of executorch, but did not completely follow the operations in the example because I could not succeed in the operations in the example.

`cd $EXECUTORCH_ROOT
mkdir build_android
cd build_android
cmake .. \
    -DBUCK2=buck2 \
    -DCMAKE_INSTALL_PREFIX=$PWD \
    -DEXECUTORCH_BUILD_QNN=ON \
    -DQNN_SDK_ROOT=$QNN_SDK_ROOT \
    -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake \
    -DANDROID_ABI='arm64-v8a' \
    -DANDROID_NATIVE_API_LEVEL=23 \
    -B$PWD

cmake --build $PWD -j16`

As you can see here I'm not executing ‘--target install’，What I understand is that my operation should have no impact.
If I follow the example, the following error will be reported！
**gmake: *** No rule to make target 'install'.  Stop.**

for ’qnn_executorch_backend‘:

"""
cmake ../examples/qualcomm \
    -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake \
    -DANDROID_ABI='arm64-v8a' \
    -DANDROID_NATIVE_API_LEVEL=23 \
    -DCMAKE_PREFIX_PATH="$PWD/lib/cmake/ExecuTorch;$PWD/third-party/gflags;" \
    -DCMAKE_FIND_ROOT_PATH_MODE_PACKAGE=BOTH \
    -Bexamples/qualcomm

cmake --build examples/qualcomm -j16

"""
What I understand about this part is to compile the code here in ../examples/qualcomm, but it seems that there is no cmakelist.txt file here.So I understand if I should do this？

“”“
cmake .. \
    -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake \
    -DANDROID_ABI='arm64-v8a' \
    -DANDROID_NATIVE_API_LEVEL=23 \
    -DCMAKE_PREFIX_PATH="$PWD/lib/cmake/ExecuTorch;$PWD/third-party/gflags;" \
    -DCMAKE_FIND_ROOT_PATH_MODE_PACKAGE=BOTH \
    -Bexamples/qualcomm

cmake --build examples/qualcomm -j16
”“”

I'm currently encountering these problems when compiling. I hope I can get your help.
thanks！

**Comment by czy2014hust** [comment]
You can use the script
```bash
./backends/qualcomm/scripts/build.sh
```

**Comment by tensorflowt** [comment]
Hello, I followed the above compilation method and conducted inference tests on 2 Android devices of different models. The results are as follows：

**devices 1：** Qualcomm Snapdragon 8550
![image](https://github.com/pytorch/executorch/assets/37217594/2b25841c-329e-472e-8e2d-a936d72f91c9)


**devices 2：** Qualcomm Snapdragon 765G
![image](https://github.com/pytorch/executorch/assets/37217594/f3a9706b-5145-4eb4-88c6-cc30402437a7)

What I understand is that on the first device 8550, it is because there is no NPU driver yet, so the corresponding library is missing. On the second device 765G, it is because the NPU model does not support it.

Please let me know if my understanding is correct? thks！

**Comment by tensorflowt** [comment]
> You can use the script
> 
> ```shell
> ./backends/qualcomm/scripts/build.sh
> ```

Based on the version 2 days ago, I had no problem using this operation, but today I pulled down the main branch and rebuilt the environment, and found that the operation failed.

Version 2 days ago:
[build_old.txt](https://github.com/pytorch/executorch/files/13786584/build_old.txt)

Version today:
[build_20231228.txt](https://github.com/pytorch/executorch/files/13786595/build_20231228.txt)

What I don’t understand is the mismatch between the executorch package and the corresponding build.sh, because I used today’s executorch environment to compile the original project and found that it would also fail.

The installation process of executorch package is as follows：

`conda create -yn executorch python=3.10.0`
`conda activate executorch`
`conda install cmake    `
`./install_requirements.sh`

I hope to verify whether the build.sh script is running normally under the latest branch, because I can convert the llama2-7b model under this version. I need this environment to do Qualcomm SOC's llama2-7b model inference.

Looking forward to hearing your good news and wishing you a Happy New Year!

**Comment by haowhsu-quic** [comment]
Hi @tensorflowt , the build flow issue has been resolved by this [PR](https://github.com/pytorch/executorch/pull/1447), please check again, thank you.

**Comment by chiwwang** [comment]
> What I understand is that on the first device 8550, it is because there is no NPU driver yet, so the corresponding library is missing. On the second device 765G, it is because the NPU model does not support it.
> 
> Please let me know if my understanding is correct? thks！

You're right!
765G is not supported by QNN-HTP.

For SM8550 error, I'm a bit of surprised. `libcdsprpc.so` should be located in `/vendor/lib64` or so, which should be a default searching path...
But anyway you can try to
```
find /vendor -name "libcdsprpc.so"
```

On my 8550, it outputs:
```
/vendor/lib/libcdsprpc.so
/vendor/lib64/libcdsprpc.so
```

Then you can add `/vendor/lib64` to the environment variable `LD_LIBRARY_PATH`
