### ISSUE TITLE
 Regarding the conversion problem of llama2-7b model

### ISSUE THREAD

**Issue by tensorflowt** [pytorch/executorch#1497]
Under today's branch, I conducted a test of converting llama2-7b model pth to pte. But I used the model in the provided param folder and the conversion was successful. 

`python3 -m examples.models.llama2.export_llama --checkpoint ./examples/models/llama2/params/demo_rand_params.pth --params ./examples/models/llama2/params/demo_config.json`

![executorch-llama2-7b](https://github.com/pytorch/executorch/assets/37217594/77a9495f-383f-4e35-986b-e8d453524aed)

What I want to ask is, if I switch to the official llama2-7b pth model, can the conversion be successful?

**Comment by kirklandsign** [comment]
Hi @tensorflowt we are still working on enabling llama model so please stay tuned.

**Comment by tensorflowt** [comment]
> Hi @tensorflowt we are still working on enabling llama model so please stay tuned.


Do you have a time plan? I'm anxious to apply it recently ？

**Comment by shifeiwen** [comment]
Is there any follow-up update on this matter?

**Comment by lucylq** [comment]
Hey @shifeiwen @tensorflowt, thanks for your patience, you should be able to export the llama2-7b model with executorch.

**Comment by tensorflowt** [comment]
It's a happy message! Also I want to consult, is there a development plan for the LLAMA2-7B of accelerated reasoning verification?

Happy New Year!


---Original---
From: ***@***.***&gt;
Date: Wed, Feb 14, 2024 08:51 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [pytorch/executorch]  Regarding the conversion problem of llama2-7b model (Issue #1497)




 
Hey @shifeiwen @tensorflowt, thanks for your patience, you should be able to export the llama2-7b model with executorch.
