### ISSUE TITLE
How to implement the "aten.mul.Scalar" for Qualcomm backend

### ISSUE THREAD

**Issue by czy2014hust** [pytorch/executorch#1548]
The second arg of "aten.mul.Scalar" is const scalar value, such as float: 0.5f.
The function define_tensor/define_scalar/define_value of NodeVisitor should get the arg "node" as input, but how can I define one node like torch.fx.Node for const scalar value?

**Comment by czy2014hust** [comment]
Implement aten.mul.Scalar to aten.mul.Tensor in passes firstly?

**Comment by shewu-quic** [comment]
Hi,

I create a [PR](https://github.com/pytorch/executorch/pull/1442) which converts mul.Scalar to mul.Tensor to solve it.

Thanks,
Hutton
