### ISSUE TITLE
Runner in Cpp with CMake error

### ISSUE THREAD

**Issue by neverorfrog** [pytorch/executorch#1549]
I am trying to use the cmake built library to do something similar to the executor_runner (following [this tutorial](https://pytorch.org/executorch/stable/running-a-model-cpp-tutorial.html)) in my cmake based system.

I don't know if it's even possible, maybe I'm asking a stupid question. Anyway, the problem that arises is:

/usr/bin/ld: /home/flavio/code/executorch/cmake-out/extension/data_loader/libextension_data_loader.a(file_data_loader.cpp.o): in function `torch::executor::util::FileDataLoader::from(char const*, unsigned long)`:
/home/flavio/code/executorch/extension/data_loader/file_data_loader.cpp:65: **undefined reference to** `torch::executor::internal::getLogTimestamp()`

The libraries are correctly imported but I don't understand why this happens

Thank you in advance

**Comment by kirklandsign** [comment]
Hi @neverorfrog I see the symbol is defined in `runtime/platform/log.cpp` so please make sure this file is added to your lib in CMake.

**Comment by neverorfrog** [comment]
@kirklandsign thank you for your answer.
Maybe I'm missing something, but I thought that by importing libexecutorch.a with `add_library(executorch STATIC IMPORTED)  
set_property(TARGET executorch PROPERTY
             IMPORTED_LOCATION "${TORCH_PATH}/executorch/cmake-out/libexecutorch.a")` also `runtime/platform/log.cpp` should be accessible from my executables, since it is among the source files of libexecutorch in `cmake-out/executorch_srcs.cmake`. 
Thank you again

**Comment by neverorfrog** [comment]
@kirklandsign solved it, I just needed to do `target_link_libraries(extension_data_loader INTERFACE executorch)` also in my cmakelists. Guess i need to learn cmake better. Thanks!
