### ISSUE TITLE
Error when run examples.qualcomm.scripts.deeplab_v3

### ISSUE THREAD

**Issue by Novelfor** [pytorch/executorch#1550]
latest commit has some error when running qualcomm qi engine example

when i run [this tutorial](https://pytorch.org/executorch/stable/build-run-qualcomm-ai-engine-direct-backend.html), I got this error:
```
# after I run python -m examples.qualcomm.scripts.deeplab_v3 -b build_android -m SM8550 --compile_only --download
TypeError: ExportedProgram.__init__() missing 1 required positional argument: 'equality_constraints'
```

I think it's a bug because "ExportedProgram” class in torch need equality_constraints as it's input.
I use ./install_requirements.sh to install torch, it will install 2.2.0.dev20231129+cpu.

**Comment by Jerry-Ge** [comment]
Encountered the same issue when running arm examples here: https://github.com/pytorch/executorch/blob/663882fe7dc518c04adf3d2ee5ccb7d99f41ade4/examples/arm/arm_tosa_e2e.py#L173

**Comment by Jerry-Ge** [comment]
seems related to this PR?: https://github.com/pytorch/executorch/commit/f6f8d0d80b1f6e5b9f45bf16bc016918b155bbb0

**Comment by angelayi** [comment]
Ah sorry, let me update the pin.

**Comment by Jerry-Ge** [comment]
> Ah sorry, let me update the pin. Can you try doing:
> 
> ```
> pip install --force-reinstall --pre torch=="2.3.0.dev20240108" -i https://download.pytorch.org/whl/nightly/cpu
> ```

yep, this now works. thanks Angela!
