### ISSUE TITLE
Update TOSA reference_model to v0.90.0d

### ISSUE THREAD

**Issue by guangy10** [pytorch/executorch#1568]
ExecuTorch CI running TOSA reference_model e2e tests is pinning to `main` because v0.90.0d is not available in https://review.mlplatform.org/plugins/gitiles/tosa/reference_model. As a follow-up on #1335, future version bump on reference_model should still pin on the release/stable version.

**Comment by robell** [comment]
We should be careful to keep this aligned with other projects' support versions.  I'd aim that we do this via the pip dependencies as in this draft to keep compatible versions:

https://github.com/pytorch/executorch/pull/1171/files#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711

**Comment by Jerry-Ge** [comment]
We have updated everything to v0.80 now. Let's close this for now. 

https://github.com/pytorch/executorch/pull/1701
