### ISSUE TITLE
Link Error in Xcode when build ExecuTorchDemo

### ISSUE THREAD

**Issue by magn-obvious** [pytorch/executorch#1590]
I followed this link https://pytorch.org/executorch/stable/demo-apps-ios.html to set up the ExecuTorch iOS Demo App. After finishing build frameworks and move frameworks to examples/demo-apps/apple_ios/ExecuTorchDemo/ExecuTorchDemo/Frameworks, I opened the project in Xcode and try to build the ExecuTorchDemo project. I got link error like this: 

ld: Undefined symbols:
  torch::executor::TensorImpl::TensorImpl(torch::executor::ScalarType, long, int*, void*, unsigned char*, int*, torch::executor::TensorShapeDynamism), referenced from:
      -[ETMobileNetClassifier classifyWithInput:output:outputSize:error:] in libMobileNetClassifier.a[2](MobileNetClassifier-9fafe6e28bd0342839ae5401fb08649d.o)
  torch::executor::runtime_init(), referenced from:
      torch::executor::demo::Module::Module(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&)::$_0::operator()() const in libMobileNetClassifier.a[3](Module.o)
  torch::executor::runtime_abort(), referenced from:
      torch::executor::EValue::toTensor() & in libMobileNetClassifier.a[2](MobileNetClassifier-9fafe6e28bd0342839ae5401fb08649d.o)
      torch::executor::EValue::toTensorList() const in libMobileNetClassifier.a[2](MobileNetClassifier-9fafe6e28bd0342839ae5401fb08649d.o)
      torch::executor::BoxedEvalueList<torch::executor::Tensor>::get() const in libMobileNetClassifier.a[2](MobileNetClassifier-9fafe6e28bd0342839ae5401fb08649d.o)
      torch::executor::ArrayRef<torch::executor::Tensor>::ArrayRef(torch::executor::Tensor const*, unsigned long) in libMobileNetClassifier.a[2](MobileNetClassifier-9fafe6e28bd0342839ae5401fb08649d.o)
      torch::executor::Span<torch::executor::Span<unsigned char>>::Span(torch::executor::Span<unsigned char>*, unsigned long) in libMobileNetClassifier.a[3](Module.o)
      torch::executor::Result<torch::executor::util::MmapDataLoader>::CheckOk() const in libMobileNetClassifier.a[3](Module.o)
      torch::executor::Result<torch::executor::Program>::CheckOk() const in libMobileNetClassifier.a[3](Module.o)
      ...
  torch::executor::util::MmapDataLoader::from(char const*, torch::executor::util::MmapDataLoader::MlockConfig), referenced from:
      torch::executor::demo::Module::Module(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) in libMobileNetClassifier.a[3](Module.o)
  torch::executor::util::MmapDataLoader::~MmapDataLoader(), referenced from:
      torch::executor::Result<torch::executor::util::MmapDataLoader>::~Result() in libMobileNetClassifier.a[3](Module.o)
  torch::executor::Method::get_outputs(torch::executor::EValue*, unsigned long), referenced from:
      torch::executor::demo::Module::forward(std::__1::vector<torch::executor::EValue, std::__1::allocator<torch::executor::EValue>> const&, std::__1::vector<torch::executor::EValue, std::__1::allocator<torch::executor::EValue>>&) in libMobileNetClassifier.a[3](Module.o)
  torch::executor::Method::execute(), referenced from:
      torch::executor::demo::Module::forward(std::__1::vector<torch::executor::EValue, std::__1::allocator<torch::executor::EValue>> const&, std::__1::vector<torch::executor::EValue, std::__1::allocator<torch::executor::EValue>>&) in libMobileNetClassifier.a[3](Module.o)
  torch::executor::Method::set_input(torch::executor::EValue const&, unsigned long), referenced from:
      torch::executor::demo::Module::forward(std::__1::vector<torch::executor::EValue, std::__1::allocator<torch::executor::EValue>> const&, std::__1::vector<torch::executor::EValue, std::__1::allocator<torch::executor::EValue>>&) in libMobileNetClassifier.a[3](Module.o)
  torch::executor::Method::~Method(), referenced from:
      std::__1::default_delete<torch::executor::Method>::operator()[abi:v160006](torch::executor::Method*) const in libMobileNetClassifier.a[2](MobileNetClassifier-9fafe6e28bd0342839ae5401fb08649d.o)
      torch::executor::Result<torch::executor::Method>::~Result() in libMobileNetClassifier.a[3](Module.o)
  torch::executor::Program::load(torch::executor::DataLoader*, torch::executor::Program::Verification), referenced from:
      torch::executor::demo::Module::Module(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) in libMobileNetClassifier.a[3](Module.o)
  torch::executor::internal::getLogTimestamp(), referenced from:
      torch::executor::EValue::toTensor() & in libMobileNetClassifier.a[2](MobileNetClassifier-9fafe6e28bd0342839ae5401fb08649d.o)
      torch::executor::EValue::toTensorList() const in libMobileNetClassifier.a[2](MobileNetClassifier-9fafe6e28bd0342839ae5401fb08649d.o)
      torch::executor::BoxedEvalueList<torch::executor::Tensor>::get() const in libMobileNetClassifier.a[2](MobileNetClassifier-9fafe6e28bd0342839ae5401fb08649d.o)
      torch::executor::ArrayRef<torch::executor::Tensor>::ArrayRef(torch::executor::Tensor const*, unsigned long) in libMobileNetClassifier.a[2](MobileNetClassifier-9fafe6e28bd0342839ae5401fb08649d.o)
      torch::executor::Span<torch::executor::Span<unsigned char>>::Span(torch::executor::Span<unsigned char>*, unsigned long) in libMobileNetClassifier.a[3](Module.o)
      torch::executor::Result<torch::executor::util::MmapDataLoader>::CheckOk() const in libMobileNetClassifier.a[3](Module.o)
      torch::executor::Result<torch::executor::Program>::CheckOk() const in libMobileNetClassifier.a[3](Module.o)
      ...
  torch::executor::internal::vlogf(torch::executor::LogLevel, unsigned long long, char const*, char const*, unsigned long, char const*, __va_list_tag*), referenced from:
      torch::executor::internal::logf(torch::executor::LogLevel, unsigned long long, char const*, char const*, unsigned long, char const*, ...) in libMobileNetClassifier.a[2](MobileNetClassifier-9fafe6e28bd0342839ae5401fb08649d.o)
  torch::executor::MethodMeta::memory_planned_buffer_size(unsigned long) const, referenced from:
      torch::executor::demo::Module::Module(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) in libMobileNetClassifier.a[3](Module.o)
  torch::executor::MethodMeta::num_memory_planned_buffers() const, referenced from:
      torch::executor::demo::Module::Module(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) in libMobileNetClassifier.a[3](Module.o)
  torch::executor::TensorImpl::data() const, referenced from:
      float const* torch::executor::TensorImpl::data<float>() const in libMobileNetClassifier.a[2](MobileNetClassifier-9fafe6e28bd0342839ae5401fb08649d.o)
  torch::executor::BoxedEvalueList<torch::executor::optional<torch::executor::Tensor>>::get() const, referenced from:
      torch::executor::EValue::toListOptionalTensor() const in libMobileNetClassifier.a[2](MobileNetClassifier-9fafe6e28bd0342839ae5401fb08649d.o)
  torch::executor::Method::outputs_size() const, referenced from:
      torch::executor::demo::Module::forward(std::__1::vector<torch::executor::EValue, std::__1::allocator<torch::executor::EValue>> const&, std::__1::vector<torch::executor::EValue, std::__1::allocator<torch::executor::EValue>>&) in libMobileNetClassifier.a[3](Module.o)
  torch::executor::Program::load_method(char const*, torch::executor::MemoryManager*, torch::executor::EventTracer*) const, referenced from:
      torch::executor::demo::Module::Module(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) in libMobileNetClassifier.a[3](Module.o)
  torch::executor::Program::method_meta(char const*) const, referenced from:
      torch::executor::demo::Module::Module(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) in libMobileNetClassifier.a[3](Module.o)
  vtable for torch::executor::util::MmapDataLoader, referenced from:
      torch::executor::util::MmapDataLoader::MmapDataLoader(torch::executor::util::MmapDataLoader&&) in libMobileNetClassifier.a[3](Module.o)
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Actually, libMobileNetClassifier.a is generated. I don't know why. Anyone can help?

**Comment by digantdesai** [comment]
Seems like the compiler wasn't able to find Executorch libraries thus the symbols.
Like missing [this](https://pytorch.org/executorch/stable/demo-apps-ios.html#move-frameworks-for-app-linking) step might lead to this, just a guess.

cc @shoumikhin, for FYI.

**Comment by magn-obvious** [comment]
> Seems like the compiler wasn't able to find Executorch libraries thus the symbols. Like missing [this](https://pytorch.org/executorch/stable/demo-apps-ios.html#move-frameworks-for-app-linking) step might lead to this, just a guess.
> 
> cc @shoumikhin, for FYI.

Hi, 
I did move the framework to the location. 
![Image 2024-01-12 at 7 47 PM](https://github.com/pytorch/executorch/assets/64537372/ed9d2f26-6243-46a2-b799-bb79b7969655)
![Image 2024-01-12 at 7 50 PM](https://github.com/pytorch/executorch/assets/64537372/72be07ef-e3f4-44b7-b0bb-f2da03a4c1dd)

**Comment by shoumikhin** [comment]
Hi @magn-obvious,

Which iOS SDK you used to build ExecuTorch?
Maybe you can attach the produced .xcframework files here?

Thanks.

**Comment by magn-obvious** [comment]
Hi, 
Thank you for info. I will have a try. 
 The iOS SDK is IOS 17.0 and the xcframework is attached. 

> Hi @magn-obvious,
> 
> Which iOS SDK you used to build ExecuTorch? Maybe you can attach the produced .xcframework files here? Also, please check if this [script](https://github.com/pytorch/executorch/issues/1575#issuecomment-1885872291) may be helpful.
> 
> Thanks.

![Image 2024-01-12 at 9 13 PM](https://github.com/pytorch/executorch/assets/64537372/2479f936-85f5-4d90-8975-2831d859201b)
[executorch.xcframework.zip](https://github.com/pytorch/executorch/files/13925996/executorch.xcframework.zip)

**Comment by mergennachin** [comment]
@magn-obvious 

We have been building iOS apps without much problem recently, including LLMs. Please try again with the latest release binary. If it's not working, please create a separate issue.

cc @shoumikhin
