### ISSUE TITLE
Third-Party Error - Prelude is outdated

### ISSUE THREAD

**Issue by podraco** [pytorch/executorch#1604]
This is just a heads up, the prelude package is now obsolete due to data typing changes in prelude, the current version doesn't respect many data typing specifications that StarLark now uses in buck2-prelude.

You can solve this by replacing the version stored in third-party/prelude with it's newest version.

This has been tested with python 3.11

**Comment by mergennachin** [comment]
Hi @podraco 

Thanks for reporting

Which version of buck2 did you see? 

https://pytorch.org/executorch/stable/getting-started-setup.html#building-a-runtime

We currently have a workaround to pin to a particular version of buck2

"Version 2023-07-18 of the buck2 commandline tool — you can download a prebuilt archive for your system from [the Buck2 repo](https://github.com/facebook/buck2/releases/tag/2023-07-18). Note that the version is important, and newer or older versions may not work with the version of the buck2 prelude used by the ExecuTorch repo."

**Comment by podraco** [comment]
Oh, thanks, I used these documents to start building and faced that error.

https://pytorch.org/executorch/main/build-run-qualcomm-ai-engine-direct-backend.html
https://pytorch.org/executorch/main/runtime-build-and-cross-compilation.html

I wasn't aware of the documentation page you shared, thanks.

for now, i replaced the prelude with the newest available, and it seems to work out of the box.
