### ISSUE TITLE
Error: No module named 'executorch.extension.pybindings.portable_lib' 

### ISSUE THREAD

**Issue by Jerry-Ge** [pytorch/executorch#1648]
When I'm running the following test script from XNNPACK
```
python -m unittest backends/xnnpack/test/models/mobilenet_v2.py
```

I got the following error, seems it's missing something here? 

```
ModuleNotFoundError: No module named 'executorch.extension.pybindings.portable_lib' 
```

**Comment by Jerry-Ge** [comment]
cc @digantdesai

**Comment by guangy10** [comment]
@larryliu0820 Is #1588 added support for it?

**Comment by larryliu0820** [comment]
> @larryliu0820 Is #1588 added support for it?

Yes if you build CMake with -DEXECUTORCH_BUILD_PYBIND you should have the module available.

**Comment by guangy10** [comment]
> > @larryliu0820 Is #1588 added support for it?
> 
> Yes if you build CMake with -DEXECUTORCH_BUILD_PYBIND you should have the module available.

Can you elaborate more? It's to run the python unittest, which doesn't need CMake right?

**Comment by guangy10** [comment]
Fix the label. The issue is not related to xnnpack, but to `executorch/extension/pybindings`

**Comment by Jerry-Ge** [comment]
this mentioned issue is gone. close this ticket.
