### ISSUE TITLE
question: Is there a plan to support the acceleration of the ARM Cortex-M7 CMSIS-NN library?

### ISSUE THREAD

**Issue by willChuai** [pytorch/executorch#1716]
Is there documentation on how to adapt the [CMSIS_NN](https://github.com/ARM-software/CMSIS-NN) acceleration library independently, and does this project accept such pull requests?

**Comment by robell** [comment]
Hi @willChuai 

There's no documentation or implementation for a CMSIS_NN integration at present. Though, you can see a bare-metal build which uses the portable library here: https://github.com/pytorch/executorch/tree/main/examples/arm/

We're hoping to look soon at how we introduce this support, most likely with a delegate, and would welcome thoughts and contributions on this.
