### ISSUE TITLE
Add support to ExecuTorch CI to mark a job as unstable and ignore it from CI

### ISSUE THREAD

**Issue by guangy10** [pytorch/executorch#1759]
This is a feature that PyTorch has. Reusing this feature in ExecuTorch would provide the flexibility to exclude unstable jobs from the process and keep the stable branch fresh. As we are setting up the stable branch to automatically promote green commit, this feature would be very helpful to make the process running w/o requiring ALL trunk jobs to be green all the time, which is hard to enforce and typically the fix cycle can be long especially some jobs are owned by external partners. 

![420160399_1454337692104147_8162923362509189186_n](https://github.com/pytorch/executorch/assets/42389959/f5b12cd6-2d95-47ed-afa2-7410ec09f2b2)

**Comment by huydhn** [comment]
AI: Consider using a shorter path, i.e. no need to `.github/actions/..`
