### ISSUE TITLE
Unable to run the llama with buck2

### ISSUE THREAD

**Issue by arm-ssingh** [pytorch/executorch#1806]
I am getting this error when running llama2 with buck2 on arm64-Mac. 
`
(.executorch) (base) sansin03@Q2VG62K29C executorch % /tmp/buck2 run //examples/portable/executor_runner:executor_runner -- --model_path llama2.pte
Build ID: e4629027-4d1c-42df-81bf-20565a884279
Jobs completed: 3. Time elapsed: 0.0s.
BUILD FAILED
From load to implicit location

Caused by:
    0: From load at third-party/prelude/prelude.bzl:8
    1: Error parsing: `prelude//native.bzl`
    2: error: list of 1 element expression is not allowed in type expression
          --> third-party/prelude/native.bzl:166:42
           |
       166 | def _get_valid_cpu_filters(cpu_filters: [[str], None]) -> [str]:
           |                                          ^^^^^
           |
`

          
I am using [buck2-aarch64-apple-darwin.zst](https://github.com/facebook/buck2/releases/download/latest/buck2-aarch64-apple-darwin.zst) 

Also, can you suggest how to configure the underlying backend for the buck2?

**Comment by guangy10** [comment]
It looks like it is an issue to build llama runtime with buck2. CC: @shoumikhin

**Comment by mergennachin** [comment]
Hi @arm-ssingh 

You might need to install this version based on 
https://pytorch.org/executorch/main/getting-started-setup.html#building-a-runtime

`Version 2023-07-18 of the buck2 commandline tool — you can download a prebuilt archive for your system from [the Buck2 repo](https://github.com/facebook/buck2/releases/tag/2023-07-18). Note that the version is important, and newer or older versions may not work with the version of the buck2 prelude used by the ExecuTorch repo.`

Looks like you are installing the latest

**Comment by arm-ssingh** [comment]
@mergennachin  thanks, let me try with that. 
Can you also explain on how the underlying HW (CPU/GPU) can be configured with executorch to run LLAMA?

**Comment by mergennachin** [comment]
Hi @arm-ssingh 

We have revamped our README page for llama2 and llama3 in April. Please take a look. Please open issues if you encounter any problems.

https://github.com/pytorch/executorch/blob/main/examples/models/llama2/README.md
