### ISSUE TITLE
 Issue with Running `executor_runner` on Custom `llama2.pte` File with Meta's llama-7b-chat Weights

### ISSUE THREAD

**Issue by marcin-ochman** [pytorch/executorch#1858]
I successfully created a `llama2.pte` file with Meta's llama-7b-chat weights using the following command:

```
python -m examples.models.llama2.export_llama --checkpoint $LLAMA/consolidated.00.pth --params $LLAMA/params.json
```

However, I encountered an error when attempting to run this file using `executor_runner`. The error message is as follows:

```
E 00:00:00.650431 executorch:file_data_loader.cpp:194] Reading from ../llama2.pte at offset 696320: short read 2147479552 < 26953793540
E 00:00:00.707478 executorch:executor_runner.cpp:70] Failed to parse model file ../llama2.pte
```

Notably, when I use the checkpoint and parameters provided in `examples/models/llama2/params`, the model runs correctly. Additionally, I observed that running the model with the original weights using the llama runner is extremely slow, particularly at the forward method:

```cpp
Result<std::vector<EValue>> outputs_res = module_->forward({EValue(tensor)});
```

Could you provide any insights into what might be causing these issues? Also, what performance metrics (tokens per second) should be expected?

Thank you for your assistance.

**Comment by cccclai** [comment]
exporting it directly will use portable kernel set (focuses on portability but not performance https://github.com/pytorch/executorch/tree/main/kernels/portable/cpu). The performance will be better if it's delegated to xnnpack backend (https://github.com/pytorch/executorch/tree/main/backends/xnnpack)

There should be an arg in `export_llama` to use xnnpack backend. Maybe @kimishpatel or @digantdesai knows more about the xnnpack progress.

**Comment by marcin-ochman** [comment]
Thanks for the reply. I will try that flag. What about the main issue i.e. why `executor_runner` cannot run exported llama2 model with weights other than "demo" weights?

**Comment by iseeyuan** [comment]
It's likely the issue of offset limit. When the model is big, the offset of tensor data may go beyond 32bit. It should have been resolved recently. Could you try to rebase the code to master, regenerate the .pte file and rebuild the runtime? cc @dbort

**Comment by marcin-ochman** [comment]
Thanks for the response. I managed to perform some tests and here are my findings:

1. The example provided with stories110M model works correctly in basic scenario, but it's very, very slow comparing to llama.cpp or llama.c.
2. When stories110M model is exported with xnnpack, running model causes segmentation fault
```sh
python3 -m examples.models.llama2.export_llama -c stories110M.pt   -p params.json --use_kv_cache # export pte
buck2 run examples/models/llama2/tokenizer:tokenizer_py -- -t tokenizer.model -o tokenizer.bin # tokenizer preparation
buck2 run examples/models/llama2:main -- --model_path=llama2.pte --tokenizer_path=tokenizer.bin --prompt="Once"
```

Here is stack:
```sh
Thread 1 "main" received signal SIGSEGV, Segmentation fault.
0x00005555564905af in xnn_f32_vaddc_minmax_ukernel.avx_u16 ()
(gdb) bt
#0  0x00005555564905af in xnn_f32_vaddc_minmax_ukernel.avx_u16 ()
#1  0x0000555556311c25 in xnn_compute_elementwise_binary_1d ()
#2  0x000055555647278c in pthreadpool_parallelize_1d ()
#3  0x0000555556312e8c in xnn_run_operator_with_index ()
#4  0x0000555556308f5c in xnn_invoke_runtime ()
#5  0x00005555563035da in torch::executor::xnnpack::delegate::XNNExecutor::forward(torch::executor::BackendExecutionContext&) ()
#6  0x000055555630257d in torch::executor::XnnpackBackend::execute(torch::executor::BackendExecutionContext&, void*, torch::executor::EValue**) const ()
#7  0x000055555654b1de in torch::executor::BackendDelegate::Execute(torch::executor::BackendExecutionContext&, torch::executor::EValue**) const ()
#8  0x00005555565476c7 in torch::executor::Method::execute_instruction() ()
#9  0x0000555556548620 in torch::executor::Method::execute() ()
#10 0x00005555565371fb in torch::executor::Module::execute(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<torch::executor::EValue, std::allocator<torch::executor::EValue> > const&) ()
#11 0x00005555562e5212 in torch::executor::Module::forward(std::vector<torch::executor::EValue, std::allocator<torch::executor::EValue> > const&) ()
#12 0x00005555562e27c3 in torch::executor::Runner::generate(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::function<void (std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)>) ()
#13 0x00005555562dd3c4 in main ()
```
3. Exporting llama-7B model  with kv cache is currently not possible. Following command fails:
```sh
python3 -m examples.models.llama2.export_llama -c llama-7b-chat-orig/consolidated.00.pth   -p llama-7b-chat-orig/params.json  --use_kv_cache
```
with an error:
```sh
torch._dynamo.exc.TorchRuntimeError: Failed running call_function <built-in function scaled_dot_product_attention>(*(FakeTensor(..., size=(1, 32, 1, 128), dtype=torch.bfloat16), FakeTensor(..., size=(1, 32, u0 + 1, 128)), FakeTensor(..., size=(1, 32, u0 + 1, 128))), **{'attn_mask': FakeTensor(..., size=(1, 1), dtype=torch.bfloat16), 'dropout_p': 0.0}):
Expected query, key, and value to have the same dtype, but got query.dtype: c10::BFloat16 key.dtype: float and value.dtype: float instead.

from user code:
   File "/executorch/examples/models/llama2/model.py", line 444, in forward
    h, updated_cache_k, updated_cache_v = layer(
  File "/executorch/.executorch/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/executorch/examples/models/llama2/model.py", line 357, in forward
    h, cache_k, cache_v = self.attention.forward(
  File "/executorch/examples/models/llama2/model.py", line 265, in forward
    output = F.scaled_dot_product_attention(
```
4. 

It seems there are several, independent issues regarding Llama2 models.

**Comment by mergennachin** [comment]
Hi @marcin-ochman 

We have revamped our README page for llama2 and llama3 in April. Please take a look. Please open issues if you encounter any problems.

https://github.com/pytorch/executorch/blob/main/examples/models/llama2/README.md
