### ISSUE TITLE
Enable back test-arm-backend-delegation CI trunk job

### ISSUE THREAD

**Issue by mergennachin** [pytorch/executorch#1947]
Mengwei tried to fix the ARM CI job with this PR (https://github.com/pytorch/executorch/pull/1945) but still failing with this error

https://github.com/pytorch/executorch/actions/runs/7878561349/job/21497079824?pr=1945&fbclid=IwAR3tRCoJLG1LD5BSUtDcJkWBbhxzJWAHy6I8XQwbNkaJBU5StPuLowr9XaY

We will disable the CI job.

This GH issue is to track the enablement back.  We are not sure the rootcause of it. Some possible explanations are: 

-environment not set up correctly

-Info: Simulation is stopping. Reason: CPU time has been exceeded.

**Comment by Jerry-Ge** [comment]
@robell 's https://github.com/pytorch/executorch/pull/1909 patch should be able to fix that.

**Comment by larryliu0820** [comment]
@Jerry-Ge Thanks I'll hold off the disabling PR then

**Comment by larryliu0820** [comment]
Any help needed from our side? Maybe we can help review?

**Comment by Jerry-Ge** [comment]
> Any help needed from our side? Maybe we can help review?

I guess just need someone from Meta to review and approve the #1909 patch. More details can be answered by @robell when he wakes up from the UK.

**Comment by larryliu0820** [comment]
I stamped. We want to see if the CI job is passing on this PR: `test-arm-backend-delegation`

**Comment by mergennachin** [comment]
In https://github.com/pytorch/executorch/pull/1909/checks, test-arm-backend-delegation is still failing (https://github.com/pytorch/executorch/actions/runs/7878951453/job/21498277494?pr=1909)

I still think we should disable for now, until we have a proper fix, @larryliu0820 , @Jerry-Ge , @robell

**Comment by mergennachin** [comment]
Also, there's no need to stamp just to test 

you can label the PR as `ciflow/trunk` which will trigger all trunk tests.

**Comment by robell** [comment]
the simulation warning is not an issue, this is the corstone-300 platform being shutdown with a timeout after the simulation has been finished.

Error as i see it is 
`WARNING: The script vela is installed in '/var/lib/ci-user/.local/bin' which is not on PATH.`
then later on...
`/bin/sh: 1: vela: not found`

the vela command comes from pip install . in the vela directory (which got a --user flag more recently by Jerry)

for many jobs vela doesn't matter but for the cases which invoke run.sh the ArmBackend is invoked with vela to target u55. 

Seperately on #1909 
`I'm also getting /bin/sh: 1: tosa_reference_model: not found` as a different mode of failure.


It looks to me like the arm jobs are not consistent or calling the supported flow, in particular `setup.sh` is not invoked on the now disabled test-arm-backend-delegation run.

see https://github.com/pytorch/executorch/blob/main/.github/workflows/trunk.yml#L181C1-L181C67

I'm not sure how this ever worked if we're not building vela and tosa_reference_model - environment pollution?


My preference would be
setup venv
run setup.sh
for ethos delegate run run.sh
for tosa invoke a test script from backends/arm/test/<something.sh>

**Comment by robell** [comment]
p.s. it also seems odd to me that we have a tutorial and install_requirements.sh which are stated as a precursor to setup.sh but we don't follow all these steps in the CI.

**Comment by larryliu0820** [comment]
@robell Seems we still have the same issue on the CI. see #2011
