### ISSUE TITLE
XNNPack Error: NameError: name '_load_for_executorch_from_buffer' is not defined

### ISSUE THREAD

**Issue by Jerry-Ge** [pytorch/executorch#2049]
When running the following command, you'll see the errors below: 

-  Command
`python -m unittest backends/xnnpack/test/models/mobilenet_v2.py`
- Error
`NameError: name '_load_for_executorch_from_buffer' is not defined`

**Comment by mcr229** [comment]
Hi Jerry, this is because we haven't yet set up pybind to run these tests. I am actually finding a need for this myself now, so let me try and get this out soon.

**Comment by mcr229** [comment]
Hi Jerry, Pybinding for XNNPACK should now be enabled after this PR https://github.com/pytorch/executorch/pull/2152. 

Try installing as:
```
CMAKE_BUILD_PARALLEL_LEVEL=9 EXECUTORCH_BUILD_XNNPACK=ON EXECUTORCH_BUILD_PYBIND=ON pip install . --no-build-isolation -v
```

and then running:
```
python -m unittest backends/xnnpack/test/models/mobilenet_v2.py
```

**Comment by mcr229** [comment]
revision use this updated command:
```
EXECUTORCH_BUILD_PYBIND=ON CMAKE_ARGS="-DEXECUTORCH_BUILD_XNNPACK=ON" CMAKE_BUILD_PARALLEL_LEVEL=9 pip install . --no-build-isolation -v
```

**Comment by Jerry-Ge** [comment]
thanks
