### ISSUE TITLE
Qualcomm AI Engine Direct - htp_performance_mode 

### ISSUE THREAD

**Issue by salykovaa** [pytorch/executorch#2147]
ONNX Runtime allows users to set "htp_performance_mode" to ['balanced', 'high-performance', 'power_saver', 'burst' etc.] when running a model with QNN backend. Do you also provide such feature or do you plan to add it?

Reference: [https://onnxruntime.ai/docs/execution-providers/QNN-ExecutionProvider.html#configuration-options](https://onnxruntime.ai/docs/execution-providers/QNN-ExecutionProvider.html#configuration-options)

**Comment by czy2014hust** [comment]
You can set the performance mode in here: [generate_qnn_executorch_compiler_spec](https://github.com/pytorch/executorch/blob/main/examples/qualcomm/scripts/export_example.py#L61)

**Comment by salykovaa** [comment]
@czy2014hust 

Thanks! As I understood, the htp performance mode affect neither compilation nor execution and therefore defaulted to "burst_mode" with no option to change it from outside? [htp_performance_mode](https://github.com/pytorch/executorch/blob/5aa4cac3ca22d0991171fe7f691bedb98c58af03/backends/qualcomm/utils/utils.py#L203)

**Comment by salykovaa** [comment]
@czy2014hust thanks for the info!
