### ISSUE TITLE
mpmath package version

### ISSUE THREAD

**Issue by tschimben** [pytorch/executorch#2228]
Hi,

when following the tutorial for setting up executorch (https://pytorch.org/executorch/stable/getting-started-setup.html) the command

`python3 -m examples.portable.scripts.export --model_name="add"`

results in an error

`AttributeError: module 'mpmath' has no attribute 'rational'`.

This is because the actual newest version of the package is 1.4.0. I resolved it by specifically installing version 1.3.0 by running

`pip install mpmath==1.3.0`.

**Comment by mergennachin** [comment]
Should be handled by https://github.com/pytorch/executorch/pull/3593
