### ISSUE TITLE
For the Runtime build for QNN

### ISSUE THREAD

**Issue by na20215** [pytorch/executorch#2439]
the error is appeared when I use this commend to build the runtime for qualcomm NPU：
cmake .. -DQNN_SDK_ROOT=$QNN_SDK_ROOT -DEXECUTORCH_BUILD_QNN=ON -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake -DANDROID_ABI='arm64-v8a' -DANDROID_NATIVE_API_LEVEL=23 -DBUCK2=/tmp/buck2 -DEXECUTORCH_BUILD_XNNPACK=ON -DEXECUTORCH_BUILD_ANDROID_JNI=ON -DEXECUTORCH_BUILD_FLATC=OFF -DEXECUTORCH_BUILD_EXTENSION_DATA_LOADER=ON -DFLATC_EXECUTABLE=/root/autodl-tmp/executorch/third-party/flatbuffers/cmake-out/flatc

ld: error: unable to find library -lextension_module
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
gmake[2]: *** [extension/android/CMakeFiles/executorch_jni.dir/build.make:110: extension/android/libexecutorch_jni.so] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:706: extension/android/CMakeFiles/executorch_jni.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....

**Comment by na20215** [comment]
I found that changing the argument from -DEXECUTORCH_BUILD_ANDROID_JNI back to -DEXECUTORCH_BUILD_ANDROID_DEMO_APP_JNI resolved the error.

**Comment by bingo787** [comment]
why closed？
