### ISSUE TITLE
Failing install_requirements.sh with line errors

### ISSUE THREAD

**Issue by Jaya25Lakshmi** [pytorch/executorch#2878]
On the Setting up Executorch [page](https://pytorch.org/executorch/stable/getting-started-setup.html), there are steps for setting up the environment and step 7 says 'Install ExecuTorch and dependencies' using

`./install_requirements.sh`

As suggested, i installed Anaconda and in the Anaconda prompt, running the above command throws error as  ''.' is not recognized..'. So I used bash install_requirements.sh. It gives a list of errors (below) related to certain line nos. in the install_requirements.sh file. So, I am confused if I am doing wrong or if anything in the .sh file needs to be changed?

`install_requirements.sh: line 7: $'\r': command not found
install_requirements.sh: line 10: pip: command not found
install_requirements.sh: line 11: $'\r': command not found
install_requirements.sh: line 21: $'\r': command not found
install_requirements.sh: line 23: pip: command not found
install_requirements.sh: line 24: $'\r': command not found
install_requirements.sh: line 26: pip: command not found
install_requirements.sh: line 27: $'\r': command not found
install_requirements.sh: line 29: pip: command not found
install_requirements.sh: line 30: $'\r': command not found
install_requirements.sh: line 32: pip: command not found
install_requirements.sh: line 33: $'\r': command not found
install_requirements.sh: line 35: pip: command not found
install_requirements.sh: line 36: $'\r': command not found
install_requirements.sh: line 38: pip: command not found
install_requirements.sh: line 39: $'\r': command not found
: No such file or directoryh`

Here is the .sh file [page ](https://github.com/pytorch/executorch/blob/main/install_requirements.sh)for quick look. 

@iseeyuan

**Comment by mergennachin** [comment]
Hi @Jaya25Lakshmi 

We just released a new stable release a few weeks ago. Can you go through the set up script again?
