### ISSUE TITLE
[Usability] My clone of third-party/pytorch is taking a really long time?

### ISSUE THREAD

**Issue by orionr** [pytorch/executorch#2906]
I just started to run through the ExecuTorch install from GitHub checkout. Really happy to see all of this coming together!

When running the setup commands (look forward to seeing these in the README or https://pytorch.org/executorch/stable/index.html pretty soon!) and running through this

```
git clone https://github.com/pytorch/executorch.git
cd executorch
git submodule sync
git submodule update --init
```

Things really slow down on the line

```
Cloning into '/Users/orionr/local/executorch/third-party/pytorch'...
```

As in, I'm not sure if it is going to complete. Anybody know what is going on? Is there just some weirdness with my setup on a new M1?

I tried to debug with

```
GIT_TRACE=1 GIT_CURL_VERBOSE=1 git submodule update --init
```

but wasn't anything obvious there. Thank you!

cc @dbort @byjlw @iseeyuan @cbilgin

**Comment by mikekgfb** [comment]
I think the only way to reduce the time it takes to get running ith ET is with the prebuilt binaries.

As I indicated elsewhere, we need to include anything that's needed to build applications either in the installed binary build, or as a separate et-dev or et-sdk package

**Comment by orionr** [comment]
I'm going to let the `git submodule update` run this morning and see if it finishes. Crossing my fingers!

**Comment by orionr** [comment]
I know @dbort is working on the pip installs with @huydhn and @kit1980 so hopefully we can have `pip install executorch` working soon. Likely need it for the other (private) repo we're working on.

**Comment by orionr** [comment]
It finished: `git submodule update --init  110.39s user 36.48s system 26% cpu 9:20.57 total`

**Comment by huydhn** [comment]
This should has been addressed by https://github.com/pytorch/executorch/pull/3530 because checking out pytorch is not needed anymore after the change.

**Comment by orionr** [comment]
Agreed! Closing
