### ISSUE TITLE
[Nit] Should we include quick install steps directly in the README?

### ISSUE THREAD

**Issue by orionr** [pytorch/executorch#2915]
I know we are referencing out to the website, but wouldn't it be best to just include them in the README as well with a quick example? I feel like there will be a few entry points to the code:

1. `pip install executorch` (which needs no explanation)
2. https://github.com/pytorch/executorch which can use the README (as recommended here)
3. https://pytorch.org/executorch which can use the quick start guide, but ideally embedded there

We can close this if people don't agree, but checking. Thanks.

cc @mergennachin @byjlw

**Comment by byjlw** [comment]
Yes, I much prefer to keep everything self contained in the readme. I ran into a bunch of issues trying to get the readme to work on a clean environment. I have notes, I'll share them.

**Comment by byjlw** [comment]
Feedback applied
