### ISSUE TITLE
Change behavior of updating input signature (parameter) when lowering to the backend

### ISSUE THREAD

**Issue by mhs4670go** [pytorch/executorch#2989]
Hello.

I'm using executorch with fixed commit and recently updated the commit into the latest one from 34db73d to 1e8c0ff.

Unfortunately, seems that some behavior has been changed.

### 34db73d

https://github.com/pytorch/executorch/blob/34db73d72c4c8b9e2700e14f8723100cd78a7ade/exir/lowered_backend_module.py#L443

### 1e8c0ff

https://github.com/pytorch/executorch/blob/1e8c0fff137ea3728b0c2d6bdfed965181400ad4/exir/lowered_backend_module.py#L464

The issue occurred with below torch module.
```python
class SimpleEmbedding(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.embedding = torch.nn.Embedding(num_embeddings=10, embedding_dim=3)

    def forward(self, arg):
        return (self.embedding(arg),)

    def get_example_inputs(self):
        return (torch.LongTensor([[1, 2, 4, 5], [4, 3, 2, 9]]),)
```

This module internally would be transformed into `ExportedProgram` whose input spec is like below with the single `torch.ops.aten.embedding.default`.
```
1. InputSpec(kind=<InputKind.PARAMETER: 2>, arg=TensorArgument(name='arg0_1'), target='embedding.weight', persistent=None)
2. InputSpec(kind=<InputKind.USER_INPUT: 1>, arg=TensorArgument(name='arg1_1'), target=None, persistent=None)
```

The thing is that when I call `to_backend` with my customized partitioner like below, only `torch.ops.aten.embedding.default` node is marked as my delegation tag. That was not a problem on the former commit (34db73d) but latter one (1e8c0ff) has an issue about it. 

In the former commit, `arg0_1` keeps its input spec's kind as PARAMETER, but in the latter one, `arg0_1`'s kind is changed into USER_INPUT because embedding weight is not tagged.

Seems to me that former behavior is more natural because embedding weight is just constant tensor and I added a tag to its aten embedding node that uses the constant tensor. So, I think the weight should be PARAMETER. Could you let me know the reason of these code changes?

```python
class MyPartitioner(Partitioner):
    compile_spec: List[CompileSpec] = []

    def __init__(self) -> None:
        self.delegation_spec = DelegationSpec(MyBackend.__name__, self.compile_spec)

    def partition(self, exported_program: ExportedProgram) -> PartitionResult:
    # ..
        partition_list = capability_partitioner.propose_partitions()
        for partition in partition_list:
            for node in partition.nodes:
                tag = f"my_{partition.id}"
                node.meta["delegation_tag"] = tag
                partition_tags[tag] = self.delegation_spec

        return PartitionResult(
            tagged_exported_program=exported_program, partition_tags=partition_tags
        )
```

**Comment by vmpuri** [comment]
cc @kimishpatel

**Comment by mcr229** [comment]
I believe there were changes made to the partitioner functionality, in which constant tensors are meant to be explicitly tagged in order to be partitioned. This is to enable more functionality with the partitioner. Previously, as long as a constant tensor was supplied as input to a marked partition(even if it was not tagged), the constant tensor would be pulled into partition. 

However, some delegates may not want to own the constant data, and so if they aren't explicitly tagging these data nodes, they don't want them pulled in to delegation. The change was made so that delegates can choose whether or not they want to own the data through explicit tagging, while previously they had no choice to own as long as it was supplied as an input.

**Comment by mcr229** [comment]
https://github.com/pytorch/executorch/blob/main/exir/backend/utils.py#L503

We introduced a helper function here that will mirror the same behavior as before. Calling this helper at the end, after tagging a desired node in the partitioner, will tag all the constant data used as inputs to these partitions.

**Comment by mhs4670go** [comment]
Thank you for the detail explanation! It really makes sense and the function solved my error:) I'll close this issue.
