### ISSUE TITLE
Memory planner errors?

### ISSUE THREAD

**Issue by mikekgfb** [pytorch/executorch#3425]
When building an LLM with torchchat, executorch issues the following errors => https://github.com/pytorch/torchchat/actions/runs/8888815495/job/24406192435?pr=573

```
[method.cpp:939] Overriding output data pointer allocated by memory plan is not allowed.
[pybindings.cpp:199] Cannot set_output_data_ptr(): this likely means the outputs were MemoryPlanned inspect the error code to know for sure, but likely this is not an issue. 0x2
```

**Comment by cccclai** [comment]
@JacobSzwejbka probably knows it?

**Comment by JacobSzwejbka** [comment]
This is not an error. Its a warning. In this case you can ignore the warning. The pybindings just issue a warning if it cant override the data ptr of outputs from the et program. This can happen if the program memory planned the outputs (whats going on here).

**Comment by JacobSzwejbka** [comment]
https://github.com/pytorch/executorch/pull/3433?fbclid=IwAR1sPd5gAga5aZXqEfyTKlAUU6VNkJ7Gi8CoYh67SNMa-SghYqjAAB28oo4
