### ISSUE TITLE
missing packages & incorrect package versions

### ISSUE THREAD

**Issue by antmikinka** [pytorch/executorch#3430]
- Followed Setup and all installations, including pybinds
- got to converting Llama3 8B Instruct before issues started arriving (using Meta HF Download Script from their llama3 repo)
- **First Issue** numpy needed to be 1.22.4 version or greater for it to work the particular version of Pandas
     - ran `pip install --upgrade numpy`, it worked

- **Second issue** missing **sentencepiece** package
      - ran `pip install sentencepiece`, fixed

- **Third issue** fairseq2 missing? rope_theta not expected?
     - Mentions the fairseq2 missing module or something, but that messed up my env, so I ignored
     - need to use parser and the error still came up in term, but also said it was able to be imported.
     - I tried manually editing some of these llama python files and it wasnt really working
     - could not get the error to go away
     
     `❯ python -m examples.models.llama2.export_llama --checkpoint /Users/anthonymikinka/executorch/meta-llama/Meta-Llama-3-8B-Instruct/original/consolidated.00.pth -p /Users/anthonymikinka/executorch/meta-llama/Meta-Llama-3-8B-Instruct/original/params.json --coreml --output_name="llama3_kv_sdpa_xnn_qe_4_32.pte"
Could not import fairseq2 modules.
INFO:root:Loading model with checkpoint=/Users/anthonymikinka/executorch/meta-llama/Meta-Llama-3-8B-Instruct/original/consolidated.00.pth, params=/Users/anthonymikinka/executorch/meta-llama/Meta-Llama-3-8B-Instruct/original/params.json, use_kv_cache=False, weight_type=WeightType.LLAMA
Traceback (most recent call last):
  File "/opt/anaconda3/envs/executorch/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/anaconda3/envs/executorch/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/anthonymikinka/executorch/examples/models/llama2/export_llama.py", line 30, in <module>
    main()  # pragma: no cover
  File "/Users/anthonymikinka/executorch/examples/models/llama2/export_llama.py", line 26, in main
    export_llama(modelname, args)
  File "/Users/anthonymikinka/executorch/examples/models/llama2/export_llama_lib.py", line 545, in export_llama
    return _export_llama(modelname, args)
  File "/Users/anthonymikinka/executorch/examples/models/llama2/export_llama_lib.py", line 707, in _export_llama
    builder_exported_to_edge = _prepare_for_llama_export(
  File "/Users/anthonymikinka/executorch/examples/models/llama2/export_llama_lib.py", line 629, in _prepare_for_llama_export
    load_llama_model(
  File "/Users/anthonymikinka/executorch/examples/models/llama2/builder.py", line 83, in load_llama_model
    model, example_inputs, _ = EagerModelFactory.create_model(
  File "/Users/anthonymikinka/executorch/examples/models/model_factory.py", line 44, in create_model
    model = model_class(**kwargs)
  File "/Users/anthonymikinka/executorch/examples/models/llama2/model.py", line 119, in __init__
    model_args: ModelArgs = ModelArgs(
TypeError: ModelArgs.__init__() got an unexpected keyword argument 'rope_theta'
`

**Comment by mergennachin** [comment]
@antmikinka thanks for the feedback.

for first and second issue, yeah we will improve our set up script .

fairseq2, you can ignore that. will see if we can silence that error.

for rope_theta issue, are you on `main` or `release/0.2` branch? 

for llama3 you might want to check out the main branch instead. another option is to checkout `viable/strict` branch for better stability

**Comment by mergennachin** [comment]
@antmikinka 

i see that you're using --coreml option. 

currently, the only backend to support llama3 is XNNPACK (use -X option). full command is [here](https://github.com/pytorch/executorch/blob/main/examples/models/llama2/README.md#option-c-download-and-export-llama3-8b-model). We use XNNPACK to use CPU specific accelerations with 4bit quantization.

llama3 is a really large model. we're working with coreml team to take full advantage of the accelerators. stay tuned.

**Comment by antmikinka** [comment]
> @antmikinka thanks for the feedback.
> 
> for first and second issue, yeah we will improve our set up script. did you run examples/models/llama2/install_requirements.sh by any chance?
> 
> fairseq2, you can ignore that. will see if we can silence that error.
> 
> for rope_theta issue, are you on `main` or `release/0.2` branch?
> 
> for llama3 you might want to check out the main branch instead. another option is to checkout `viable/strict` branch for better stability

**Comment by antmikinka** [comment]
@mergennachin 

> i see that you're using --coreml option.


Yes, I tried with it on and off, wasn't working out. 

> currently, the only backend to support llama3 is XNNPACK (use -X option). full command is [here](https://github.com/pytorch/executorch/blob/main/examples/models/llama2/README.md#option-c-download-and-export-llama3-8b-model). We use XNNPACK to use CPU specific accelerations with 4bit quantization.

Sweet! Thank you! Will have to check this out.


> llama3 is a really large model. we're working with coreml team to take full advantage of the accelerators. stay tuned.

Would you have the ANE API? Hahaha! Apple has been hiding that up their sleeve.

Should I close this, or is it better open to serve as a reminder for fixing the first and second problems?
I'm newer to the workflow of this, just not sure...

**Comment by mergennachin** [comment]
@antmikinka 

> Would you have the ANE API? Hahaha! Apple has been hiding that up their sleeve.

From a developer perspective, it will be through Core ML API. ExecuTorch won't expose ANE specific APIs. You can see about the integration here https://pytorch.org/executorch/stable/build-run-coreml.html

> Should I close this, or is it better open to serve as a reminder for fixing the first and second problems?

the second problem, looks like it should be already there. https://github.com/pytorch/executorch/blob/main/examples/models/llama2/install_requirements.sh#L10

i will keep it open until we fix: 

- the first problem, will add minimum version for numpy
- silencing the fairseq2 warning

**Comment by mergennachin** [comment]
@antmikinka 

@lucylq just fixed two problems. will close this github issue.

Let us know if you encounter any other issues
