### ISSUE TITLE
Can I run ExecuTorch on ARM Cortex-A53 processor?

### ISSUE THREAD

**Issue by neverparadise** [pytorch/executorch#3541]
.

**Comment by JacobSzwejbka** [comment]
@digantdesai

**Comment by digantdesai** [comment]
Yes, it should work. It is Armv8-a. We support Armv8-a. We have tests least for Aarch64.

**Comment by neverparadise** [comment]
I haven't built and run it yet. I'm considering using executorch for a project.
I'll try it. Thank you :)

**Comment by neverparadise** [comment]
hello. I'm currently trying to apply a simple time series classification model working on an embedded system using executorch. I'm new to this field, so please forgive me if my questions are strange.  
My current host environment is using Ubuntu 22.04 and my target device uses aarch64 cpu (ARM Cortex-A53).
My questions are as follows. 
1. can I write codes which runs the model exported with executorch by using a C++ API and cross-compile it to run on my target device?
2. I'm currently following the tutorial [Link](https://pytorch.org/executorch/stable/running-a-model-cpp-tutorial.html) trying to cross-compile, but for the line `using namespace torch::executor`, can I just specify the executorch path in an environment variable and write `#include <executorch>`? I'm not sure how I should include the header file. 

Best regards

**Comment by digantdesai** [comment]
> Can I write code which runs the model exported with executorch by using a C++ API and cross-compile it to run on my target device?


Yes. See this for how to cross compile ExecuTorch runtime. - https://dev-discuss.pytorch.org/t/run-llama3-8b-on-a-raspberry-pi-5-with-executorch/2048

**Comment by digantdesai** [comment]
Let me know how it goes, and feel free to reopen this.

**Comment by YasumasaNamba** [comment]
> Let me know how it goes, and feel free to reopen this.

Hi, @digantdesai.

Could you please clarify what the directories lib, lib64, and et_libs refer to in the following command?

```
pi@raspberrypi:~/llm $ ./lib/ld-linux-aarch64.so.1 \  # Copied from toolchain sysroot
    --library-path ./lib/:./lib64:./et_libs/    \  # System Libraries + ExecuTorch Libraries
    ./llama_main                                   # ExecuTorch Llama Runner
    [... other args for the runner ...]
```
