### ISSUE TITLE
Exporting Llama3's tokenizer

### ISSUE THREAD

**Issue by vifi2021** [pytorch/executorch#3555]
Hello,

I am following https://github.com/pytorch/executorch/blob/main/examples/models/llama2/README.md#option-c-download-and-export-llama3-8b-model to make Llama3-8B-instruct to run on an S21 Ultra. But seems like the ```examples.models.llama2.tokenizer.tokenizer``` cannot process llama3's ```tokenizer.model```.

Has anyone run into this issue?

**Comment by iseeyuan** [comment]
@larryliu0820 , could you help look at this?

**Comment by larryliu0820** [comment]
Hello you don't need to process `tokenizer.model` you can just feed it into this step: https://github.com/pytorch/executorch/blob/main/examples/models/llama2/README.md#step-4-run-on-your-computer-to-validate

**Comment by vifi2021** [comment]
Thanks for the fast response. 
But I am not running it on my computer. I am running it on an Android phone. 
In https://github.com/pytorch/executorch/blob/main/examples/models/llama2/README.md#step-5-run-benchmark-on-android-phone step 2.2, it requires to upload model, tokenizer to the phone:
```
adb push <model.pte> /data/local/tmp/llama/
adb push <tokenizer.bin> /data/local/tmp/llama/
```
Looks like we still need ```tokenizer.bin```?

**Comment by jonatananselmo** [comment]
Just do:

adb push <tokenizer.model> /data/local/tmp/llama/

And use <tokenizer.model> wherever you need to specify the tokenizer.

**Comment by JacobSzwejbka** [comment]
@kirklandsign Since theres some android question can u take a look

**Comment by mergennachin** [comment]
@vifi2021 

In Step 4, we have this "For Llama3, you can pass the original tokenizer.model (without converting to .bin file)."

It also applies to subsequent steps.

@kirklandsign 

In our readme file, for Step 5, 2.2 and 2.3, we make that clear.

**Comment by kirklandsign** [comment]
We updated our setup and readme recently. Please check out the latest one.

**Comment by jordanqi** [comment]
For the Qwen2 example, there is no tokenizer.model, only tokenizer.json. How should I push it?

> Just do:
> 
> adb push <tokenizer.model> /data/local/tmp/llama/
> 
> And use <tokenizer.model> wherever you need to specify the tokenizer.
