### ISSUE TITLE
Ensure python version is compatible before building wheels

### ISSUE THREAD

**Issue by Ciao-Wen-Chen** [pytorch/executorch#3570]
Hi I got the following error message after running instruction from [page](https://pytorch.org/executorch/main/getting-started-setup.html#run-your-program)
>> ./install_requirements.sh --pybind

build_meta.py", line 311, in run_setup
        exec(code, locals())
      File "<string>", line 549, in <module>
    TypeError: 'type' object is not subscriptable
    Preparing wheel metadata ... error

![image](https://github.com/pytorch/executorch/assets/67620800/5b9e3a21-f4e1-4f2b-a559-04970913d9f0)

**Comment by mergennachin** [comment]
Looks like you're using python 3.8

ExecuTorch runs on 3.10 and above. 

@dbort - once actionable thing is to update our setup page (https://pytorch.org/executorch/main/getting-started-setup.html) to include supported python versions.

**Comment by dbort** [comment]
Updating the docs makes sense; I thought we already mentioned it, but we don't.

We should also update `install_requirements.sh` and maybe `setup.py` to explicitly check for a compatible python version.

**Comment by Ciao-Wen-Chen** [comment]
yeah, I pointed to the wrong Python version. Get the build successfully, thank you for the reply!

**Comment by dbort** [comment]
#4131 will fix this

**Comment by dbort** [comment]
Merged in https://github.com/pytorch/executorch/commit/f32d707fd89ce64ffbaff6d9c216ac7d15c829e6
