### ISSUE TITLE
Is Qwen in the roadmap?

### ISSUE THREAD

**Issue by DzAvril** [pytorch/executorch#3583]
Hello executorch team,

I have a question regarding the compatibility of executorch with Qwen, an open-source llm created by Alibaba Group [(QWen)](https://huggingface.co/Qwen) . Are there any plans to support Qwen in the future?

Thank you for your attention.

**Comment by mikekgfb** [comment]
I have not looked at Qwen in detail, but if the architecture is similar to llama2 or llama3 it should be very easy to add, by writing a parameter json file for the model. (The MoE part may require some work?)

ExecuTorch is an OSS project and we're excited to take community contributions that meet our open source commitments and coding standards!  So, if you're interested in exploring how to add support for Qwen, we'll be delighted to get a submission!

**Comment by DzAvril** [comment]
![image](https://github.com/pytorch/executorch/assets/18597737/7e85c771-5f35-45bb-bd01-2996193bcae1)
Thanks for your response @mikekgfb . In the v0.2 release note, I noticed that QW1.5 7B has been tested using `torch.export`. Would it be possible for you to share the test code as a reference for supporting QWen with executorch?

**Comment by DzAvril** [comment]
I apologize for reaching out once again, but would it be possible for someone to kindly provide some guidelines on how to support QWen?
