### ISSUE TITLE
Fail to Install Requirements with --pybind xnnpack: Could not find a package configuration file provided by "Torch"

### ISSUE THREAD

**Issue by reganh98** [pytorch/executorch#3589]
Attempted to follow https://pytorch.org/executorch/main/getting-started-setup.html but fail to execute `./install_requirements.sh --pybind xnnpack`

Tested with: Checkout [v0.2.0](https://github.com/pytorch/executorch/tree/v0.2.0) ( https://github.com/pytorch/executorch/commit/4f798326c6545a58ea958ce3b8fa21f109651747 ) as well as the latest commit https://github.com/pytorch/executorch/commit/60c94e81bc0ea31f63977da57a47e2791b909e9d

**Environment:** Google Colaboratory (Python 3.10.12 CPU Runtime)
Also tested on Python 3.9.16 in Paperspace: paperspace/gradient-base:pt112-tf29-jax0317-py39-20230125 

Error Log:
```
CMake Error at CMakeLists.txt:526 (find_package):
    Could not find a package configuration file provided by "Torch" with any of
    the following names:

      TorchConfig.cmake
      torch-config.cmake

    Add the installation prefix of "Torch" to CMAKE_PREFIX_PATH or set
    "Torch_DIR" to a directory containing one of the above files.  If "Torch"
    provides a separate development package or SDK, be sure it has been
    installed.


  -- Configuring incomplete, errors occurred!
  error: command '/usr/local/bin/cmake' failed with exit code 1
  error: subprocess-exited-with-error
  
  × Building wheel for executorch (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /usr/bin/python3 /usr/local/lib/python3.10/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py build_wheel /tmp/tmpxetii_wh
  cwd: /content/executorch
  Building wheel for executorch (pyproject.toml) ... error
  ERROR: Failed building wheel for executorch
Failed to build executorch
ERROR: Could not build wheels for executorch, which is required to install pyproject.toml-based projects
```

Script Executed:
https://colab.research.google.com/gist/reganh98/9bf33111060ea347985acc170b99c130/executorch-fail-to-install-requirements-with-xnnpack.ipynb
OR:
```
!git clone https://github.com/pytorch/executorch.git
%cd executorch

# check out the v0.2.0 tag
!git checkout 4f798326c6545a58ea958ce3b8fa21f109651747

!git submodule sync
!git submodule update --init

!pip uninstall torchtext -y # avoid conflicts during install requirements step

!./install_requirements.sh --pybind xnnpack
```

The checkout line can be omitted to checkout the latest commit but the error still occurs

**Comment by zingo** [comment]
Could it be related to https://github.com/pytorch/executorch/issues/3561  in that case using venv helped us e.g. maybe try adding something like the two env lines below?
```
                    ...
                    git submodule init
                    git submodule update --init
                    python3.10 -m venv env
                    . env/bin/activate
                    ...
```

**Comment by mergennachin** [comment]
@dbort - can you take a look at? looks like it's related to pip package for executorch

**Comment by reganh98** [comment]
Thank you! I did not realize it is a must to use virtual environment. I have tested executing the script below line by line successfully on Paperspace (paperspace/gradient-base:pt112-tf29-jax0317-py39-20230125)

```
# Install Python 3.10 if environment does not have Python 3.10+
sudo apt update
sudo apt-get -y install build-essential zlib1g-dev libffi-dev libssl-dev libbz2-dev libreadline-dev libsqlite3-dev liblzma-dev
cd /home
curl https://pyenv.run | bash
export PATH="~/.pyenv/bin:$PATH"
pyenv install 3.10
pyenv global 3.10

# Setup executorch
git clone https://github.com/pytorch/executorch.git
cd executorch

# check out the v0.2.0 tag
git checkout 4f798326c6545a58ea958ce3b8fa21f109651747

git submodule sync
git submodule update --init

./install_requirements.sh --pybind xnnpack
```

**Comment by dbort** [comment]
Great! I'm glad that it's working @reganh98.

You might also try using the prebuilt pip package instead, to avoid installing executorch from source. I just set up an example notebook at https://colab.research.google.com/drive/1bHUJp0-FM5rhDR0azAUTuQ4lME0PFelA

This is something that we just got working before the release, and haven't had a chance to add to the docs yet.
