### ISSUE TITLE
ERROR in "cmake --build cmake-out-android/examples/models/llama2 -j16 --config Release"

### ISSUE THREAD

**Issue by sunqijie0350** [pytorch/executorch#3590]
ld.lld: error: unable to find library -lcpublas
ld.lld: error: unable to find library -leigen_blas

After executed the command as issue title, there are two errors reported, and I think these error are related to my environment.
How to resolve them? Thank you~

**Comment by sunqijie0350** [comment]
And when I get in /executorch/kernels/optimized executed "cmake CMakeList.txt", there is related errors ocurred:

CMake Error at CMakeLists.txt:44 (add_library):
  No SOURCES given to target: cpublas


CMake Error at CMakeLists.txt:60 (add_library):
  No SOURCES given to target: optimized_kernels


CMake Generate step failed.  Build files cannot be regenerated correctly.

**Comment by mergennachin** [comment]
Hi @sunqijie0350 

Have you gone through initial executorch setup steps here: 

https://pytorch.org/executorch/stable/getting-started-setup.html

Creating conda environment, updating gitsubmodules and calling `./install_requirements.sh`

**Comment by sunqijie0350** [comment]
> Hi @sunqijie0350
> 
> Have you gone through initial executorch setup steps here:
> 
> https://pytorch.org/executorch/stable/getting-started-setup.html
> 
> Creating conda environment, updating gitsubmodules and calling `./install_requirements.sh`

@mergennachin Yes, I did all things I can do in executorch setup steps. but there are still two errors, and other steps report no error.

**Comment by sunqijie0350** [comment]
$ cmake  -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake \
    -DANDROID_ABI=arm64-v8a \
    -DANDROID_PLATFORM=android-23 \
    -DCMAKE_INSTALL_PREFIX=cmake-out-android \
    -DCMAKE_BUILD_TYPE=Release \
    -DPYTHON_EXECUTABLE=python \
    -DEXECUTORCH_BUILD_KERNELS_OPTIMIZED=ON \
    -Bcmake-out-android/examples/models/llama2 \
    examples/models/llama2

cmake --build cmake-out-android/examples/models/llama2 -j16 --config Release
-- The C compiler identification is Clang 17.0.2
-- The CXX compiler identification is Clang 17.0.2
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /home/ufoe/SLMU-Public-Packages/Android-NDKs/android-ndk-r26c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /home/ufoe/SLMU-Public-Packages/Android-NDKs/android-ndk-r26c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
etdump library is not found.
            If needed rebuild with the proper options in CMakeLists.txt
bundled_program library is not found.
            If needed rebuild with the proper options in CMakeLists.txt
flatccrt library is not found.
            If needed rebuild with the proper options in CMakeLists.txt
mpsdelegate library is not found.
            If needed rebuild with the proper options in CMakeLists.txt
qnn_executorch_backend library is not found.
            If needed rebuild with the proper options in CMakeLists.txt
vulkan_backend library is not found.
            If needed rebuild with the proper options in CMakeLists.txt
optimized_kernels library is not found.
            If needed rebuild with the proper options in CMakeLists.txt
cpublas library is not found.
            If needed rebuild with the proper options in CMakeLists.txt
eigen_blas library is not found.
            If needed rebuild with the proper options in CMakeLists.txt
optimized_ops_lib library is not found.
            If needed rebuild with the proper options in CMakeLists.txt
optimized_native_cpu_ops_lib library is not found.
            If needed rebuild with the proper options in CMakeLists.txt
-- executorch: Using source file list /home/ufoe/qj.sun/et/test/executorch/cmake-out-android/examples/models/llama2/custom_ops/../../../../executorch_srcs.cmake
Command - python;-m;codegen.tools.gen_oplist;--output_path=/home/ufoe/qj.sun/et/test/executorch/cmake-out-android/examples/models/llama2/custom_ops/selected_operators.yaml;--ops_schema_yaml_path="/home/ufoe/qj.sun/et/test/executorch/examples/models/llama2/custom_ops/custom_ops.yaml"
-- Generating kernel bindings:
--   FUNCTIONS_YAML: /home/ufoe/qj.sun/et/test/executorch/examples/models/llama2/custom_ops/custom_ops.yaml
--   CUSTOM_OPS_YAML:
Generated files /home/ufoe/qj.sun/et/test/executorch/cmake-out-android/examples/models/llama2/custom_ops/RegisterCodegenUnboxedKernelsEverything.cpp;/home/ufoe/qj.sun/et/test/executorch/cmake-out-android/examples/models/llama2/custom_ops/Functions.h;/home/ufoe/qj.sun/et/test/executorch/cmake-out-android/examples/models/llama2/custom_ops/NativeFunctions.h
-- Generating operator lib:
--   LIB_NAME: custom_ops_lib
--   KERNEL_LIBS: custom_ops
--   DEPS: executorch
-- executorch: Using source file list /home/ufoe/qj.sun/et/test/executorch/cmake-out-android/examples/models/llama2/runner/../../../../executorch_srcs.cmake
--
-- ******** Summary ********
--   CMAKE_BUILD_TYPE              : Release
--   CMAKE_CXX_STANDARD            : 17
--   CMAKE_CXX_COMPILER_ID         : Clang
--   CMAKE_TOOLCHAIN_FILE          : /home/ufoe/SLMU-Public-Packages/Android-NDKs/android-ndk-r26c/build/cmake/android.toolchain.cmake
--   BUCK2                         :
--   PYTHON_EXECUTABLE             : python
--   FLATC_EXECUTABLE              :
--   EXECUTORCH_ENABLE_LOGGING              :
--   EXECUTORCH_ENABLE_PROGRAM_VERIFICATION :
--   EXECUTORCH_LOG_LEVEL                   :
--   EXECUTORCH_BUILD_ANDROID_JNI           :
--   EXECUTORCH_BUILD_ARM_BAREMETAL         :
--   EXECUTORCH_BUILD_COREML                :
--   EXECUTORCH_BUILD_CUSTOM                :
--   EXECUTORCH_BUILD_EXECUTOR_RUNNER       :
--   EXECUTORCH_BUILD_EXTENSION_DATA_LOADER :
--   EXECUTORCH_BUILD_EXTENSION_MODULE      :
--   EXECUTORCH_BUILD_EXTENSION_RUNNER_UTIL :
--   EXECUTORCH_BUILD_FLATC                 :
--   EXECUTORCH_BUILD_GFLAGS                :
--   EXECUTORCH_BUILD_GTESTS                :
--   EXECUTORCH_BUILD_HOST_TARGETS          :
--   EXECUTORCH_BUILD_MPS                   :
--   EXECUTORCH_BUILD_PYBIND                :
--   EXECUTORCH_BUILD_QNN                   :
--   EXECUTORCH_BUILD_OPTIMIZED             : OFF
--   EXECUTORCH_BUILD_QUANTIZED             :
--   EXECUTORCH_BUILD_SDK                   :
--   EXECUTORCH_BUILD_SIZE_TEST             :
--   EXECUTORCH_BUILD_XNNPACK               :
--   EXECUTORCH_BUILD_VULKAN                :
--   EXECUTORCH_BUILD_PTHREADPOOL           :
--   EXECUTORCH_BUILD_CPUINFO               :
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    EXECUTORCH_BUILD_KERNELS_OPTIMIZED


-- Build files have been written to: /home/ufoe/qj.sun/et/test/executorch/cmake-out-android/examples/models/llama2
[ 11%] Building CXX object custom_ops/CMakeFiles/custom_ops.dir/op_sdpa.cpp.o
[ 11%] Building CXX object custom_ops/CMakeFiles/custom_ops.dir/home/ufoe/qj.sun/et/test/executorch/backends/xnnpack/threadpool/threadpool.cpp.o
[ 16%] Building CXX object custom_ops/CMakeFiles/custom_ops.dir/home/ufoe/qj.sun/et/test/executorch/extension/parallel/thread_parallel.cpp.o
[ 22%] Building CXX object custom_ops/CMakeFiles/custom_ops.dir/home/ufoe/qj.sun/et/test/executorch/backends/xnnpack/threadpool/threadpool_guard.cpp.o
[ 27%] Linking CXX static library libcustom_ops.a
[ 27%] Built target custom_ops
[ 33%] Generating selected_operators.yaml for custom ops
[ 38%] Building CXX object runner/CMakeFiles/llama_runner.dir/__/sampler/sampler.cpp.o
[ 44%] Building CXX object runner/CMakeFiles/llama_runner.dir/home/ufoe/qj.sun/et/test/executorch/extension/evalue_util/print_evalue.cpp.o
[ 50%] Building CXX object runner/CMakeFiles/llama_runner.dir/home/ufoe/qj.sun/et/test/executorch/kernels/optimized/blas/CPUBlas.cpp.o
[ 55%] Building CXX object runner/CMakeFiles/llama_runner.dir/runner.cpp.o
[ 61%] Building CXX object runner/CMakeFiles/llama_runner.dir/__/tokenizer/tokenizer.cpp.o
[ 66%] Generating code for kernel registration
[ 72%] Building CXX object custom_ops/CMakeFiles/custom_ops_lib.dir/RegisterCodegenUnboxedKernelsEverything.cpp.o
[ 77%] Linking CXX static library libllama_runner.a
[ 77%] Built target llama_runner
[ 83%] Linking CXX static library libcustom_ops_lib.a
[ 83%] Built target custom_ops_lib
[ 88%] Building CXX object CMakeFiles/llama_main.dir/home/ufoe/qj.sun/et/test/executorch/backends/xnnpack/threadpool/cpuinfo_utils.cpp.o
[ 94%] Building CXX object CMakeFiles/llama_main.dir/main.cpp.o
[100%] Linking CXX executable llama_main
ld.lld: error: unable to find library -lcpublas
ld.lld: error: unable to find library -leigen_blas
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
gmake[2]: *** [CMakeFiles/llama_main.dir/build.make:129: llama_main] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:122: CMakeFiles/llama_main.dir/all] Error 2
gmake: *** [Makefile:91: all] Error 2

**Comment by GregoryComer** [comment]
This may be a submodule issue. Can you try running `git submodule update --init`?

**Comment by sunqijie0350** [comment]
> This may be a submodule issue. Can you try running ?`git submodule update --init`



> This may be a submodule issue. Can you try running ?`git submodule update --init`

yes, I have done all steps which in setup guide.

**Comment by sunqijie0350** [comment]
I run the steps successfully just now, the reason maybe caused by bad network speed, it caused some lib lost. 
I'm so sorry, Thank you~

**Comment by GregoryComer** [comment]
I'm glad it's working. Feel free to reach out if you hit any other issues. The build is still a bit fragile, so we'd love to fix anything else that comes up.
