### ISSUE TITLE
llama2 pte generated results are somewhat off from my prompt

### ISSUE THREAD

**Issue by CHNtentes** [pytorch/executorch#3634]
I used llama_main to test the result on both pc and android phone. Here's the result:

PC:
```
Could you tell me about Qualcomm's Snapdragon 800 series?
 nobody 100

The Snapdragon 800 series is a line of mobile processors developed by Qualcomm. These processors are designed for high-end smartphones and other mobile devices, and are known for their fast performance and advanced features.
Here are some key features of the Snapdragon 800 series:
1. Performance: The Snapdragon 800 series is based on ARMv8 architecture and is designed to provide fast performance for demand
```

Android:
```
Could you tell me about Qualcomm Life, Qualcomm's new subsidiary?
 situé in San Diego, California, Qualcomm Life is a new subsidiary of Qualcomm Incorporated, a leading provider of wireless technologies and services. Established in 2014, Qualcomm Life is focused on developing and commercializing wearable technologies and other health-related devices.
Qualcomm Life's main goal is to create products and services that can improve people's health and wellness by leveraging the power of wireless connectivity and data analytics. The company's initial
```

I'd say they are related to my prompt but do not follow very well. I also tried Nvidia, and got RTX 3070 and Geforce Now...

**Comment by salykova** [comment]
@CHNtentes 

I assume you are using Llama2 chat model. Instead of feeding only user input, try to use llama2 template for instructions
```
<s>[INST] <<SYS>> {{ system_prompt }} <</SYS>>\n\n {{ user_message }} [/INST]
```
P.S. you dont need  to type in `{{   }}`, these brackes are just for formatting

**Comment by CHNtentes** [comment]
@salykova 
Thanks! It seems adding chat template does solve the issue. There's another thing, when I pass "--seq_len 256" (or any number larger) it does not generate longer text. From output message it seems to read metadata from model to get max seq length. How can I modify this value? When use transformers I can just set it in config.json or pass max_new_tokens when generate.

**Comment by salykova** [comment]
@CHNtentes 

you can add ` --max_seq_len=x` when exporting a model, e.g.

`python -m examples.models.llama2.export_llama --checkpoint <checkpoint.pth> --params <params.json> -kv --use_sdpa_with_kv_cache -X -qmode 8da4w --group_size 128 -d fp32 --max_seq_len=x`
