### ISSUE TITLE
Question about qmode `8da4w` in example llama2

### ISSUE THREAD

**Issue by DzAvril** [pytorch/executorch#3717]
I am currently learning about the example llama2 by following the instructions provided in the [README](https://github.com/pytorch/executorch/blob/main/examples/models/llama2/README.md). In this example, the quantize mode specified is `8daw4`. From my understanding, this means that the activation values will be quantized to int8 during runtime, and the matrix multiplication computations will be performed using int8 data type.

However, upon reviewing the delegation info, I noticed that the activation values are first quantized to int8 and then de-quantized to fp32 (floating-point 32) format. In the end, these values are multiplied with weights that have also been de-quantized to fp32. I am puzzled as to why this process is carried out in this manner.

Could someone kindly explain the reasoning behind this process?
![image](https://github.com/pytorch/executorch/assets/18597737/74ff0a28-41e5-45cc-9a1a-6c3d5a69c789)

**Comment by feiyuvl** [comment]
I have the same question. It seems the final edge ir still using the fake quantize process, when does the real int convert pass happen?

**Comment by cccclai** [comment]
It happens during `to_backend()` stage https://github.com/pytorch/executorch/blob/main/examples/models/llama2/export_llama_lib.py#L447

the fake quantized model will be lowered to the quantized ops for the target backend

**Comment by DzAvril** [comment]
> It happens during `to_backend()` stage https://github.com/pytorch/executorch/blob/main/examples/models/llama2/export_llama_lib.py#L447
> 
> the fake quantized model will be lowered to the quantized ops for the target backend

Is the computation during runtime consistent with the information I provided earlier? This implies that the activation values will be quantized to int8 and then de-quantized back to fp32.

**Comment by feiyuvl** [comment]
> It happens during `to_backend()` stage https://github.com/pytorch/executorch/blob/main/examples/models/llama2/export_llama_lib.py#L447
> 
> the fake quantized model will be lowered to the quantized ops for the target backend

Thank you, the following code is a simple convolution layer after `to_backend`. Is there any way to see the  fully quantized graph, or it is a black box hidden in `executorch_call_delegate`?
```
ExportedProgram:
    class GraphModule(torch.nn.Module):
        def forward(self, arg2_1: "f32[1, 3, 100, 100]"):
            # No stacktrace found for following nodes
            lowered_module_0 = self.lowered_module_0
            executorch_call_delegate = torch.ops.higher_order.executorch_call_delegate(lowered_module_0, arg2_1);  lowered_module_0 = arg2_1 = None
            getitem: "f32[1, 16, 100, 100]" = executorch_call_delegate[0];  executorch_call_delegate = None
            return (getitem,)

```

**Comment by cccclai** [comment]
> Is the computation during runtime consistent with the information I provided earlier? This implies that the activation values will be quantized to int8 and then de-quantized back to fp32.

Maybe try this api to inspect the nodes delegated?

https://github.com/pytorch/executorch/blob/main/exir/backend/utils.py#L458
