### ISSUE TITLE
Profile issue with CoreML with MacOS Sonoma ver 14.5

### ISSUE THREAD

**Issue by fguzman82** [pytorch/executorch#3742]
Running the steps in: https://pytorch.org/executorch/stable/build-run-coreml.html

My setup:
MacOS version 14.5
Executorch version v0.2.0

After executing this step: 
cd executorch
# Generate the ETDump file.
./coreml_executor_runner --model_path mv3_coreml_all.pte --profile_model --etdump_path etdump.etdp

I got this error: 

❯ ./coreml_executor_runner --model_path mv3_coreml_all.pte --profile_model --etdump_path etdump.etdp
I 00:00:00.756852 executorch:main.mm:357] Load duration = 642.175417
I 00:00:00.756861 executorch:main.mm:360] Running method = forward
I 00:00:00.760939 executorch:main.mm:363] Inputs prepared.
E 00:00:00.760992 executorch:ETCoreMLModelProfiler.mm:297] ETCoreMLModelProfiler: Model profiling is only available for macOS >= 14.4, iOS >= 17.4, tvOS >= 17.4 and watchOS >= 10.4.
E 00:00:00.761003 executorch:ETCoreMLModelAnalyzer.mm:101] ETCoreMLModelAnalyzer: Model profiling is only available for macOS >= 14.4, iOS >= 17.4, tvOS >= 17.4 and watchOS >= 10.4.
E 00:00:00.761010 executorch:ETCoreMLModelProfiler.mm:297] ETCoreMLModelProfiler: Model profiling is only available for macOS >= 14.4, iOS >= 17.4, tvOS >= 17.4 and watchOS >= 10.4.
E 00:00:00.761014 executorch:ETCoreMLModelAnalyzer.mm:101] ETCoreMLModelAnalyzer: Model profiling is only available for macOS >= 14.4, iOS >= 17.4, tvOS >= 17.4 and watchOS >= 10.4.
[1]    2212 segmentation fault  ./coreml_executor_runner --model_path mv3_coreml_all.pte --profile_model
~/executorch #v0.2.0-rc5 ?1                                                                                                                          ✘
~/executorch #v0.2.0-rc5 ?1                                                                                            ✘ SEGV  executorch 04:17:5
❯ sw_vers

ProductName:		macOS
ProductVersion:		14.5
BuildVersion:		23F79

**Comment by cymbalrush** [comment]
@fguzman82 could you please check the Xcode version installed on the system? Profiling uses a new API (MLComputePlan) which shipped in Xcode 15.3 https://developer.apple.com/documentation/xcode-release-notes/xcode-15_3-release-notes .

**Comment by fguzman82** [comment]
Thank you, @cymbalrush. After updating to Xcode 15.4, as well as Xcode Command Line Tools, it is now working.
