### ISSUE TITLE
RuntimeError: Found a graph input that requires gradients, and received a mutation.

### ISSUE THREAD

**Issue by xmuhyperion** [pytorch/executorch#3753]
Hi,
I try to convert a pytorch model to the .pte model，but i got the error message:

![QQ图片20240528130458](https://github.com/pytorch/executorch/assets/116475981/a9b56ade-a183-45f4-a9d8-144561ed53a7)
Could you please tell me the reason why this problem occurs?

Thanks,
xmuhyperion

**Comment by iseeyuan** [comment]
@xmuhyperion Thanks for reporting the issue! Could you check your input tensors? All of them should have `requires_grad=False`.

**Comment by xmuhyperion** [comment]
@iseeyuan Thank you for taking time to answer my question. Thanks to your help, I have successfully resolved the issue.The cause of this problem is that my model parameters have the attribute:`requires_grad=True`.So, when i make changes to the code:
![QQ截图20240530164423](https://github.com/pytorch/executorch/assets/116475981/a1757752-3b12-41ac-923b-3cf269d0a4c4)

it works !!!
