### ISSUE TITLE
Buck2 version not updated

### ISSUE THREAD

**Issue by Jerry-Ge** [pytorch/executorch#3823]
What's the latest buck2 version used for executorch? I downloaded the 2024-02-15 version from the documentation here: https://pytorch.org/executorch/stable/getting-started-setup.html

But got the following error: 

```
CMake Error at build/Utils.cmake:237 (message):
  Failed to resolve buck2.

  The provided buck2 binary "/tmp/buck2" reports version
  "071372cfde6e9936c62eb92823742392af4a945570df5c5b34d3eed1b03813c3", but
  ExecuTorch needs version
  "3bbde7daa94987db468d021ad625bc93dc62ba7fcb16945cb09b64aab077f284".  Ensure
  that the correct buck2 version is installed or avoid explicitly passing the
  BUCK2 version to automatically download the correct version.

Call Stack (most recent call first):
  CMakeLists.txt:302 (resolve_buck2)
```

**Comment by mergennachin** [comment]
The main branch is actually updated to 2024-05-15. Here's the updated documentation

https://pytorch.org/executorch/main/getting-started-setup.html#optional-setting-up-buck2

**Comment by mergennachin** [comment]
Can you try that @Jerry-Ge ?

**Comment by Jerry-Ge** [comment]
Yes, thanks! That worked

**Comment by rabyunghwa** [comment]
https://pytorch.org/executorch/main/getting-started-setup.html#optional-setting-up-buck2 

The above link doesn't point to anything. What am I missing here?

**Comment by mergennachin** [comment]
@rabyunghwa you don't need to set up buck2 anymore. it downloads automatically underneath the hood during installation, so you don't need to worry about

**Comment by rabyunghwa** [comment]
@mergennachin Thanks for the reply. I got it working eventually.
