### ISSUE TITLE
Use `constant_prop_pass`

### ISSUE THREAD

**Issue by mhs4670go** [pytorch/executorch#3827]
Hello. I'm trying to use `constant_prop_pass` pass in my codes on exported program. But, seems that there is no place to use this function. Is there any reason for this? Or, are there any things to note to use this function?

Here's the module that I'm going to apply such function.

```python
class SimpleScalarTensor(torch.nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, x):
        y = torch.scalar_tensor(2.0)
        z = x + y
        return (z,)

    def get_example_inputs(self):
        return (torch.randn(3),)
```

```python
from executorch.exir.passes.constant_prop_pass import constant_prop_pass

# model =  torch.export.export(..)
module_edge = to_edge(model)
new_exported_program = constant_prop_pass(module_edge.exported_program())
```

Without the pass, `torch.ops.aten.scalar_tensor.default` op is remained, which makes it hard to do further compilation.
```bash
#### Without pass
ExportedProgram:
    class GraphModule(torch.nn.Module):
        def forward(self, x: "f32[3]"):
            scalar_tensor: "f32[]" = torch.ops.aten.scalar_tensor.default(2.0, device = device(type='cpu'), pin_memory = False)
            
            aten_add_tensor: "f32[3]" = executorch_exir_dialects_edge__ops_aten_add_Tensor(x, scalar_tensor);  x = scalar_tensor = None
            return (aten_add_tensor,)
            
Graph signature: ExportGraphSignature(input_specs=[InputSpec(kind=<InputKind.USER_INPUT: 1>, arg=TensorArgument(name='x'), target=None, persistent=None)], output_specs=[OutputSpec(kind=<OutputKind.USER_OUTPUT: 1>, arg=TensorArgument(name='aten_add_tensor'), target=None)])
Range constraints: {}

#### After pass
ExportedProgram:
    class GraphModule(torch.nn.Module):
        def forward(self, _prop_tensor_constant0: "f32[]", x: "f32[3]"):
            aten_add_tensor: "f32[3]" = executorch_exir_dialects_edge__ops_aten_add_Tensor(x, _prop_tensor_constant0);  x = _prop_tensor_constant0 = None
            return (aten_add_tensor,)
            
Graph signature: ExportGraphSignature(input_specs=[InputSpec(kind=<InputKind.CONSTANT_TENSOR: 4>, arg=TensorArgument(name='_prop_tensor_constant0'), target='_prop_tensor_constant0', persistent=True), InputSpec(kind=<InputKind.USER_INPUT: 1>, arg=TensorArgument(name='x'), target=None, persistent=None)], output_specs=[OutputSpec(kind=<OutputKind.USER_OUTPUT: 1>, arg=TensorArgument(name='aten_add_tensor'), target=None)])
Range constraints: {}
```

**Comment by mergennachin** [comment]
This test case has a way to call that pass https://github.com/pytorch/executorch/blob/main/exir/tests/test_passes.py#L1145

**Comment by angelayi** [comment]
Sorry, what does it mean, "there is no place to use this function"?
You are free to insert any passes between calls of `to_edge`, `to_backend`, and `to_executorch`.

**Comment by cccclai** [comment]
Is it because `constant_prop_pass` needs to take an `ExportedProgram` but the existing `transform` api only takes `GraphModule`?

**Comment by mhs4670go** [comment]
> Sorry, what does it mean, "there is no place to use this function"?

> Is it because constant_prop_pass needs to take an ExportedProgram but the existing transform api only takes GraphModule?

Ah, other passes seem to be used inside the executorch codes or backends' codes. But, this pass is not used anywhere except the test codes, which made me think this pass was under developed or had some problem. 

But, as you guys said, it is totally fine:) Thanks for the comments.

**Comment by cccclai** [comment]
> > Sorry, what does it mean, "there is no place to use this function"?
> 
> > Is it because constant_prop_pass needs to take an ExportedProgram but the existing transform api only takes GraphModule?
> 
> Ah, other passes seem to be used inside the executorch codes or backends' codes. But, this pass is not used anywhere except the test codes, which made me think this pass was under developed or had some problem.
> 
> But, as you guys said, it is totally fine:) Thanks for the comments.

Thanks for the context. Does the issue need extra action items and is it good to close?

**Comment by mhs4670go** [comment]
It's good to close. Thanks:)
