### ISSUE TITLE
[v0.3.0] Release Tracker

### ISSUE THREAD

**Issue by lucylq** [pytorch/executorch#3944]
The v0.3.0 release will be cut on 6/14, and released 7/24.

https://github.com/pytorch/executorch/tree/release/0.3

This issue is for tracking cherry-picks to the release branch.

## Cherry-Pick Criteria

Focus on stability and documentation correctness. Ideally only low risk changes may be cherry-picked from main:

1. Critical fixes in core components: [build](https://github.com/pytorch/executorch/tree/main/build), [exir](https://github.com/pytorch/executorch/tree/main/exir), [backends](https://github.com/pytorch/executorch/tree/main/backends), [runtime](https://github.com/pytorch/executorch/tree/main/runtime), [sdk](https://github.com/pytorch/executorch/tree/main/sdk)
2. Bug fixes in demos/examples. No new features/experiments
3. Critical bug fixes based on community feedback
4. Documentation improvements
5. Test/CI fixes
6. Release branch specific changes (e.g. change version identifiers)

Any core components changes and other change will require special dispensation from the release managers (currently  @kirklandsign, @lucylq). If this applies to your change please write "Special Dispensation" in the "Criteria Category:" template below and explain.

## Cherry-Pick Process

1. Ensure your PR has landed in master. This does not apply for release-branch specific changes (see Phase 1 criteria).
2. Create (but do not land) a PR against the release branch. 
   **Option 1**: Use `pytorchbot` to cherry pick a PR that has been committed to the main branch using `@pytorchbot cherry-pick` command as follows.
     
      ```
      @pytorchbot cherry-pick --onto release/0.3 -c {regression,critical,fixnewfeature,docs,release}
      ```
     
     <details>
     
      ```
      usage: @pytorchbot cherry-pick --onto ONTO [--fixes FIXES] -c
                               {regression,critical,fixnewfeature,docs,release}

      Cherry pick a pull request onto a release branch for inclusion in a release

      optional arguments:
        --onto ONTO           Branch you would like to cherry pick onto (Example: release/0.2)
        --fixes FIXES         Link to the issue that your PR fixes (i.e. https://github.com/pytorch/executorch/issues/2345)
        -c {regression,critical,fixnewfeature,docs,release}
                        A machine-friendly classification of the cherry-pick reason.
                        
      ```
      
      </details>
      
      **Option 2**: Manually create a cherry pick PR using git command as follows.
      <details>

      ```
      # Find the hash of the commit you want to cherry pick
      # (for example, abcdef12345)
      git log

      git fetch origin release/0.2
      git checkout release/0.2
      git cherry-pick -x abcdef12345

      # Submit a PR based against 'release/0.2' either:
      # via the GitHub UI
      git push my-fork

      # via the GitHub CLI
      gh pr create --base release/0.2
      
      ```
      
      </details>

3. Make a request below with the following format:

```
Link to landed trunk PR:
* 

Link to release branch PR:
* 

Criteria category and reasons:
* 
```

1. Someone from the release team will reply with approved / denied or ask for more information.
2. If approved, someone from the release team will merge your PR once the tests pass. **Do not land the release branch PR yourself.**

Please note HUD Link with branch CI status and link to the HUD to be provided here.
HUD 
https://hud.pytorch.org/hud/pytorch/executorch/release%2F0.3/0?per_page=50

### Versions

0.3.0

**Comment by Gasoonjia** [comment]
Link to landed trunk PR:
* https://github.com/pytorch/executorch/pull/3982

Link to release branch PR:
* https://github.com/pytorch/executorch/pull/4004

Criteria category and reasons:
* Migrate dim order issues by temporary close it.

**Comment by mergennachin** [comment]
Link to landed trunk PR:
* https://github.com/pytorch/executorch/pull/3896

Link to release branch PR:
* https://github.com/pytorch/executorch/pull/4017

Criteria category and reasons:
* This will be a good change to land in the upcoming July release (0.3) as it enables downloading buck for Linux aarch64 platforms.

**Comment by dbort** [comment]
Link to landed trunk PR:
* https://github.com/pytorch/executorch/pull/4107

Link to release branch PR:
* https://github.com/pytorch/executorch/pull/4153

Criteria category and reasons:
* Docs-only change to add more information to CONTRIBUTING.md, and to make it easier to find that file.

**Comment by kirklandsign** [comment]
[Placeholder for https://github.com/pytorch/executorch/pull/4356]

**Comment by kirklandsign** [comment]
Placeholder for https://github.com/pytorch/executorch/pull/4362

**Comment by kirklandsign** [comment]
Release branch only: https://github.com/pytorch/executorch/pull/4379

**Comment by kirklandsign** [comment]
Release branch only for Apple artifacts:
https://github.com/pytorch/executorch/pull/4381

**Comment by kirklandsign** [comment]
Link to landed trunk PR:
* https://github.com/pytorch/executorch/pull/4406

Link to release branch PR:
* https://github.com/pytorch/executorch/pull/4407

Criteria category and reasons:
* Docs
