### ISSUE TITLE
QNN: failed to specified config SOC

### ISSUE THREAD

**Issue by zhouwg** [pytorch/executorch#3949]
I have a Qualcomm SnapDragon 8 Gen 3 equipped Android phone and trying run QNN SDK(/opt/qcom/aistack/qairt/2.23.0.240531) on this Android phone, I found there are two strange questions:

1.failed to specified config SoC
```
[qnn_init, 1114]: qualcomm soc_model:57(SM8650), htp_arch:75(QCOM_HTP_V75), vtcm_size:8 MB
[qnn_sdk_logcallback, 874]:      0.0ms [INFO   ]  <I> QnnDevice_freePlatformInfo started


[qnn_sdk_logcallback, 874]:      0.0ms [INFO   ]  <I> QnnDevice_freePlatformInfo done. status 0x0


[qnn_sdk_logcallback, 874]:      0.0ms [INFO   ]  <I> QnnDevice_create started


[qnn_sdk_logcallback, 874]:      0.0ms [VERBOSE]  <V> Create device with id 0x1


[qnn_sdk_logcallback, 874]:      0.0ms [VERBOSE]  <V> Validating device config 0x7fcdd70b10


[qnn_sdk_logcallback, 874]:      0.0ms [VERBOSE]  <V> Setting device config 0x7fcdd70b10 via router


[qnn_sdk_logcallback, 874]:      0.0ms [WARNING]  <W> Specified config SOC, ignoring on real target


[qnn_sdk_logcallback, 874]:      0.0ms [VERBOSE]  <V> Validating device config 0x7fcdd70af0


[qnn_sdk_logcallback, 874]:      0.0ms [VERBOSE]  <V> Setting device config 0x7fcdd70af0 via router


[qnn_sdk_logcallback, 874]:      0.0ms [WARNING]  <W> HTP arch will be deprecated, please set SoC id instead.

```

2. why a simple QNN_OP_ELEMENT_WISE_ADD operation cost 53 ms?

```
[ggml_qnn_add, 2163]: create qnn graph handle with graph name ggml_op_qnn_add_4_tensor_0_tensor_1 ok

[ggml_qnn_add, 2220]: alloc rpcmem successfully

[register_rpcmem, 1645]: mem_fd 24

[register_rpcmem, 1662]: tensor tensor_0000 successfully register shared memory

[ggml_qnn_add, 2229]: alloc rpcmem successfully

[register_rpcmem, 1645]: mem_fd 25

[register_rpcmem, 1662]: tensor tensor_0001 successfully register shared memory

[ggml_qnn_add, 2238]: alloc rpcmem successfully

[register_rpcmem, 1645]: mem_fd 26

[register_rpcmem, 1662]: tensor tensor_0002 successfully register shared memory

[info, 511]: duration of ggml_qnn_add : 53436 microseconds

[qnn_op_ut, 2037]: dump tensors:
[tensor_dump, 1404]: dump ggml tensor src0(tensor_0): type = 0 (  f32) ne =     4 x     4 x     1, nb = (    4,    16,    64)
[tensor_dump, 1466]: (4x4 in 4x4)
    0.75    -0.35    -0.30     0.44 
    0.19     0.66     0.11     0.17 
    0.98     0.05    -0.93    -0.33 
   -0.42     0.02    -0.93     0.56 

[tensor_dump, 1404]: dump ggml tensor src1(tensor_1): type = 0 (  f32) ne =     4 x     4 x     1, nb = (    4,    16,    64)
[tensor_dump, 1466]: (4x4 in 4x4)
   -0.68    -0.87     0.09     0.49 
    0.15    -0.56    -0.53    -0.78 
   -0.72     0.31     0.14     0.43 
    0.64    -0.53     0.07     0.59 

[tensor_dump, 1404]: dump ggml tensor dst(tensor_2): type = 0 (  f32) ne =     4 x     4 x     1, nb = (    4,    16,    64)
[tensor_dump, 1466]: (4x4 in 4x4)
    0.07    -1.22    -0.21     0.93 
    0.34     0.10    -0.42    -0.61 
    0.26     0.35    -0.80     0.11 
```

Could anyone technical expert from QTI help to explain why these happend? thanks so much.

**Comment by digantdesai** [comment]
Did you try ExecuTorch delegate? https://github.com/pytorch/executorch/tree/main/backends/qualcomm

**Comment by zhouwg** [comment]
thanks for your response. 

deploy ExecuTorch on android is not a easy thing and I hasn't try that. could you help to explain what's a special approach was used in ExecuTorch with QNN API?

**Comment by digantdesai** [comment]
Check out ExecuTorch Android demo app which can leverage QNN - https://pytorch.org/executorch/stable/demo-apps-android.html

**Comment by zhouwg** [comment]
Thanks so much for you guidance. I'm trying the ExecuTorch on Android but failed in dev envs setup stage cause of GFW. I'll try check out ExecuTorch Android demo app accordingly after fix that issue on my side.

Thanks again.

**Comment by chiwwang** [comment]
@zhouwg  you need to set HTP precision custom configuration to fp16 to get a reasonable floating point performance.
Your case looks like a fp3 addition and HTP doens't offically support it.

And you can see this tracee
```
[qnn_sdk_logcallback, 874]:      0.0ms [WARNING]  <W> Specified config SOC, ignoring on real target
```

QNN ignore SOC configuration because the program runs on a real target.... QNN is able to detect it.


mmm but I'm not sure if ExecuTorch repository is a correct place to ask QNN questions.
You might want to check Quallcomm QPM forum instead.

**Comment by zhouwg** [comment]
> @zhouwg you need to set HTP precision custom configuration to fp16 to get a reasonable floating point performance. Your case looks like a fp3 addition and HTP doens't offically support it.
> 
> And you can see this tracee
> 
> ```
> [qnn_sdk_logcallback, 874]:      0.0ms [WARNING]  <W> Specified config SOC, ignoring on real target
> ```
> 
> QNN ignore SOC configuration because the program runs on a real target.... QNN is able to detect it.
> 
> mmm but I'm not sure if ExecuTorch repository is a correct place to ask QNN questions. You might want to check Quallcomm QPM forum instead.

Thanks so much for you helps me again. I'll try.

I'm sorry for that and I'll submit ticket in Qualcomm's QPM forum next time.

**Comment by zhouwg** [comment]
> @zhouwg you need to set HTP precision custom configuration to fp16 to get a reasonable floating point performance. Your case looks like a fp3 addition and HTP doens't offically support it.
> 
> And you can see this tracee
> 
> ```
> [qnn_sdk_logcallback, 874]:      0.0ms [WARNING]  <W> Specified config SOC, ignoring on real target
> ```
> 
> QNN ignore SOC configuration because the program runs on a real target.... QNN is able to detect it.
> 
> mmm but I'm not sure if ExecuTorch repository is a correct place to ask QNN questions. You might want to check Quallcomm QPM forum instead.

Thanks so much for helps me again.

I'm sorry for that and I'll submit ticket in Qualcomm's QPM forum next time.

**Comment by chiwwang** [comment]
Thanks. Or you can ping me in GGML pull-requests. ( from the trace `[ggml_qnn_add, 2229]` I guess you're doing ggml things)

**Comment by zhouwg** [comment]
> Thanks. Or you can ping me in GGML pull-requests. ( from the trace `[ggml_qnn_add, 2229]` I guess you're doing ggml things)

thanks. we can discuss this problem in my personal learning&study project. I'm blocked by the ggml community.
