### ISSUE TITLE
string input support?

### ISSUE THREAD

**Issue by soulx0** [pytorch/executorch#3992]
similar to  [: https://github.com/tensorflow/tensorflow/issues/21213](https://github.com/pytorch/pytorch/issues/74669)

and how tflite does: https://github.com/tensorflow/tensorflow/issues/21213

could executorch do better on string inputs?

**Comment by guangy10** [comment]
To make it supported in ExecuTorch I think it needs to be supported in the upstream PyTorch first. I'm not sure if we have a plan to support this feature request. @iseeyuan may know.

**Comment by cbilgin** [comment]
@dbort since Martin is out, any ideas on this one?

**Comment by dbort** [comment]
Asking about this [internally](https://fburl.com/workplace/9nfu1mb1). Like Martin said, EValue doesn't support String, so I don't expect we'd have first-class support.

The alternative is to provide some kind of wrapper to turn the string into a Tensor, but that will result in either a fully-dynamic-shaped input or an upper-bounded and padded input.

**Comment by dbort** [comment]
@soulx0 do you have a specific use case for this? There are a bunch of trade-offs, so it would help us understand the possible solutions.

**Comment by dbort** [comment]
Closing because we have no plans do to this in the near future. The first step would probably require changes on the pytorch/pytorch export side.
