### ISSUE TITLE
[FEATURE REQUEST] GGUF inputs

### ISSUE THREAD

**Issue by rcontesti** [pytorch/executorch#4006]
Llama.cpp has proven quite convininent for many of us, I wish you could add the possibility of taking those models as inputs. Many thanks!

**Comment by mergennachin** [comment]
@rcontesti - we have a work-in-progress prototype to convert fp16/fp32 version of llama

https://github.com/pytorch/executorch/tree/main/extension/gguf_util

**Comment by rcontesti** [comment]
Once again many thanks @mergennachin
