### ISSUE TITLE
Partially delegate a model to the QNN backend

### ISSUE THREAD

**Issue by leigao97** [pytorch/executorch#4082]
Can we partially delegate a model to the QNN backend? For example, delegate supported operators to QNN and unsupported ones to portable kernel library. I read the Vulkan backend tutorial, and it seems like it is doing partially delegation through the Vulkan Partitioner. Can you please point me how to achieve this?

**Comment by cccclai** [comment]
`QNNPartitioner` has the option to exclude some ops if needed https://github.com/pytorch/executorch/blob/main/backends/qualcomm/partition/qnn_partitioner.py#L104-L105

**Comment by leigao97** [comment]
Thank you. Just to confirm, the excluded ops will be linked to the protable kernel library, right?

**Comment by cccclai** [comment]
yes, excluded ops will fall back to the portable kernel library

**Comment by leigao97** [comment]
Thank you. The skip ops option works.
