### ISSUE TITLE
Is there example for running model with Quantization with Vulkan GPU ?

### ISSUE THREAD

**Issue by Andrechang** [pytorch/executorch#4199]
Is there example for running quantized model with Vulkan GPU ?

**Comment by lucylq** [comment]
cc @SS-JIA for Vulkan?

**Comment by SS-JIA** [comment]
Hello @Andrechang so we are currently only starting out supporting quantized models in the Vulkan backend. Unfortunately we don't have a complete end to end example working yet. The current status is:

* We can currently support 8-bit tensors in the Vulkan backend
* We have an implementation of an [weight only 8-bit quantized linear op](https://github.com/pytorch/executorch/blob/main/backends/vulkan/runtime/graph/ops/impl/QuantizedLinear.cpp)
  * Note this operator has not yet been hooked up to model export yet
  
Some remaining components are:

* Adding a `VulkanQuantizer()` to enable export of quantized models
* Implementation of additional quantized operators such as quantized convolution

We will be focusing on improving support for quantization over the next few months, so stay tuned!
