### ISSUE TITLE
LLAMA Runner with QNN Build Failure in Recent Push

### ISSUE THREAD

**Issue by mattsbryson** [pytorch/executorch#4201]
### 🐛 Describe the bug

A recent update to main (within this month) has introduced a bug in the build process for the AOT components of the LLAMA runner with the QNN flag turned on. This bug was produced on 561c035af5d6b64cd74defd8aea96b94f84af6f1 (head). Rolling back to a late June commit solves this particular issue. 

executorch/backends/qualcomm/runtime/QnnManager.cpp:324:18: error: no member named 'is_from_context_binary' in 'qnn_delegate::QnnExecuTorchOptions'
  if (!options_->is_from_context_binary()) {
       ~~~~~~~~  ^
executorch/backends/qualcomm/runtime/QnnManager.cpp:348:18: error: no member named 'is_from_context_binary' in 'qnn_delegate::QnnExecuTorchOptions'
  if (!options_->is_from_context_binary())

### Versions

Vulnerability Meltdown:             Mitigation; PTI
Vulnerability Mmio stale data:      Unknown: No mitigations
L1i cache:                          512 KiB
L2 cache:                           4 MiB
L3 cache:                           40 MiB
NUMA node0 CPU(s):                  0-7,16-23
NUMA node1 CPU(s):                  8-15,24-31
Vulnerability Gather data sampling: Not affected
Vulnerability Itlb multihit:        KVM: Mitigation: Split huge pages
Vulnerability L1tf:                 Mitigation; PTE Inversion; VMX conditional cache flushes, SMT vulnerable
Vulnerability Mds:                  Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Meltdown:             Mitigation; PTI
Vulnerability Mmio stale data:      Unknown: No mitigations
Vulnerability Retbleed:             Not affected
Vulnerability Spec store bypass:    Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:           Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:           Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIBP conditional, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:                Not affected
Vulnerability Tsx async abort:      Not affected
Flags:                              fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx lahf_lm epb pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid xsaveopt dtherm ida arat pln pts md_clear flush_l1d

Versions of relevant libraries:
[pip3] executorch==0.3.0a0+7c0f4c2
[pip3] numpy==1.26.4
[pip3] torch==2.5.0.dev20240618+cpu
[pip3] torchao==0.1
[pip3] torchaudio==2.4.0.dev20240618+cpu
[pip3] torchsr==1.0.4
[pip3] torchvision==0.20.0.dev20240618+cpu
[conda] executorch                0.3.0a0+7c0f4c2          pypi_0    pypi
[conda] numpy                     1.26.4                   pypi_0    pypi
[conda] torch                     2.5.0.dev20240618+cpu          pypi_0    pypi
[conda] torchao                   0.1                      pypi_0    pypi
[conda] torchaudio                2.4.0.dev20240618+cpu          pypi_0    pypi
[conda] torchsr                   1.0.4                    pypi_0    pypi
[conda] torchvision               0.20.0.dev20240618+cpu          pypi_0    pypi

**Comment by lucylq** [comment]
@cccclai do you mind taking a look at this?

**Comment by cccclai** [comment]
That's like from https://github.com/pytorch/executorch/pull/4142

Can you rebuild the library and try again?

**Comment by mattsbryson** [comment]
Thanks for your help! I tried to rebuild on the latest commit to main, but got the same build error. In case they're useful, here are my build steps. 

1. Build AOT libs: 
    
    cmake -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake \
        -DANDROID_ABI=arm64-v8a \
        -DANDROID_PLATFORM=android-23 \
        -DCMAKE_INSTALL_PREFIX=cmake-out-android \
        -DCMAKE_BUILD_TYPE=Release \
        -DEXECUTORCH_BUILD_EXTENSION_MODULE=ON \
        -DEXECUTORCH_BUILD_EXTENSION_DATA_LOADER=ON \
        -DEXECUTORCH_ENABLE_LOGGING=1 \
        -DPYTHON_EXECUTABLE=python \
        -DEXECUTORCH_BUILD_XNNPACK=ON \
        -DEXECUTORCH_BUILD_KERNELS_OPTIMIZED=ON \
        -DEXECUTORCH_BUILD_KERNELS_QUANTIZED=OFF \
        -DEXECUTORCH_BUILD_KERNELS_CUSTOM=ON \
        -DEXECUTORCH_BUILD_QNN=ON \
        -DQNN_SDK_ROOT=$QNN_SDK_ROOT \
        -Bcmake-out-android .


2. Hack this into the cmake cache file: 

echo "QNN_SDK_ROOT=$QNN_SDK_ROOT" >> /scratch/executorch/CMakeCache.txt 

3. Build libraries

cmake --build cmake-out-android -j16 --target install --config Release 

4. Build runner:
    
    cmake  -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake \
        -DANDROID_ABI=arm64-v8a \
        -DANDROID_PLATFORM=android-23 \
        -DCMAKE_INSTALL_PREFIX=cmake-out-android \
        -DCMAKE_BUILD_TYPE=Release \
        -DPYTHON_EXECUTABLE=python \
        -DEXECUTORCH_BUILD_XNNPACK=OFF \
        -DEXECUTORCH_BUILD_KERNELS_OPTIMIZED=ON \
        -DEXECUTORCH_BUILD_KERNELS_QUANTIZED=OFF \
        -DEXECUTORCH_BUILD_KERNELS_CUSTOM=ON \
        -DEXECUTORCH_USE_TIKTOKEN=ON \
        -DEXECUTORCH_BUILD_QNN=ON \
        -Bcmake-out-android/examples/models/llama2 \
        examples/models/llama2

cmake --build cmake-out-android/examples/models/llama2 -j16 --config Release

**Comment by chiwwang** [comment]
Hi @mattsbryson ,
I tried around and it seems this error can occur if we don't cleanup cmake folder after updating codebase.
Could you try a fresh build please?

**Comment by mattsbryson** [comment]
Thanks, that did the trick! My apologizes for not trying that this time - I had with other build errors, but perhaps not this one.
