### ISSUE TITLE
UNSTABLE Build M1 Wheels / pytorch/executorch / upload / wheel-py3_9-cpu

### ISSUE THREAD

**Issue by dbort** [pytorch/executorch#4309]
> Please provide a brief reason on why you need to mark this job as unstable.

ET doesn't currently support python 3.9

**Comment by huydhn** [comment]
I landed https://github.com/pytorch/executorch/pull/7064 few days ago to allow the team to choose which python version to support, so we can turn off 3.9 build now.  Keeping this issue open is not needed anymore.
