### ISSUE TITLE
[coreml][sdk] Add intermediate tensor logging for the coreml

### ISSUE THREAD

**Issue by cccclai** [pytorch/executorch#4323]
### 🚀 Add intermediate tensor logging for the coreml

The infra side to add intermediate tensor logging is landed. Related PRS: https://github.com/pytorch/executorch/pull/3822 https://github.com/pytorch/executorch/pull/4293

This issue is created to track adding intermediate tensor logging support inside coreml delegate

**Comment by cymbalrush** [comment]
PR - https://github.com/pytorch/executorch/pull/4557

**Comment by cymbalrush** [comment]
Changes are merged.
