### ISSUE TITLE
Running Demo Deeplab Model with XNNpack Backend on Android  Fails with Linking Error

### ISSUE THREAD

**Issue by nbansal90** [pytorch/executorch#4384]
### 🐛 Describe the bug

I am trying to run the ExecuTorch  (for Deeplab) using the step-to-step guidance mentioned at [https://pytorch.org/executorch/stable/demo-apps-android.html#build](url).

**Running Information:**
Device: Samsung S24+, 8GB RAM
Pytorch: 2.3.1+cpu
Android SDK API Level 34
Android NDK 27.0.12077973

**Error Received(on Running on Android Studio)**:
```Java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZTVNSt6__ndk119basic_ostringstreamIcNS_11char_traitsIcEENS_9allocatorIcEEEE" referenced by "/data/app/~~3SZuMtdvMV2io9R0EEbJcA==/com.example.executorchdemo-tBRqisQu2gYzB_hfiEMqew==/lib/arm64/libexecutorch.so"...```

**Steps to Reproduce**
Replicated all the steps mentioned at the Link  [https://pytorch.org/executorch/stable/demo-apps-android.html#build](url)

**Added .so file at jniLibs**
![Screenshot from 2024-07-23 16-46-33](https://github.com/user-attachments/assets/fdffda2d-b54f-4750-bcd7-9fb74730f48c)

Not sure why it is not able to find the `.so` file and run the app correctly.

### Versions

**Running Information:**
Device: Samsung S24+, 8GB RAM
Pytorch: 2.3.1+cpu
Android SDK API Level 34
Android NDK 27.0.12077973

**Comment by larryliu0820** [comment]
@kirklandsign Can you take a look? From the look of it it seems like an ABI incompatibility issue

**Comment by kirklandsign** [comment]
Hi @nbansal90 thank you for reporting the issue. We have seen this kind of issue before, but we don't know the root cause yet. Seems that something with libc is not linked correctly. As a workaround, reclone the git repo from stratch should fix the issue.

**Comment by nbansal90** [comment]
@kirklandsign Which repo are you suggesting to reclone? Do you mean the ExecuTorch repository ? Just to mention all the (sub) steps mentioned at the link  [https://pytorch.org/executorch/stable/demo-apps-android.html#build](https://github.com/pytorch/executorch/issues/url). were successfully executed.

**Comment by kirklandsign** [comment]
> @kirklandsign Which repo are you suggesting to reclone? Do you mean the ExecuTorch repository ? Just to mention all the (sub) steps mentioned at the link [https://pytorch.org/executorch/stable/demo-apps-android.html#build](https://github.com/pytorch/executorch/issues/url). were successfully executed.

Yes, I mean executorch repo. I got similar reports and they mentioned that re-cloning the repo and setting up again from a clean state eliminated the issue.

**Comment by nbansal90** [comment]
Recloning fixes the issue. Thank you
