### ISSUE TITLE
Why not directly use Google/XNNPACK as a third-party solution?

### ISSUE THREAD

**Issue by DzAvril** [pytorch/executorch#4663]
The XNNPACK used in this project is a forked version of the original Google/XNNPACK repository. However, the forked repo is significantly behind in commits compared to the original. I was wondering what the reason for this is.

**Comment by digantdesai** [comment]
We are in the process of upstreaming some logic to Google/XNNPACK. Once merged, we intend to migrate to upstream XNNPACK.
