### ISSUE TITLE
aten::scatter.src_out missing from baseline cross-platform kernels

### ISSUE THREAD

**Issue by awgr** [pytorch/executorch#4742]
### Error Message
```
E 00:00:25.912566 executorch:method.cpp:540] Missing operator: [16] aten::scatter.src_out
E 00:00:25.935731 executorch:method.cpp:728] There are 1 instructions don't have corresponding operator registered. See logs for details
```

### Details
**Summary**
I exported a model by lowering it from torch -> aten -> edge -> executorch.
This export completed successfully.

After compiling and running the model, I discovered that the default cross-platform operator kernels do not include a kernel that appears to be in the compute graph of my model.

**Resolution attempts**
I attempted to delegate subgraphs to XNNPack, hoping that the subgraph including aten::scatter.src_out might be delegated. Unfortunately, the XNNPack partitioner was unable to complete an SDPA pass for my model, which appears to be a separate, unrelated bug.

**Additional notes**
I exported the aten compute graph for my model to a text file. I was surprised to see that it did not appear to include this operator. I had expected the missing operator to be included in the aten compute graph. I will attach the file. You can view it with `less -R file_name`

### Versions

notes:
the executorch version is 15815dd5cd58b6d250dc98f8a4b121c77c44dbed

```
Collecting environment information...
PyTorch version: 2.5.0.dev20240716
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 14.5 (arm64)
GCC version: Could not collect
Clang version: 15.0.0 (clang-1500.3.9.4)
CMake version: version 3.30.1
Libc version: N/A

Python version: 3.12.4 (main, Jun  6 2024, 18:26:44) [Clang 15.0.0 (clang-1500.3.9.4)] (64-bit runtime)
Python platform: macOS-14.5-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M3 Max

Versions of relevant libraries:
[pip3] executorch==0.4.0a0+15815dd
[pip3] numpy==1.26.4
[pip3] torch==2.5.0.dev20240716
[pip3] torchaudio==2.4.0.dev20240716
[pip3] torchsr==1.0.4
[pip3] torchvision==0.20.0.dev20240716
[conda] Could not collect
```

**Comment by manuelcandales** [comment]
> I was surprised to see that it did not appear to include this operator.

We don't yet have full coverage. We are currently at around 90% Core ATen op coverage, and this is one of the 10% Core ATen ops we haven't implemented yet in the portable library. I am adding this op to my list of priorities, based on this request. However, there are other ops in that list already. It might take me a few weeks before I get to this one.

**Comment by awgr** [comment]
Sorry, I realize I miscommunicated there. I meant I was surprised to not see the operator represented in the printed out compute graph, because I had thought the printed out compute graph would contain a reference to every operator that the compiled binary would include.

**Comment by awgr** [comment]
Is there a way to identify which part of the torch code is lowering to this operator, so I can change it?

**Comment by manuelcandales** [comment]
Added scatter.src_out to the Portable Lib https://github.com/pytorch/executorch/pull/5037
