### ISSUE TITLE
Encountering Error while building Executorch on QNN Backend

### ISSUE THREAD

**Issue by nbansal90** [pytorch/executorch#4776]
### 🐛 Describe the bug

I am trying to build and run the Executorch model for the QNN backend as described in the link [https://pytorch.org/executorch/stable/build-run-qualcomm-ai-engine-direct-backend.html](url).

I am particularly getting error while building `qnn_executor_runner` for Android, while using the command:

> cmake .. \
    -DCMAKE_INSTALL_PREFIX=$PWD \
    -DEXECUTORCH_BUILD_SDK=ON \
    -DEXECUTORCH_BUILD_QNN=ON \
    -DQNN_SDK_ROOT=$QNN_SDK_ROOT \
    -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake \
    -DANDROID_ABI='arm64-v8a' \
    -DANDROID_NATIVE_API_LEVEL=23 \
    -B$PWD
    
  The error I am receiving is:
  

> In file included from /home/n.bansal1/utils/executorch/runtime/executor/tensor_parser_portable.cpp:9:
In file included from /home/n.bansal1/utils/executorch/../executorch/runtime/executor/tensor_parser.h:15:
/home/n.bansal1/utils/executorch/build_android/schema/include/executorch/schema/program_generated.h:11:15: error: static assertion failed due to requirement '24 == 23': Non-compatible flatbuffers version included
   11 | static_assert(FLATBUFFERS_VERSION_MAJOR == 23 &&
      |               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/n.bansal1/utils/executorch/schema/../third-party/flatbuffers/include/flatbuffers/base.h:142:35: note: expanded from macro 'FLATBUFFERS_VERSION_MAJOR'
  142 | #define FLATBUFFERS_VERSION_MAJOR 24
      |                                   ^
In file included from /home/n.bansal1/utils/executorch/runtime/executor/tensor_parser_portable.cpp:9:
In file included from /home/n.bansal1/utils/executorch/../executorch/runtime/executor/tensor_parser.h:15:
In file included from /home/n.bansal1/utils/executorch/build_android/schema/include/executorch/schema/program_generated.h:16:
/home/n.bansal1/utils/executorch/build_android/schema/include/executorch/schema/scalar_type_generated.h:11:15: error: static assertion failed due to requirement '24 == 23': Non-compatible flatbuffers version included
   11 | static_assert(FLATBUFFERS_VERSION_MAJOR == 23 &&
      |               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/n.bansal1/utils/executorch/schema/../third-party/flatbuffers/include/flatbuffers/base.h:142:35: note: expanded from macro 'FLATBUFFERS_VERSION_MAJOR'
  142 | #define FLATBUFFERS_VERSION_MAJOR 24

I am not quite able to resolve this issue.

### Versions

NDK Version Installed: 27.0.11902837
QNN SDK Installed: 2.25.0.240728
Python: 3.10.0
Ubuntu: 22.04.4 LTS

**Comment by digantdesai** [comment]
@cccclai - I guess we need `-DANDROID_NATIVE_API_LEVEL=23` and won't work with 24? Perhaps related to #3966?

**Comment by nbansal90** [comment]
@digantdesai @cccclai. Is this a known issue. Do we have a workaround for now ?

**Comment by nbansal90** [comment]
@digantdesai @cccclai do we have a workaround for this issue ?

**Comment by shewu-quic** [comment]
According to the following error message, it seems the version of flatbuffer doesn't match.
```
/home/n.bansal1/utils/executorch/build_android/schema/include/executorch/schema/program_generated.h:11:15: error: static assertion failed due to requirement '24 == 23': Non-compatible flatbuffers version included
```

Could you help to check the version of flatc?
```bash
third-party/flatbuffers/cmake-out/flatc --version
# Or use the following script to check
build/install_flatc.sh
```

**Comment by cccclai** [comment]
@nbansal90 does `./install_requirements.sh` work for you? Just want to check executorch without QNN can be built to narrow down the issue.
