### ISSUE TITLE
phi-3-mini export "Missing out variants"

### ISSUE THREAD

**Issue by JLake310** [pytorch/executorch#4832]
### 🐛 Describe the bug

Hi there,

First of all, I appreciate for the amazing work you've done on this project.
I wanted to bring up an issue I've encountered while converting phi-3-mini.

I followed instructions in [README](https://github.com/pytorch/executorch/blob/main/examples/models/phi-3-mini/README.md), and I've got the error below when tried to do Step 2.

```bash
$ python -m examples.models.phi-3-mini.export_phi-3-mini -c "4k" -s 128 -o phi-3-mini.pte

Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:23<00:00, 11.67s/it]
The 'max_batch_size' argument of ETStaticCache is deprecated and will be removed in v4.46. Use the more precisely named 'batch_size' argument instead.
W0822 10:58:40.673562 25903 torch/_export/__init__.py:65] +============================+
W0822 10:58:40.675322 25903 torch/_export/__init__.py:66] |     !!!   WARNING   !!!    |
W0822 10:58:40.675351 25903 torch/_export/__init__.py:67] +============================+
W0822 10:58:40.675369 25903 torch/_export/__init__.py:68] capture_pre_autograd_graph() is deprecated and doesn't provide any function guarantee moving forward.
Traceback (most recent call last):
  File "/Users/jaeyeonkim/miniconda3/envs/executorch/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/jaeyeonkim/miniconda3/envs/executorch/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/jaeyeonkim/Desktop/newest/executorch/examples/models/phi-3-mini/export_phi-3-mini.py", line 120, in <module>
    main()
  File "/Users/jaeyeonkim/Desktop/newest/executorch/examples/models/phi-3-mini/export_phi-3-mini.py", line 116, in main
    export(parser.parse_args())
  File "/Users/jaeyeonkim/Desktop/newest/executorch/examples/models/phi-3-mini/export_phi-3-mini.py", line 87, in export
    et_program = edge_manager.to_executorch()
  File "/Users/jaeyeonkim/miniconda3/envs/executorch/lib/python3.10/site-packages/executorch/exir/program/_program.py", line 1238, in to_executorch
    new_gm_res = p(new_gm)
  File "/Users/jaeyeonkim/miniconda3/envs/executorch/lib/python3.10/site-packages/torch/fx/passes/infra/pass_base.py", line 41, in __call__
    res = self.call(graph_module)
  File "/Users/jaeyeonkim/miniconda3/envs/executorch/lib/python3.10/site-packages/executorch/exir/passes/__init__.py", line 425, in call
    raise RuntimeError(f"Missing out variants: {missing_out_vars}")
RuntimeError: Missing out variants: {'quantized_decomposed::quantize_per_channel', 'quantized_decomposed::dequantize_per_channel', 'quantized_decomposed::choose_qparams', 'quantized_decomposed::quantize_per_tensor', 'quantized_decomposed::dequantize_per_tensor'}
```

Please let me know if there's any additional information I can provide to help resolve this.

Thanks again for your hard work, and I look forward to your response.

Best regards,
Jaeyeon Kim

### Versions

PyTorch version: 2.5.0.dev20240821
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 14.5 (arm64)
GCC version: Could not collect
Clang version: 15.0.0 (clang-1500.3.9.4)
CMake version: version 3.30.2
Libc version: N/A

Python version: 3.10.0 (default, Mar  3 2022, 03:54:28) [Clang 12.0.0 ] (64-bit runtime)
Python platform: macOS-14.5-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M3

Versions of relevant libraries:
[pip3] executorch==0.4.0a0+ce4917c
[pip3] numpy==1.21.3
[pip3] torch==2.5.0.dev20240821
[pip3] torchaudio==2.4.0.dev20240821
[pip3] torchsr==1.0.4
[pip3] torchvision==0.20.0.dev20240821
[conda] executorch                0.4.0a0+ce4917c          pypi_0    pypi
[conda] numpy                     1.21.3                   pypi_0    pypi
[conda] torch                     2.5.0.dev20240821          pypi_0    pypi
[conda] torchaudio                2.4.0.dev20240821          pypi_0    pypi
[conda] torchsr                   1.0.4                    pypi_0    pypi
[conda] torchvision               0.20.0.dev20240821          pypi_0    pypi

**Comment by mcr229** [comment]
Hi, I believe I made a change to our partitioner that might be causing this problem. Can you remove the fold_quantize line here and retry exporting:

https://github.com/pytorch/executorch/blob/main/examples/models/phi-3-mini/export_phi-3-mini.py#L72

**Comment by JLake310** [comment]
@mcr229 Thanks for the response.

I set `fold_quantize` to True and It seems that the conversion was successful.

Here's the log.
```
python -m examples.models.phi-3-mini.export_phi-3-mini -c "4k" -s 128 -o phi-3-mini.pte
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:28<00:00, 14.23s/it]
The 'max_batch_size' argument of ETStaticCache is deprecated and will be removed in v4.46. Use the more precisely named 'batch_size' argument instead.
W0826 13:42:53.335429 48088 torch/_export/__init__.py:65] +============================+
W0826 13:42:53.337140 48088 torch/_export/__init__.py:66] |     !!!   WARNING   !!!    |
W0826 13:42:53.337169 48088 torch/_export/__init__.py:67] +============================+
W0826 13:42:53.337193 48088 torch/_export/__init__.py:68] capture_pre_autograd_graph() is deprecated and doesn't provide any function guarantee moving forward.
/Users/jaeyeonkim/miniconda3/envs/executorch/lib/python3.10/site-packages/executorch/exir/emit/_emitter.py:1498: UserWarning: Mutation on a buffer in the model is detected. ExecuTorch assumes buffers that are mutated in the graph have a meaningless initial state, only the shape and dtype will be serialized.
  warnings.warn(
```

Appreciate for the reply again :)

**Comment by dvorjackz** [comment]
Resolved, closing
