### ISSUE TITLE
Call for Action: Supporting Dim Order in Backend Delegates

### ISSUE THREAD

**Issue by Gasoonjia** [pytorch/executorch#4873]
### Description:

As part of our recent updates to ExecuTorch's core IR, we've introduced [dim order](https://pytorch.org/executorch/stable/concepts.html#dim-order) as a representation of memory format for each tensor. However, this feature is still not enabled by default, and we need delegate authors' support to make it fully functional. In this context, dim order refers to the ordering of dimensions in a tensor's memory layout. For example, a 4D tensor with dimensions (batch, channel, height, width) can be represented in different memory formats by permuting the order of these dimensions.

In our implementation, dim order is represented as an array of integers, where each integer corresponds to a dimension in the tensor. For instance, a contiguous memory format would be represented as [0, 1, 2, 3], indicating that the dimensions are stored in the order of batch, channel, height, and width. On the other hand, a channels_last memory format would be represented as [0, 2, 3, 1], indicating that the channel dimension is stored last.

Compared with torch.memory_format, dim_order provides an explicit and detailed representation of each dimension's meaning, and is directly accessible as part of ExecuTorch's IR for any tensor.

### Issues: 

The introduction of dim order as a representation of memory format presents two challenges for backend support:
Removing torch.memory_format: The introduction of dim order means that backends will need to handle tensor arguments with non-default dim-order either AoT or at runtime. This will cause issues if the dim order in the current graph is not acceptable for the backend.
New operators: We've introduced new operators, such as to_dim_order_copy, which use dim order as the target memory format instead of the MemoryFormat variable. These operators do not exist in other places, so backends may not be equipped to handle them.

### Solution Options:
To address these challenges, we provide an example solution using the XNNPACK delegate as a reference. We encourage delegate authors to follow a similar pipeline to support dim order on their own backends:
**Delegate guards:** Implement delegate guards to ensure that AoT and runtime checks are performed correctly. See [PR 4725](https://github.com/pytorch/executorch/pull/4725) for an example implementation.
**Revert dim_order ops**: Add a new pass to revert dim_order ops back to regular ops (e.g., to_dim_order_copy back to to_copy) inside the partitioned subgraph. Please note that this is a temporary solution to give delegate authors more time to adapt to this IR change. Although it's ultimately up to the delegate authors to decide how to handle the partitioned graph, we recommend avoiding this pass in the long run and instead using the dim_order arg and ops directly. [This](https://github.com/pytorch/executorch/blob/main/exir/passes/memory_format_ops_pass.py#L73) is an example implementation of the revert pass and detailed can be found in  [PR 4520](https://github.com/pytorch/executorch/pull/4520) and its stack.
**Partition dim_order ops (if necessary)**: If your delegate currently lowers to_copy() op, you may need to add an additional step to partition dim_order ops before reverting them. This is because the to_dim_order_copy op may not be compatible with the existing partitioning logic. XNNPACK does not require this step since it does not partition to_copy() op.

### Call to Action

We encourage delegate authors to follow the pipeline demonstrated by XNNPACK to support dimension order in their respective backends. This approach will ensure compatibility with the new IR, and extend the functionality of ExecuTorch with dim order representation and operations. We hope to enable dim_order ops in the Edge IR by ET Beta (end of Sep) to ensure Edge IR stability post Beta. Therefore, we kindly request all backend delegates to be ready to handle dim_order ops in the IR by then by applying the above-mentioned relatively easy fixes/updates.

@larryliu0820  @digantdesai  @mcr229 @cccclai 

Edit:
Delegates ready for the Dim-Order Edge IR change:
✅ XNNPACK
✅ CoreML
✅ Arm

**Comment by cccclai** [comment]
cc: @YifanShenSZ , @chiwwang , @DenisVieriu97 , @neuropilot-captain

**Comment by oscarandersson8218** [comment]
https://github.com/pytorch/executorch/pull/5576 resolves this for Arm backend.

**Comment by YifanShenSZ** [comment]
Resolved for Core ML backend in coremltools 8.1 release
1. [Error out non-contiguous dim order](https://github.com/apple/coremltools/blob/8.1/coremltools/converters/mil/frontend/torch/exir_utils.py#L231-L236)
2. [Test non-contiguous dim order error raising](https://github.com/apple/coremltools/blob/8.1/coremltools/converters/mil/frontend/torch/test/test_torch_export_conversion_api.py#L74-L96)

**Comment by digantdesai** [comment]
cc @SS-JIA - do you think we can do this for Vulkan Delegate as well? 🙏

**Comment by digantdesai** [comment]
Thanks @YifanShenSZ for taking care of this. An easy way to check if these changes are sufficient or not is to flip [this](https://github.com/pytorch/executorch/blob/270d0558cecba173f5bc5a667124a79c6258054a/exir/capture/_config.py#L49) switch and run the tests with dim_order_ops in the Edge IR graph.

**Comment by digantdesai** [comment]
Thanks @haowhsu-quic for #7189 .

**Comment by digantdesai** [comment]
@DenisVieriu97 - FYI, I am trying to fix some MPS failures after turning the dim_order ops in the edge_IR on #7563. I might ask for help if I can't get it to work. :)

**Comment by Gasoonjia** [comment]
Hi @SS-JIA looks like there're some errors happened on the Vulkan tests after enabling dim order: https://github.com/pytorch/executorch/pull/7847. Would you plz take a look?

**Comment by SS-JIA** [comment]
@Gasoonjia thanks for alerting. Taking a look now.
