### ISSUE TITLE
can I employ the examples/models/llava on the arm device below? 

### ISSUE THREAD

**Issue by udrs** [pytorch/executorch#5003]
### 🐛 Describe the bug

Dear Executorch team,
Thank you for your great job.
Below is our arm embedding device:
 
Rockchip RK3588S 8-core 64-bit processor（4*Cortex-A76 + 4*Cortex-A55）
We want to run llm on its cpu.
Thank you

### Versions

（4*Cortex-A76 + 4*Cortex-A55） ubuntu22.02 python3.11 arm cpu

**Comment by udrs** [comment]
![image](https://github.com/user-attachments/assets/2b4a764a-6d29-4a73-87d0-56ef89932c8d)
It seems no arm env available as said in the image.
https://pytorch.org/executorch/stable/getting-started-setup.html

**Comment by dvorjackz** [comment]
cc @digantdesai

**Comment by digantdesai** [comment]
It should work. Assuming you can generate PTE (ExecuTorch model binary) file on some other machine (or even this machine), then you can 100% build the runtime for this target device and run it. For example, here we [demonstrate](https://dev-discuss.pytorch.org/t/run-llama3-8b-on-a-raspberry-pi-5-with-executorch/2048) running Llama3 on a Raspberry Pi 5.

**Comment by digantdesai** [comment]
Let me know or reopen this if you run into issues.
