### ISSUE TITLE
[ERROR] [Qnn ExecuTorch]: Cannot Open QNN library libQnnHtp.so, with error: libc++.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by nbansal90** [pytorch/executorch#5120]
### 🐛 Describe the bug

Receiving Error and core dump while compiling `deeplabv3`  model using QNN backend. As mentioned in the link: https://pytorch.org/executorch/0.2/build-run-qualcomm-ai-engine-direct-backend.html

After finishing up Build process. During the following steps:

> cd $EXECUTORCH_ROOT
python -m examples.qualcomm.scripts.deeplab_v3 -b build_android -m SM8550 --compile_only --download

I receive the following error during the quantization process for QNN backend

> No quant config is implemented for op, aten.dropout.default
No quant config is implemented for op, aten.dropout.default
Quantizing the model...
[ERROR] [Qnn ExecuTorch]: Cannot Open QNN library libQnnHtp.so, with error: libc++.so.1: cannot open shared object file: No such file or directory
E 00:00:47.286110 executorch:QnnImplementation.cpp:183] Fail to start backend
E 00:00:47.286136 executorch:QnnManager.cpp:273] Fail to load Qnn library
Segmentation fault (core dumped)

### Versions

Versions

NDK Version Installed: 27.0.11902837
QNN SDK Installed: 2.25.0.240728
Python: 3.10.0
Ubuntu: 22.04.4 LTS

**Comment by shewu-quic** [comment]
Hi @nbansal90,
Based on the error message, it could not find libc++.so.1 in your system environment.
It seems that there is not "libc++.so.1" in ${QNN_SDK_ROOT}/lib/x86_64-linux-clang for QNN 2.25.

I think you could try the one to install it from the following solutions:
1. Install older qnn such as 2.23 or below
2. Install it with apt-get by yourself
3. Install it with script in ${QNN_SDK_ROOT}/bin/check-linux-dependency.sh
4. Install it with conda
```bash
conda install -c conda-forge libcxx=14.0.0
```
After install, you will need to check libc++.so.1 in you LD_LIBRARY_PATH or system lib

If you have any problem, please let me know.

**Comment by nbansal90** [comment]
Solves the issue for me! Thank you

**Comment by Astuary** [comment]
Hello,

I am running into the same issue. I tried `conda install -c conda-forge libcxx=14.0.0` and then adding the `$CONDA_PREFIX/lib` path to `LD_LIBRARY_PATH`, but still the same issue. And I am unable to find QNN SDK 2.23 version.
