### ISSUE TITLE
[Segmentation fault] in example build; Cannot Open QNN library libQnnHtp.so, with error: libunwind.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by romleiaj** [pytorch/executorch#5311]
### 🐛 Describe the bug

#qcom_aisw

Build process:

``` bash
./install_requirements.sh # (had to drop nightly builds for torch)
./backends/qualcomm/scripts/build.sh # (tried with --release, as well)
```
These complete successfully, then:

``` bash
python -m examples.qualcomm.scripts.deeplab_v3 -b build-android -m SM8550 --compile_only --download
```

Failed, output: 
```
py:1062: UserWarning: erase_node(_native_batch_norm_legit_no_training_111) on an already erased node
  warnings.warn(f"erase_node({to_erase}) on an already erased node")
...
No quant config is implemented for op, aten.dropout.default
No quant config is implemented for op, aten.dropout.default
Quantizing the model...
[ERROR] [Qnn ExecuTorch]: Cannot Open QNN library libQnnHtp.so, with error: libunwind.so.1: cannot open shared object file: No such file or directory
Segmentation fault (core dumped)
```

Tried an `apt install libunwind-dev` with no success. I see a libunwind.so in the Android NDK, so I know it's there, but not finding it? Appreciate any input here, new to mobile development.

### Versions

Android NDK: 27.1.12297006
QNN SDK: 2.26.0.240828
Python version: 3.10.13
OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
Clang version: 10.0.0-4ubuntu1
CMake version: version 3.30.3
Libc version: glibc-2.31

**Comment by shewu-quic** [comment]
Hi @romleiaj,

The issue likely occurred on the x86, resulting in the inability to locate libunwind.so on the host. You might consider executing the subsequent commands.

```
apt-get update
apt-get install -y libc++-dev
```
