### ISSUE TITLE
Could not run 'cadence::quantized_conv' with arguments from the 'CPU' backend.

### ISSUE THREAD

**Issue by ZORO-Q** [pytorch/executorch#5508]
### 🐛 Describe the bug
https://github.com/pytorch/executorch/blob/main/examples/cadence/operators/quantized_conv1d_op.py
```
def export_model(
    model: nn.Module,
    example_inputs: Tuple[Any, ...],
    file_name: str = "CadenceDemoModel",
):
    # Quantizer
    quantizer = CadenceQuantizer()

    # Export
    model_exp = capture_pre_autograd_graph(model, example_inputs)

    # Prepare
    prepared_model = prepare_pt2e(model_exp, quantizer)
    prepared_model(*example_inputs)

    # Convert
    converted_model = convert_pt2e(prepared_model)

    # pyre-fixme[16]: Pyre doesn't get that CadenceQuantizer has a patterns attribute
    patterns = [q.pattern for q in quantizer.quantizers]
    QuantFusion(patterns)(converted_model)
```

After quantization with QuantFusion, is there a way to perform inference? Currently, during inference, the following issues occur:
```
RuntimeError: Could not run 'cadence::quantized_conv' with arguments from the 'CPU' backend. This could be because the operator doesn't exist for this backend, or was omitted during the selective/custom build process (if using custom build). If you are a Facebook employee using PyTorch on mobile, please visit https://fburl.com/ptmfixes for possible resolutions. 'cadence::quantized_conv' is only available for these backends: [Meta, BackendSelect, Python, FuncTorchDynamicLayerBackMode, Functionalize, Named, Conjugate, Negative, ZeroTensor, ADInplaceOrView, AutogradOther, AutogradCPU, AutogradCUDA, AutogradXLA, AutogradMPS, AutogradXPU, AutogradHPU, AutogradLazy, AutogradMeta, Tracer, AutocastCPU, AutocastXPU, AutocastCUDA, FuncTorchBatched, BatchedNestedTensor, FuncTorchVmapMode, Batched, VmapMode, FuncTorchGradWrapper, PythonTLSSnapshot, FuncTorchDynamicLayerFrontMode, PreDispatch, PythonDispatcher].
```

### Versions

PyTorch version: 2.5.0.dev20240901
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 14.5 (arm64)
GCC version: Could not collect
Clang version: 15.0.0 (clang-1500.3.9.4)
CMake version: version 3.29.6
Libc version: N/A

Python version: 3.10.0 (default, Mar 3 2022, 03:54:28) [Clang 12.0.0 ] (64-bit runtime)
Python platform: macOS-14.5-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M3

Versions of relevant libraries:
[pip3] executorch==0.4.0a0+99fbca3
[pip3] numpy==1.21.3
[pip3] torch==2.5.0.dev20240901
[pip3] torchaudio==2.5.0.dev20240901
[pip3] torchsr==1.0.4
[pip3] torchvision==0.20.0.dev20240901
[conda] executorch 0.4.0a0+99fbca3 pypi_0 pypi
[conda] numpy 1.21.3 pypi_0 pypi
[conda] torch 2.5.0.dev20240901 pypi_0 pypi
[conda] torchaudio 2.5.0.dev20240901 pypi_0 pypi
[conda] torchsr 1.0.4 pypi_0 pypi
[conda] torchvision 0.20.0.dev20240901 pypi_0 pypi

**Comment by guangy10** [comment]
cc: @kimishpatel @zonglinpengmeta

**Comment by zonglinpeng** [comment]
@guangy10 Did you see this issue from [cadence runtime](https://github.com/pytorch/executorch/tree/main/backends/cadence/runtime)? CPU backend currently runs on [cadence_runner.cpp](https://github.com/pytorch/executorch/blob/main/backends/cadence/cadence_runner/cadence_runner.cpp). If not please feel free to try out the [run_and_compare inference API](https://github.com/pytorch/executorch/blob/main/backends/cadence/aot/export_example.py#L122C5-L122C28)

**Comment by ZORO-Q** [comment]
> @guangy10 Did you see this issue from [cadence runtime](https://github.com/pytorch/executorch/tree/main/backends/cadence/runtime)? CPU backend currently runs on [cadence_runner.cpp](https://github.com/pytorch/executorch/blob/main/backends/cadence/cadence_runner/cadence_runner.cpp). If not please feel free to try out the [run_and_compare inference API](https://github.com/pytorch/executorch/blob/main/backends/cadence/aot/export_example.py#L122C5-L122C28)

When using (https://github.com/pytorch/executorch/blob/main/backends/cadence/aot/export_example.py#L122C5-L122C28), error exists
```
coremldelegate library is not found.
            If needed rebuild with the proper options in CMakeLists.txt
mpsdelegate library is not found.
            If needed rebuild with the proper options in CMakeLists.txt
qnn_executorch_backend library is not found.
            If needed rebuild with the proper options in CMakeLists.txt
extension_module library is not found.
            If needed rebuild with the proper options in CMakeLists.txt
extension_module_static library is not found.
            If needed rebuild with the proper options in CMakeLists.txt
extension_tensor library is not found.
            If needed rebuild with the proper options in CMakeLists.txt
extension_threadpool library is not found.
            If needed rebuild with the proper options in CMakeLists.txt
extension_training library is not found.
            If needed rebuild with the proper options in CMakeLists.txt
xnnpack_backend library is not found.
            If needed rebuild with the proper options in CMakeLists.txt
XNNPACK library is not found.
            If needed rebuild with the proper options in CMakeLists.txt
cpuinfo library is not found.
            If needed rebuild with the proper options in CMakeLists.txt
pthreadpool library is not found.
            If needed rebuild with the proper options in CMakeLists.txt
vulkan_backend library is not found.
            If needed rebuild with the proper options in CMakeLists.txt
optimized_kernels library is not found.
            If needed rebuild with the proper options in CMakeLists.txt
cpublas library is not found.
            If needed rebuild with the proper options in CMakeLists.txt
eigen_blas library is not found.
            If needed rebuild with the proper options in CMakeLists.txt
optimized_ops_lib library is not found.
            If needed rebuild with the proper options in CMakeLists.txt
optimized_native_cpu_ops_lib library is not found.
            If needed rebuild with the proper options in CMakeLists.txt
quantized_kernels library is not found.
            If needed rebuild with the proper options in CMakeLists.txt
quantized_ops_lib library is not found.
            If needed rebuild with the proper options in CMakeLists.txt
quantized_ops_aot_lib library is not found.
            If needed rebuild with the proper options in CMakeLists.txt
-- Generating operator lib:
--   LIB_NAME: cadence_ops_lib
--   OPS_SCHEMA_YAML: /home/yaqiong.he/executorch/backends/cadence/reference/operators/../../aot/functions.yaml
--   ROOT_OPS: 
--   INCLUDE_ALL_OPS: 
Command - python;-m;codegen.tools.gen_oplist;--output_path=/home/yaqiong.he/executorch/cmake-out/backends/cadence/reference/operators/cadence_ops_lib/selected_operators.yaml;--ops_schema_yaml_path="/home/yaqiong.he/executorch/backends/cadence/reference/operators/../../aot/functions.yaml"
-- Generating kernel bindings:
--   LIB_NAME: cadence_ops_lib
--   FUNCTIONS_YAML: /home/yaqiong.he/executorch/backends/cadence/reference/operators/../../aot/functions.yaml
--   CUSTOM_OPS_YAML: 
Generated cadence x86 files /home/yaqiong.he/executorch/cmake-out/backends/cadence/reference/operators/cadence_ops_lib/RegisterCodegenUnboxedKernelsEverything.cpp;/home/yaqiong.he/executorch/cmake-out/backends/cadence/reference/operators/cadence_ops_lib/Functions.h;/home/yaqiong.he/executorch/cmake-out/backends/cadence/reference/operators/cadence_ops_lib/NativeFunctions.h
-- Generating operator lib:
--   LIB_NAME: cadence_ops_lib
--   KERNEL_LIBS: custom_ops
--   DEPS: aten_ops_cadence
-- Configuring done (0.4s)
CMake Error in CMakeLists.txt:
  Imported target "etdump" includes non-existent path

    "/home/yaqiong.he/executorch/cmake-out/backends/cadence/../../sdk/include"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.



-- Generating done (0.0s)
CMake Generate step failed.  Build files cannot be regenerated correctly.
Traceback (most recent call last):
  File "/home/yaqiong.he/.conda/envs/executorch/lib/python3.10/site-packages/executorch/backends/cadence/runtime/executor.py", line 94, in execute
    return _execute_subprocess(args)
  File "/home/yaqiong.he/.conda/envs/executorch/lib/python3.10/site-packages/executorch/backends/cadence/runtime/executor.py", line 78, in _execute_subprocess
    raise subprocess.CalledProcessError(p.returncode, p.args, stdout, stderr)
subprocess.CalledProcessError: Command '['./backends/cadence/build_cadence_runner.sh']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/yaqiong.he/.conda/envs/executorch/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/yaqiong.he/.conda/envs/executorch/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/yaqiong.he/.local/share/code-server/extensions/ms-python.debugpy-2024.8.0/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/home/yaqiong.he/.local/share/code-server/extensions/ms-python.debugpy-2024.8.0/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/home/yaqiong.he/.local/share/code-server/extensions/ms-python.debugpy-2024.8.0/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 317, in run_module
    run_module_as_main(options.target, alter_argv=True)
  File "/home/yaqiong.he/.local/share/code-server/extensions/ms-python.debugpy-2024.8.0/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 238, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/yaqiong.he/.local/share/code-server/extensions/ms-python.debugpy-2024.8.0/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/home/yaqiong.he/executorch/examples/cadence/operators/quantized_conv1d_op.py", line 58, in <module>
    export_model(model, example_inputs)
  File "/home/yaqiong.he/.conda/envs/executorch/lib/python3.10/site-packages/executorch/backends/cadence/aot/export_example.py", line 122, in export_model
    runtime.run_and_compare(
  File "/home/yaqiong.he/.conda/envs/executorch/lib/python3.10/site-packages/executorch/backends/cadence/runtime/runtime.py", line 224, in run_and_compare
    outputs = run(executorch_prog, inputs, ref_outputs, working_dir)
  File "/home/yaqiong.he/.conda/envs/executorch/lib/python3.10/site-packages/executorch/backends/cadence/runtime/runtime.py", line 160, in run
    executor()
  File "/home/yaqiong.he/.conda/envs/executorch/lib/python3.10/site-packages/executorch/backends/cadence/runtime/executor.py", line 117, in __call__
    execute(args)
  File "/home/yaqiong.he/.conda/envs/executorch/lib/python3.10/site-packages/executorch/backends/cadence/runtime/executor.py", line 97, in execute
    raise RuntimeError(
RuntimeError: Failed to execute. Use the following to debug:
fdb ./backends/cadence/build_cadence_runner.sh
```

**Comment by guangy10** [comment]
> @tarun292 can you tag Matthias?

cc: @mcremon-meta

**Comment by mcremon-meta** [comment]
> After quantization with QuantFusion, is there a way to perform inference? Currently, during inference, the following issues occur:

If you mean running the forward model (something like `converted_model(*inputs)`), then the short answer is no unfortunately. We only provide implementations of the custom quantized ops in cpp, which basically require compiling with the whole flow to get outputs.
This is something we've talked about, but we don't have the bandwidth to implement yet :/

**Comment by zonglinpeng** [comment]
@ZORO-Q @guangy10 To just fix the Cmake dependency issue, I'm shipping a [fix to CPU flow](https://github.com/pytorch/executorch/pull/5555) to solve similar CMake build errors and enable the CPU e2e flow. Please feel free to check if the cmake error persists from there.

**Comment by ZORO-Q** [comment]
> > After quantization with QuantFusion, is there a way to perform inference? Currently, during inference, the following issues occur:
> 
> If you mean running the forward model (something like `converted_model(*inputs)`), then the short answer is no unfortunately. We only provide implementations of the custom quantized ops in cpp, which basically require compiling with the whole flow to get outputs. This is something we've talked about, but we don't have the bandwidth to implement yet :/

Okey, Thank you for your answer!

**Comment by ZORO-Q** [comment]
> @ZORO-Q @guangy10 To just fix the Cmake dependency issue, I'm shipping a [fix to CPU flow](https://github.com/pytorch/executorch/pull/5555) to solve similar CMake build errors and enable the CPU e2e flow. Please feel free to check if the cmake error persists from there.



> @ZORO-Q @guangy10 To just fix the Cmake dependency issue, I'm shipping a [fix to CPU flow](https://github.com/pytorch/executorch/pull/5555) to solve similar CMake build errors and enable the CPU e2e flow. Please feel free to check if the cmake error persists from there.

Thank you! I will give it a try.

**Comment by ZORO-Q** [comment]
> @ZORO-Q @guangy10 To just fix the Cmake dependency issue, I'm shipping a [fix to CPU flow](https://github.com/pytorch/executorch/pull/5555) to solve similar CMake build errors and enable the CPU e2e flow. Please feel free to check if the cmake error persists from there.

I tried the new code and encountered the following issue.
```
In file included from /executorch/extension/data_loader/../../../executorch/runtime/core/error.h:18,
                 from /executorch/extension/data_loader/../../../executorch/runtime/core/result.h:19,
                 from /executorch/extension/data_loader/../../../executorch/runtime/core/data_loader.h:14,
                 from /executorch/extension/data_loader/../../../executorch/extension/data_loader/mmap_data_loader.h:11,
                 from /executorch/extension/data_loader/mmap_data_loader.cpp:9:
/executorch/extension/data_loader/mmap_data_loader.cpp: In function ‘void executorch::extension::{anonymous}::MunmapSegment(void*, void*, size_t)’:
/executorch/extension/data_loader/mmap_data_loader.cpp:143:9: warning: too many arguments for format [-Wformat-extra-args]
  143 |         "munmap(0x%zx, %zu) failed: %s (ignored)",
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/executorch/extension/data_loader/../../../executorch/runtime/platform/log.h:171:11: note: in definition of macro ‘ET_LOG’
  171 |           _format,                                                   \
      |           ^~~~~~~
```

**Comment by zonglinpeng** [comment]
> data_loader

this looks like from the ET side where data_loader is not included properly. Cadence has an example runner that has the right [dependencies](https://github.com/pytorch/executorch/pull/5555/files#diff-248b2f7d3fb660cde247b580af85fc12555ae32e74c678cfe80f2de65240efd5R68). Also try the cmake commands in the [build.sh](https://github.com/pytorch/executorch/pull/5555/files#diff-d7422d7443bdd500ca7f2c2341ecc41925dfec7ca0e55317ec3e6b5046c15a6a)

**Comment by ZORO-Q** [comment]
> > data_loader
> 
> this looks like from the ET side where data_loader is not included properly. Cadence has an example runner that has the right [dependencies](https://github.com/pytorch/executorch/pull/5555/files#diff-248b2f7d3fb660cde247b580af85fc12555ae32e74c678cfe80f2de65240efd5R68). Also try the cmake commands in the [build.sh](https://github.com/pytorch/executorch/pull/5555/files#diff-d7422d7443bdd500ca7f2c2341ecc41925dfec7ca0e55317ec3e6b5046c15a6a)

I just run ./backends/cadence/cadence_runner/build_cadence_runner.sh and then the above issue occurred. Is there something wrong on my end?

**Comment by zonglinpeng** [comment]
Can you make a separate post to the ExecuTorch extension owners? Please make sure pulling the latest ExecuTorch repo, install submodules and other dependencies as [instructed](https://pytorch.org/executorch/stable/getting-started-setup.html#quick-setup-colab-jupyter-notebook-prototype).

**Comment by ZORO-Q** [comment]
> Can you make a separate post to the ExecuTorch extension owners? Please make sure pulling the latest ExecuTorch repo, install submodules and other dependencies as [instructed](https://pytorch.org/executorch/stable/getting-started-setup.html#quick-setup-colab-jupyter-notebook-prototype).

Thank you, I will check it and make a new post.

**Comment by zonglinpeng** [comment]
C
