### ISSUE TITLE
Building Llama IOS Demo failed

### ISSUE THREAD

**Issue by Hanxian97** [pytorch/executorch#5623]
Hi I am new to Xcode. I tried to follow this [tutorial](https://github.com/pytorch/executorch/tree/main/examples/demo-apps/apple_ios/LLaMA) to run Llama IOS demo on my iPhone. 

I went through the process until the "Xcode" section, and opened the project of examples/demo-apps/apple_ios/LLama. When I tried to do "select which ExecuTorch framework should link against which target." I found I cannot link the backends against the main app target, as shown in this figure:
![xcode](https://github.com/user-attachments/assets/692ad952-976a-47e4-b4f8-811a627959ea)

Thus after this, when I ran the app, it failed with the error "PhaseScriptExecution failed with a nonzero exit code". 

When I followed the exactly same flow to set up and run this [benchmark app](https://github.com/pytorch/executorch/tree/main/extension/apple/Benchmark), I can successfully run it on my phone.

Do you have any idea on how to properly set up the ExecuTorch dependency for the llama demo app? Thank you so much!

**Comment by Olivia-liu** [comment]
@shoumikhin @Riandy Would you be able to look at this question? Thank you

**Comment by shoumikhin** [comment]
@Hanxian97 the project you've opened is already set up to work out the box, so just click Run and it should launch the app in Simulator.

**Comment by Hanxian97** [comment]
@shoumikhin Thank you for your reply. When I click "Run", it will still build before run, and triggered the "PhaseScriptExecution failed with a nonzero exit code" error. Did I miss something?

**Comment by Hanxian97** [comment]
Or do you have a doc/tutorial for using this [benchmark app](https://github.com/pytorch/executorch/tree/main/extension/apple/Benchmark)? I can successfully run this, but I am not sure how to use it/modify it after that. Thank you!

**Comment by kebbbnnn** [comment]
Had the same PhaseScriptExecution error. It turns out Xcode can't find the cmake installed via homebrew  that resides in `/opt/homebrew/bin/` even if I added it to PATH. So I uninstalled the homebrew cmake and downloaded cmake gui here https://cmake.org/download/ then run: `sudo "/Applications/CMake.app/Contents/bin/cmake-gui" --install` to install symlinks to` /usr/local/bin/` then everything worked fined.
