### ISSUE TITLE
Python run_method API segfaults if given non-existent method

### ISSUE THREAD

**Issue by swolchok** [pytorch/executorch#5648]
### 🐛 Describe the bug

Repro:
1) install executorch with ./install_requirements.sh --pybind
2)
```
>>> from executorch.extension.pybindings import portable_lib as exec_lib
>>> mod = exec_lib._load_for_executorch("some.pte")
>>> mod.run_method("idontexist")
fish: Job 1, 'python' terminated by signal SIGSEGV (Address boundary error)
```

### Versions

latest executorch main, commit hash cd4672101a59e562121293828dbb41f1dfc6289b

**Comment by dbort** [comment]
We should definitely throw a python exception instead of segfaulting.

**Comment by JacobSzwejbka** [comment]
Looking

**Comment by JacobSzwejbka** [comment]
https://github.com/pytorch/executorch/blob/main/extension/pybindings/pybindings.cpp#L252 lol
