### ISSUE TITLE
Numeric difference appear in ARM test_sigmoid_add_tosa_BI with PT Pin Bump

### ISSUE THREAD

**Issue by Jack-Khuu** [pytorch/executorch#5832]
### 🐛 Describe the bug

https://github.com/pytorch/executorch/pull/5824 Performs a pin bump to dev20240927 for PyTorch Versioning. While doing so, we encounter failures related to ARM unittests specifically around `test_sigmoid_add_tosa_BI`

Example run:
https://github.com/pytorch/executorch/actions/runs/11150808085/job/30992819400

### Versions

See https://github.com/pytorch/executorch/pull/5824

**Comment by digantdesai** [comment]
If it was working before and only 3/4 fails including TOSA ones - the only Sigmoid one is passing. We need to dig deeper to see what changed.

cc @Erik-Lundell for FYI

**Comment by zingo** [comment]
As a fast CI-fix fix I created https://github.com/pytorch/executorch/pull/5843 until this is sorted out

**Comment by zingo** [comment]
Hi after the merge of:
Add sigmoid to one-to-one annotator in ArmQuantizer (https://github.com/pytorch/executorch/pull/6047)

We are ready to close this (from Arm side of things) 
@Jack-Khuu & @digantdesai  is there anything more you want to do with this?

**Comment by Jack-Khuu** [comment]
I believe so, closed
