### ISSUE TITLE
Unable to locate llama3.2 model and tokenizer files in the ios demo app

### ISSUE THREAD

**Issue by hietalajulius** [pytorch/executorch#5840]
Following this tutorial: https://github.com/pytorch/executorch/blob/main/examples/demo-apps/apple_ios/LLaMA/docs/delegates/xnnpack_README.md (on main, commit `92d1d1e410b11945869472e88a2247305921989a`, iPhone 12 Pro, iOS 17.6.1)

When I drag and drop the model and tokenizer files in finder, they are not visible in the file navigator when trying to select them in the app:

<img width="786" alt="Screenshot 2024-10-02 at 22 36 55" src="https://github.com/user-attachments/assets/d41d995f-1bd5-4fdc-b8ff-21083b4aa82d"> (`llama3_2.pte` and `tokenizer.bin` inside the directories)

Any ideas what I'm doing wrong?

update: airdropping the files from my mac makes them visible and selectable in the app but it still says "Select model..." when both model and tokenizer are seemingly set.
![image](https://github.com/user-attachments/assets/5030982b-1f19-4204-a9f2-e76adbe4a4ae)

**Comment by iseeyuan** [comment]
@shoumikhin , could you help look at this?

**Comment by a8nova** [comment]
I am also facing a similar issue

**Comment by WuhanMonkey** [comment]
cc. @Riandy

**Comment by Riandy** [comment]
Try dropping them "outside" the models and tokenizers folder, basically direct child of the "iLLAMA" app in your finder.

Something like
iLLaMA
- <your_model_file.pte>
- <your_tokenizer_file.bin>
- <models folder>
- <tokenizers folder>

**Comment by hietalajulius** [comment]
> Try dropping them "outside" the models and tokenizers folder, basically direct child of the "iLLAMA" app in your finder.
> 
> Something like iLLaMA
> 
> * <your_model_file.pte>
> * <your_tokenizer_file.bin>
> * 
> *

Looks like the same thing with this setup
<img width="785" alt="Screenshot 2024-10-11 at 9 18 40" src="https://github.com/user-attachments/assets/7861fad0-5d10-4f0a-b926-9115bb11a60b">

**Comment by shoumikhin** [comment]
@hietalajulius try removing the app from the device, deploying&launching the app again, then copy the files, wait till copying finishes and proceed with the app UI to pick them.

**Comment by hietalajulius** [comment]
> @hietalajulius try removing the app from the device, deploying&launching the app again, then copy the files, wait till copying finishes and proceed with the app UI to pick them.

Thanks, that worked! I was convinced I did it already but apparently not :D
