### ISSUE TITLE
setup-with-qnn

### ISSUE THREAD

**Issue by Vinaysukhesh98** [pytorch/executorch#5852]
### 🐛 Describe the bug

setup-with-qnn.sh

### Versions

examples/demo-apps/android/LlamaDemo/setup-with-qnn.sh: 68: pushd: not found
while running script getting specific error?

**Comment by JamePeng** [comment]
If you are using Ubuntu, the solution is to execute the sudo dpkg-reconfigure dash command and set dash to No.

**Comment by kirklandsign** [comment]
We are assuming bash (or zsh) environment in our setup script.
