### ISSUE TITLE
On android, app throws ERROR CODE: 18 on loading the models

### ISSUE THREAD

**Issue by Deswaluday** [pytorch/executorch#6095]
So what is exact reason of the error and from where we can find the description of all Error Codes?

**Comment by cmodi-meta** [comment]
Thanks for the question @Deswaluday. Error 18 is associated with an "invalid argument" error.

This is found in [error.h](https://github.com/pytorch/executorch/blob/main/runtime/core/error.h#L57). (error 18 decimal value maps to 0x12 in hex).

This can happen in instances where the .pte and tokenizer file are not for the same model or also if the "Model Type" in the Settings is not corresponding to the correct model you are trying to load.

**Comment by cmodi-meta** [comment]
I'll close this issue. If the issue still persists then feel free to reopen the issue - please include your set-up on what type of model you are trying to load and screenshots of your settings page. Thank you!
