### ISSUE TITLE
On which real Android Devices we can test the app. Please explain with configuration of the devices also.

### ISSUE THREAD

**Issue by Deswaluday** [pytorch/executorch#6096]

**Comment by WuhanMonkey** [comment]
@Deswaluday I think we clearly stated the working devices at the start of each tutorial for difference backends. For example, for XNN backend [here](https://github.com/pytorch/executorch/blob/main/examples/demo-apps/android/LlamaDemo/docs/delegates/xnnpack_README.md), we have tested OnePlus 12, OnePlus 9 Pro. Samsung S23 (Llama only), Samsung S24+ (Llama only), Pixel 8 Pro (Llama only)

**Comment by cmodi-meta** [comment]
Just to add, recommended specific RAM sizes for the Android devices per model.
- Llama 3.2:
   - 1B model (BFloat16): 8GB+ RAM 
   - 3B model (BFloat16): 12GB+ RAM
- Llama 3.1:
   - 8B model: 12GB+ RAM
- Llama 2: 
   - 7B model: 12GB+ RAM 

This is also specified in the [XNNPACK Readme file](https://github.com/pytorch/executorch/blob/main/examples/demo-apps/android/LlamaDemo/docs/delegates/xnnpack_README.md).

**Comment by cmodi-meta** [comment]
Hope this helps! Closing the issue but feel free to reopen in case if you have any other questions on this topic. Thanks!
