### ISSUE TITLE
Is there a way to manipulate the model's key/value cache or tokenizer's outputs in Android?

### ISSUE THREAD

**Issue by 1010asdf0101** [pytorch/executorch#6464]
### 🚀 The feature, motivation and pitch

![Screenshot_20241024_053253_ExecuTorchLlamaDemo](https://github.com/user-attachments/assets/4458b3a7-be06-4656-99d2-65cfa527f555)

The results using the Llama3.2-1B-Instruct model are insufficient, so I would like to increase the results a bit long. Therefore, I would like to manipulate directly the input and output of the model, such as saving KV cache values. Are there any related features or documents?

**Comment by larryliu0820** [comment]
This sounds like a multiturn conversion request. I think we support this feature right now. Also it seems your `max_seq_len` is set to 128 which is too short. Please follow the wiki to make it larger. cc @cmodi-meta for the conversation feature.

**Comment by 1010asdf0101** [comment]
@larryliu0820 Thanks for your reply. I changed `max_seq_len` of exported Llama model, it works well.
But, there is a limitation, LlamaDemo App always crush when length of conversation history exceeded `max_seq_len`, so I want to fix `mModule` or `mModule.generate()` how can I fix them?
