### ISSUE TITLE
Refactor ArmBackend::preprocess()

### ISSUE THREAD

**Issue by digantdesai** [pytorch/executorch#667]
this is not scalable, and we are getting quite close to **spaghettification** point, I think #1 priority after MVP should be to refactor `preprocess()`.

_Originally posted by @digantdesai in https://github.com/pytorch/executorch/pull/616#discussion_r1348258565_

**Comment by Jerry-Ge** [comment]
https://github.com/pytorch/executorch/pull/1099

**Comment by Jerry-Ge** [comment]
The patch already got merged, I think we can close this issue now. @digantdesai @dbort
