### ISSUE TITLE
Lower model to XNNPACK on iOS platform but failed run: Missing operator: [5] executorch_prim::et_view.default. 

### ISSUE THREAD

**Issue by LuckyHeart** [pytorch/executorch#6749]
### 🐛 Describe the bug

I have successfully lowered the model to XNNPACK and utilize the cmake to run on the laptop according to the Documentation on [https://pytorch.ac.cn/executorch/stable/tutorial-xnnpack-delegate-lowering.html].

However, when I implemented the iOS app, it reported the following errors:

```
E 00:00:05.398363 executorch:operator_registry.cpp:185] kernel 'executorch_prim::et_view.default' not found.
E 00:00:05.398371 executorch:operator_registry.cpp:186] dtype: 6 | dim order: [
E 00:00:05.398373 executorch:operator_registry.cpp:186] 0,
E 00:00:05.398790 executorch:operator_registry.cpp:186] 1,
E 00:00:05.398808 executorch:operator_registry.cpp:186] 2,
E 00:00:05.398813 executorch:operator_registry.cpp:186] 3,
E 00:00:05.398817 executorch:operator_registry.cpp:186] ]
E 00:00:05.398820 executorch:operator_registry.cpp:186] dtype: 6 | dim order: [
E 00:00:05.398823 executorch:operator_registry.cpp:186] 0,
E 00:00:05.398826 executorch:operator_registry.cpp:186] 1,
E 00:00:05.398829 executorch:operator_registry.cpp:186] 2,
E 00:00:05.398832 executorch:operator_registry.cpp:186] 3,
E 00:00:05.398836 executorch:operator_registry.cpp:186] ]
E 00:00:05.398838 executorch:method.cpp:542] Missing operator: [5] executorch_prim::et_view.default
``` 

Hope to get your help!! THX！！！

**Comment by virginia-cangelosi** [comment]
I also have this issue with Xnnpack but with aten::_adaptive_avg_pool2d.out. Any help would be appreciated

**Comment by LuckyHeart** [comment]
> I also have this issue with Xnnpack but with aten::_adaptive_avg_pool2d.out. Any help would be appreciated

Maybe you can try
```
**Missing operator or backend**

If after linking against a certain ExecuTorch library you still get an unregistered kernel or backend error at runtime, 
you may need to use the -all_load or -force_load $(BUILT_PRODUCTS_DIR)/<library_name> linker flags to
 forcefully register the corresponding components at app start, e.g., -force_load $(BUILT_PRODUCTS_DIR)/libkernels_portable-ios-release.a.
```

**Comment by LuckyHeart** [comment]
> @LuckyHeart Did you try the force load option, and if so, did that resolve the issue? If not, I can help figure out what's going on.

Thanks for your reply. I have successfully solve the problem as mentioned above by utilizing  the force load option.

I first deployed the environment in xcode according to the instructions of the video in document [https://pytorch.org/executorch/main/apple-runtime.html](url), and utilize the **-force_load option.** However, I still encounter the problem as the mentioned.  Finally, I utilized the way of the **Local Build** in the document [https://pytorch.org/executorch/main/apple-runtime.html](url), and successfully run.

Thanks a lot! Great work!!
