### ISSUE TITLE
Removed std::vector container from the Arm delegate runtime code

### ISSUE THREAD

**Issue by digantdesai** [pytorch/executorch#677]
Let's try to see if we can get away without this std::container. It will be better from size and portability point of view. Other than input/output we aren't using it anywhere else so should be easy to get rid of it.

_Originally posted by @digantdesai in https://github.com/pytorch/executorch/pull/659#discussion_r1349434360_

**Comment by JacobSzwejbka** [comment]
Just to clarify by runtime you mean in the arm ethos delegate

**Comment by robell** [comment]
Yes this is a backends/arm/runtime localised issue.
