### ISSUE TITLE
the clang compiler does not support '-march=armv8.2-a+bf16' when build xnnpack for android

### ISSUE THREAD

**Issue by feifeicoder** [pytorch/executorch#6924]
Follow the tutorial to build xnnpack runtime lib for android with NDK r19 and meet such errors:

[ 91%] Building C object backends/xnnpack/third-party/XNNPACK/CMakeFiles/microkernels-all.dir/src/bf16-gemm/gen/bf16-gemm-1x4c8-minmax-neonbf16-bfmlal.c.o
[ 91%] Building C object backends/xnnpack/third-party/XNNPACK/CMakeFiles/microkernels-all.dir/src/bf16-gemm/gen/bf16-gemm-1x4c8-minmax-neonbf16-bfdot.c.o
[ 91%] Building C object backends/xnnpack/third-party/XNNPACK/CMakeFiles/microkernels-all.dir/src/bf16-gemm/gen/bf16-gemm-1x8c2-minmax-neonbf16-bfdot-lane-ld128.c.o
clang: error: the clang compiler does not support '-march=armv8.2-a+bf16'
gmake[2]: *** [backends/xnnpack/third-party/XNNPACK/CMakeFiles/microkernels-all.dir/build.make:43241: backends/xnnpack/third-party/XNNPACK/CMakeFiles/microkernels-all.dir/src/bf16-gemm/gen/bf16-gemm-1x4c8-minmax-neonbf16-bfmlal.c.o] Error 1

**Comment by agunapal** [comment]
Getting the same error 

```
[ 92%] Building C object backends/xnnpack/third-party/XNNPACK/CMakeFiles/microkernels-all.dir/src/bf16-gemm/gen/bf16-gemm-1x4c8-minmax-neonbf16-bfdot.c.o
[ 92%] Building C object backends/xnnpack/third-party/XNNPACK/CMakeFiles/microkernels-all.dir/src/bf16-gemm/gen/bf16-gemm-2x4c8-minmax-neonbf16-bfmlal.c.o
[ 92%] Building C object backends/xnnpack/third-party/XNNPACK/CMakeFiles/microkernels-all.dir/src/bf16-gemm/gen/bf16-gemm-1x4c8-minmax-neonbf16-bfmlal.c.o
[ 92%] Building C object backends/xnnpack/third-party/XNNPACK/CMakeFiles/microkernels-all.dir/src/bf16-gemm/gen/bf16-gemm-2x4c8-minmax-neonbf16-bfdot.c.o
[ 92%] Building C object backends/xnnpack/third-party/XNNPACK/CMakeFiles/microkernels-all.dir/src/bf16-gemm/gen/bf16-gemm-1x8c2-minmax-neonbf16-bfdot-lane-ld128.c.o
clang: error: the clang compiler does not support '-march=armv8.2-a+bf16'
make[2]: *** [backends/xnnpack/third-party/XNNPACK/CMakeFiles/microkernels-all.dir/src/bf16-gemm/gen/bf16-gemm-2x4c8-minmax-neonbf16-bfmlal.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
clang: error: the clang compiler does not support '-march=armv8.2-a+bf16'
```

**Comment by metascroy** [comment]
@digantdesai do you know a work around for this issue with clang?

**Comment by metascroy** [comment]
It looks like a similar issue was filed in XNNPACK and the suggested solution was to disable bf16 with -DXNNPACK_ENABLE_ARM_BF16=OFF (https://github.com/google/XNNPACK/issues/3618).  I guess using GCC might also work, but maybe there's a better option with clang

**Comment by agunapal** [comment]
Thanks! That works

**Comment by digantdesai** [comment]
Thanks @metascroy for the suggestion.

Yeah I guess the right way would be to check (by tracking minimum_supported_version for clang in this case) if the compiler supports, this and enable only when it does. And`XNNPACK_ENABLE_ARM_BF16=OFF` is just a static version of that.

That said BF16 was [enabled](https://releases.llvm.org/11.0.1/docs/ReleaseNotes.html#changes-to-the-aarch64-backend) by LLVM a while ago (2020?), and is the reason to enable by default.
