### ISSUE TITLE
LlamaDemo with backend QUALCOMM but choose XNNPACK ?

### ISSUE THREAD

**Issue by scsonic** [pytorch/executorch#7050]
### 🚀 The feature, motivation and pitch

In LlamaDemo, SettingActivity.java
what ever you choose QUALCOMM backend, the app alwawys select the XNNPACK?
is there way to enable QUALCOMM backend?

  private void setBackendSettingMode() {
    if (mBackendType.equals(BackendType.XNNPACK) || mBackendType.equals(BackendType.QUALCOMM)) {
      setXNNPACKSettingMode();
    } else if (mBackendType.equals(BackendType.MEDIATEK)) {
      setMediaTekSettingMode();
    }
  }

https://github.com/pytorch/executorch/blob/b3f2a793b6358956709f6db1adf51e8038c27745/examples/demo-apps/android/LlamaDemo/app/src/main/java/com/example/executorchllamademo/SettingsActivity.java#L411C1-L418C1

the README.md, you can build QNN with LlamaDemo
https://github.com/pytorch/executorch/blob/main/examples/demo-apps/android/LlamaDemo/README.md

**Comment by cccclai** [comment]
The backend is chosen AoT, how did you export the model and what backend would you like to target? If you can share the use case, we can provide better instruction here

**Comment by scsonic** [comment]
Thanks for response
I’m just concerned that I might select the QNN .pte file but end up executing it with XNNPACK instead.

by the way
Is there a way to backup the context binary?
its similar to ONNX Runtime’s feature for caching context binaries:
https://onnxruntime.ai/docs/execution-providers/QNN-ExecutionProvider.html#qnn-context-binary-cache-feature

This would allow me to cache the 2k system prompt efficiently.

**Comment by scsonic** [comment]
Scenario:
When I select a PTE file, the app will update and display which backends support this PTE file.

Example 1:

Selected CPU PTE file:
Display:
XNNPACK: ✅ Supported
CPU: ✅ Supported
Qualcomm: ❌ Not Supported
MTK: ❌ Not Supported
Reason for Not Supported: (Provide details here)

Example 2: 
Selected QNN PTE (e.g., QCS8550, QCS8650):
Display:
XNNPACK: ❌ Not Supported
CPU: ❌ Not Supported
Qualcomm: ✅ Supported
MTK: ❌ Not Supported
Reason for Not Supported: your device is 8650, is not 8550, can't use HTPbackend v73

**Comment by cccclai** [comment]
> Is there a way to backup the context binary? its similar to ONNX Runtime’s feature for caching context binaries:
https://onnxruntime.ai/docs/execution-providers/QNN-ExecutionProvider.html#qnn-context-binary-cache-feature This would allow me to cache the 2k system prompt efficiently.

@chiwwang any chance you know about this?

**Comment by chiwwang** [comment]
Hi @scsonic ,

I think this onnxruntime feature is similar to what we do in AOT compilation stage, i.e., compiling out a context-binary.
I'm not pretty sure what the scenario "cache the 2k system prompt" is. Could you please elaborate a bit more? Is it something like, adding some constants and ConcatOp to the model input to form a system prompt...?

**Comment by scsonic** [comment]
My system prompt is long, and getting the first token takes 90 seconds.
With llama.cpp, the first run takes 90 seconds, but second runs are faster < 1 seconds
if the prompt prefix is the same, as it's cached.

for example:
```
<|begin_of_text|><|start_header_id|>system<|end_header_id|>
You are a helpful assistant {a long prompt stirng}<|eot_id|><|start_header_id|>user<|end_header_id|>
**good morning** <|eot_id|><|start_header_id|>assistant<|end_header_id|>
```
get first token take 90 seconds

When running again with the same system prompt and only a different user input, it doesn't require another 90-second wait.
```
<|begin_of_text|><|start_header_id|>system<|end_header_id|>
You are a helpful assistant {a long prompt stirng}<|eot_id|><|start_header_id|>user<|end_header_id|>
**hi, whats your name** <|eot_id|><|start_header_id|>assistant<|end_header_id|>
```

With executorch, it recalculates every time, always taking 90 seconds.
Is it possible to implement a similar caching feature?
This is crucial for production use.

**Comment by chiwwang** [comment]
Hi @scsonic ,

I see. It seems something related to KV cache.

If we can store the KV cache produced by the below prompt:
```
<|begin_of_text|><|start_header_id|>system<|end_header_id|>
You are a helpful assistant {a long prompt stirng}<|eot_id|><|start_header_id|>user<|end_header_id|>
```
as whenever we get a user input.

Whenever we get a user input, we can feed `whenever we get a user input` and the user input wrapped as:
```
**hi, whats your name** <|eot_id|><|start_header_id|>assistant<|end_header_id|>
```
It should have the same effect, i.e., the "caching" seems to mean KV-cache here...?


BTW -- stay tuned! We're going to publish a hybrid model which can help Time-To-First-Token (TTFT) and following inferencing, which might also help your use case.

**Comment by scsonic** [comment]
Could you point out the API you mentioned for Android ExecuTorch and its specific functionality? 
Thank you!

**Comment by chiwwang** [comment]
Ah... no specific API for the behavior. The application might need to implement that by itself.

**Comment by cccclai** [comment]
> Could you point out the API you mentioned for Android ExecuTorch and its specific functionality? Thank you!

I think this kind of caching is a good feature to have, and I recommend keeping the issue open so we can keep track of it.
