### ISSUE TITLE
pip install executorch doesn't install llama custom ops

### ISSUE THREAD

**Issue by mergennachin** [pytorch/executorch#7086]
### 🚀 The feature, motivation and pitch

pip install executorch doesn't install sdpa_with_kv_cache op

Currently, llama is such a first-class citizen and so it makes sense to install these important custom ops by default as part of the pip installation. 

Here's a repro step: 

https://colab.research.google.com/drive/1xofI6KV1a5DX1Zlu2YONu92a9FgBPHSB#scrollTo=f9r__rm15mbp

**Comment by larryliu0820** [comment]
This only repros in colab. I tried `0.5.0.dev20241126` nightly the following works:

```
from executorch.kernels import quantized
```

But importing llm custom op failed
```
from executorch.extension.llm.custom_ops import sdpa_with_kv_cache
```

**Comment by larryliu0820** [comment]
https://github.com/pytorch/executorch/pull/7096 should fix

**Comment by mergennachin** [comment]
Hi @larryliu0820 

It's still having same issue. See repro using executorch==0.5.0.dev20241201

https://colab.research.google.com/drive/1xofI6KV1a5DX1Zlu2YONu92a9FgBPHSB#scrollTo=f9r__rm15mbp
