### ISSUE TITLE
Cannot export mobilenet_v3 because Batchnorm2D is not "Aten Canonical".

### ISSUE THREAD

**Issue by zecerman** [pytorch/executorch#7205]
### 🐛 Describe the bug

When I try to export a pretrained model such as mobilenet_v3_small (imported from torchvision.models) I cannot successfully export it to a .pte file, the process errors and complains: 

> "torch._export.verifier.SpecViolationError: Operator torch._ops.aten._native_batch_norm_legit_functional.default is not Aten Canonical."

Ive debugged with torch.fx and cannot find this _native_batch_norm_legit_functional operator, so I suspect it has to do with the Batchnorm2d layers present in most computer vision models.

I cannot find anything helpful via google or chatgpt about this issue, I cannot find anyone who complains that they cannot export mobilenet_v3, resnet or other existing models with executorch, so I am at a loss. 

Any advice is appreciated, the full code for my test export is:

```
from torchvision.models import mobilenet_v3_small, MobileNet_V3_Small_Weights
import torch
import torch.nn as nn

device = 'cuda' if torch.cuda.is_available() else 'cpu'

def create_model(num_classes=101):
    # Load the pretrained MobileNet V3 Small model
    model = mobilenet_v3_small(weights=MobileNet_V3_Small_Weights.DEFAULT)
    
    # Access the in_features from the Linear layer (last layer in the classifier)
    in_features = model.classifier[3].in_features  # The fourth layer in the Sequential is the Linear layer
    model.classifier[3] = torch.nn.Linear(in_features, num_classes)  # Replace the Linear layer

    return model.to(device)

# Create the model
model = create_model(num_classes=101)

# Ensure the input tensor is contiguous
sample_input = torch.randn(1, 3, 224, 224).contiguous()

# Perform a forward pass
output = model(sample_input)

# Inspect the computation graph
import torch.fx as fx
graph_module = fx.symbolic_trace(model)
print(graph_module.graph)  # Look for `empty_permuted` in the graph

# Export the model with contiguous tensors
sample_inputs = (sample_input,)
from torch.export import export
exported_program = export(model, sample_inputs)

# Save to a .pte file
from executorch.exir import EdgeProgramManager, to_edge_transform_and_lower
from executorch.backends.xnnpack.partition.xnnpack_partitioner import XnnpackPartitioner

edge = to_edge_transform_and_lower(
    exported_program,
    partitioner=[XnnpackPartitioner()],
)

exec_prog = edge.to_executorch()

output_path = "mobilenet_v3_small_1.pte"
with open(output_path, "wb") as f:
    exec_prog.write_to_file(f)

print(f"Exported model saved to {output_path}")
```

### Versions

PyTorch version: 2.5.0+cpu
Is debug build: False
CUDA used to build PyTorch: Could not collect
ROCM used to build PyTorch: N/A

OS: Ubuntu 24.04.1 LTS (x86_64)
GCC version: (Ubuntu 13.2.0-23ubuntu4) 13.2.0
Clang version: Could not collect
CMake version: version 3.31.1
Libc version: glibc-2.39

Python version: 3.10.0 (default, Mar  3 2022, 09:58:08) [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.39
Is CUDA available: False
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 4070
Nvidia driver version: 552.22
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

**Comment by dbort** [comment]
Thank you for the super-detailed instructions! I'll find someone to help look into this.

**Comment by larryliu0820** [comment]
Can you do 
```
from executorch.exir import EdgeCompileConfig

edge = to_edge_transform_and_lower(
  exported_program,
  partitioner=[XnnpackPartitioner()],
  compile_config=EdgeCompileConfig(_core_aten_ops_exception_list=torch.ops.aten. _native_batch_norm_legit_functional.default),
)
```

**Comment by larryliu0820** [comment]
Can you also try to add `with torch.no_grad():` context?

```
with torch.no_grad():
  edge = to_edge_transform_and_lower(
    exported_program,
    partitioner=[XnnpackPartitioner()],
  )
```
