### ISSUE TITLE
does at:tensor has permute ?

### ISSUE THREAD

**Issue by bok3948** [pytorch/executorch#7215]
### 🚀 The feature, motivation and pitch

does at:tensor has permute ?  i have image in cv mat format but i want to permute it and give to executorch module.  i can  change cv  mat  to  float array. but i want to permute because cv mat was  224 x 224 x 3 i want to change 1 x 3 x 224 x 224 . is there any simple code for this? i'm not familar with c++ . thank you

**Comment by dbort** [comment]
If you have an at::Tensor, you may be able to call `.permute()` on it directly, like
https://github.com/pytorch/pytorch/blob/f2f95ba813a7a65b9489f86ac82b937d76bca807/aten/src/ATen/native/transformers/attention.cpp#L100-L103. I'm not sure if the `.contiguous()` or `.view()` are required for your specific situation.

If you're using https://github.com/pytorch/executorch/blob/main/extension/aten_util/aten_bridge.h to convert the at::Tensor into an ExecuTorch tensor, it is important that the tensor is contiguous.

I hope this helps. If not, please re-open the issue with more information and we'll try to help more.

**Comment by bok3948** [comment]
Hi Thanks for reply. I'm using executorch::runtime::etensor::Tensor, it seems to don't have permute   Here is my cpp code, how can i use permute and unsqueeze for etensor::Tensor or there is simple hack for this i want to process image .  Thank you!      
![화면 캡처 2024-12-08 203510](https://github.com/user-attachments/assets/a1d28c3f-d0b2-4ae6-ac25-db53bdb664b1)
