### ISSUE TITLE
Arm backend buck2 CI tests

### ISSUE THREAD

**Issue by AdrianLundell** [pytorch/executorch#7299]
We frequently need fixes on our TARGET files after upstreaming PRs (see for example #7004) since we are not testing the buck2 flow in CI tests.

In fact, it seems that building using buck2 has been/will be deprecated externally to Meta according to commits such as #4597, so the question is how we should deal with this to avoid breaking things. Perhaps additional github testing, or if there is a solution that could be used locally as well?

**Comment by digantdesai** [comment]
Thanks for creating this ticket. I am not sure if we want to remove oss buck build completely, precisely to avoid this issue. 

Till then I think we should add a simple build and run test using buck. Let me add that.

**Comment by digantdesai** [comment]
Ok discussed this with Hansong.

Buck support in OSS is minimal at the moment, and IIUC the motivation is to simplify OSS development on ET.

For now, such buck failures will be dealt with "manually", working with someone on ExecuTorch Team.

We are still discussing how to streamline things, and make the buck failures visible to OSS devs.

cc @kirklandsign
