### ISSUE TITLE
Add support of mutable buffers in ExecuTorch

### ISSUE THREAD

**Issue by kirklandsign** [pytorch/executorch#897]
Context: https://github.com/pytorch/executorch/blob/main/examples/models/llama2/README.md?plain=1#L23

The current cache implementation in the original Llama2 repo is not supported by ExecuTorch, because ExecuTorch runtime assumes model data attributes being static.

**Comment by orionr** [comment]
@JacobSzwejbka is this now done? Just checking since we have it referenced from https://github.com/pytorch/executorch/tree/main/examples/models/llama2

**Comment by mergennachin** [comment]
@JacobSzwejbka can we close this github issue?
