### ISSUE TITLE
Performance comparison with Tencent NCNN?

### ISSUE THREAD

**Issue by 3i-Haseeb** [pytorch/executorch#996]
How does this compare with some existing mobile frameworks like Tencent's NCNN and TNN? How is it different from those?
Any insights will be helpful!

**Comment by kimishpatel** [comment]
Hello,
Thanks for the question. We havent done this benchmark comparison yet.

**Comment by SS-JIA** [comment]
Will close this issue for now. Right now we don't have comparative benchmark numbers, but will likely collect some data on this down the line.
